### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by rcritt** [dropbox/SwiftyDropbox#1]
It is great to see this API!
Does the API run on OS X?

I got the following error using CocoaPods.

_[!] The platform of the target `Pods` (OS X 10.10) is not compatible with `SwiftyDropbox (0.1)`, which does not support `OS X`._

**Comment by leah** [comment]
You're seeing that error because the instructions on the [blog post](https://blogs.dropbox.com/developers/2015/05/try-out-swiftydropbox-the-new-swift-sdk-for-dropbox-api-v2/) are for iOS only (see step #3). I think you can add OS X as a target should be able to install from CocoaPods. 

We haven't tested the SDK on OS X yet... but will hopefully get to it soon! In the meantime, if you'd like to test it out, we'd really appreciate your help and feedback.

**Comment by leah** [comment]
Sorry, I forgot to mention that user authorization may not work quite yet on OS X either.

**Comment by leah** [comment]
Okay, I did some quick testing and SwiftyDropbox isn't ready to support OS X yet at all. Thanks for bringing up this issue!

**Comment by rcritt** [comment]
I am glad if this info is useful to the development of this framework.

For the platform I get that error message even when adding "platform :osx, '10.7'" to my Podfile.

Thank you for the update on all this stuff.
For OS X it might be cool, if it is not today, to have the Keychain keep track of the token.  For example p2.OAuth2 does I think.

**Comment by leah** [comment]
Sure! We're already using the keychain to store the access token for iOS.

**Comment by nburns** [comment]
+1 for OSX support

**Comment by trondkr** [comment]
Agreed ! +1 for OSX support

**Comment by tkrajacic** [comment]
Any update on supporting OS X? (Haven't tested it I have to admit)

**Comment by nikolaeu** [comment]
+1

**Comment by lm2s** [comment]
+1

**Comment by Krivoblotsky** [comment]
+1

**Comment by AndrewSchenk** [comment]
+1

**Comment by jschweizer** [comment]
+1

**Comment by mjdescy** [comment]
+1

**Comment by Krivoblotsky** [comment]
Guys, I've just created PR with OSX support
https://github.com/dropbox/SwiftyDropbox/pull/49

Any feedback and help will be appreciated.

**Comment by ianbytchek** [comment]
@Krivoblotsky THANKS! Hope to look into this next week!

**Comment by varenc** [comment]
thanks for sharing this!

**Comment by btanner** [comment]
+1 It would be great to see this integrated.

Coming to OS X and iOS development without any knowledge of Objective-C or Cocoa, Swift has been a life saver for allowing me to quickly get traction. We're using SwiftyDropbox for our in-house iPad app and it was very easy to integrate.

Now we want to write a very simple desktop app to do some simple machinations to our Business Dropbox folders and we've hit this minor brick wall.  Krivoblotsky has the code written, but it's a bit out of my current experience level to correctly integrate his changes with this project to actually use his code :-)

**Comment by jhoughjr** [comment]
Bump!? No progress on this issue in a year?

**Comment by tkrajacic** [comment]
There hasn't been any real progress on the entire library for months. I'd guess it is because they were working on [Project Infinite](https://blogs.dropbox.com/business/2016/04/announcing-project-infinite/) and this library will be obsolete or replaced by something new?

**Comment by jhoughjr** [comment]
Surely it wouldn't be a huge effort for a few people to adapt to OS X since Foundation is shared.

**Comment by allea** [comment]
For iOS side, it's a must because the sandbox. But for the OS X side, a soft link pointing to the Dropbox sync folder will be adequate for many cases.

**Comment by scobbe** [comment]
Added in 60fca95
