### ISSUE TITLE
"Internal Server Error" returned from v2 API using Swift 2.0 branch

### ISSUE THREAD

**Issue by biodave42** [dropbox/SwiftyDropbox#10]
I fully appreciate that this is all pre-release stuff, but...

I _really, really_ hope you wonderful folks can get it together and prioritize shipping a production version of the v2 API with a Swift 2.0 SDK. You announced the beta way back in May. 

I too am using Xcode 7 and this Swift 2.0 branch and am confronted by this errror:

```
File didn't upload with error: Optional(Internal Server Error 502: <!DOCTYPE html>
<html>
<head><title>Dropbox - 5xx</title> 

[lots more HTML follows]

```
It's from the following code:
```
    func saveDataAsFileToDropBox(data:NSData, withFileName filePath:String) {
        
        if let client = Dropbox.authorizedClient {
            client.filesUpload(path: filePath, body: data).response { response, error in
                if let metadata = response {
                    print("Uploaded file: \(metadata.name)")
                } else {
                    print("File didn't upload with error: \(error)")
                }
            }
        } else {
            print("Whoops! Client not authorized")
        }
    }
```

**Comment by smarx** [comment]
What do you mean when you say "I **too**"? Is there another similar issue that you're referencing?

Are you able to consistently reproduce this error?

**Comment by rpearl** [comment]
Is this still occurring or was it transient?

Try using the newest master (now swift 2 syntax) version of the SDK. If there are still errors, they should have a 'request-id' attached so we can look up the error on the server side.

**Comment by rpearl** [comment]
I am going to close this as transient; if there's a consistent issue please follow up with more details (the request ID should be sufficient)
