### ISSUE TITLE
Cancel Download/Upload Requests

### ISSUE THREAD

**Issue by samfranz** [dropbox/SwiftyDropbox#100]
Providing thumbnails of the user's images in my app works perfectly, but if you navigate away from the page it still is trying to process the requests in the background. Not sure if there is some current way of doing this, but I'm not noticing it in any documentation.

**Comment by greg-db** [comment]
@samfranz Apologies there isn't better documentation on this, but if you keep a reference to any particular request, you can call `.cancel()` on it to cancel it.
