### ISSUE TITLE
Adding specific queue for RpcRequest

### ISSUE THREAD

**Issue by WingYn** [dropbox/SwiftyDropbox#102]
In Alamofire>ResponseSerialization.swift,

the response function has the parameter (...queue queue: dispatch_queue_t? = nil...), which makes it possible to run the completionHandler in a different queue other than the main queue.

This is not possible in the DropboxTransportClient.swift file class |RpcRequest|. The parameter can just be added in the response function and have a default value (nil) in the class |RpcRequest|.

**Comment by greg-db** [comment]
Thanks for posting this @WingYn ! I can't make any promises, but we'll consider this a feature request.

**Comment by scobbe** [comment]
Fixed by b52374e.
