### ISSUE TITLE
request: Alamofire.Request should be public

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#107]
in DropboxTransportClient.swift: 
`public class Request<RSerial: JSONSerializer, ESerial: JSONSerializer> {
    let request: Alamofire.Request
   ...
}`

`let request: Alamofire.Request` should public: for the caller app may need the task and request info in Alamofire.Request to re-setup UI for ongoing/resumed tasks.

**Comment by greg-db** [comment]
Thanks for the feedback!

**Comment by scobbe** [comment]
Fixed by 02d0038.
