### ISSUE TITLE
Xcode 8.0 GM_Seed complication

### ISSUE THREAD

**Issue by mobilestar0223** [dropbox/SwiftyDropbox#108]
When using `SwiftyDropbox` in Xcode 8.0 GM_Seed version, I am not able to compile project because `Alamofire` version(3.3.0) is not compatible with swift2.3 in current Xcode version.
Fully compatible `Alamofire` version is 3.5.0 for swift2.3 & Xcode 8.0
Is it possible to release a new version that supports current `Xcode 8.0 GM_Seed`?

**Thank you.**

**Comment by GasperC** [comment]
You would also make us extremely happy by solving this issue.

Thanks

**Comment by greg-db** [comment]
Yes, we're working on a Swift 3/Xcode 8 compatible branch: https://github.com/dropbox/SwiftyDropbox/issues/90
