### ISSUE TITLE
Xcode 8 and Swift3

### ISSUE THREAD

**Issue by JorgeAGomez** [dropbox/SwiftyDropbox#111]
I am trying to install Swiftydropbox with cocoapods in Xcode 8. However, I am having troubles after I convert the syntax to Swift3. Most of the problems is with Alamofire.

Any comments or suggestions about this issue?

Thanks.

**Comment by JorgeAGomez** [comment]
SwiftyDropbox is using Alamofire 3.3.1. The most recent Alamofire version is 4.0.0. Maybe updating to the last version will fix the issues with Swift 3.

**Comment by greg-db** [comment]
Thanks for the report! We are working on Swift 3 and Xcode 8 compatibility: #90 .
