### ISSUE TITLE
Swifty Dropbox DropboxServerTrustPolicyManager class throwing error!

### ISSUE THREAD

**Issue by rcdey** [dropbox/SwiftyDropbox#112]
Getting the following error:

![screen shot 2016-09-15 at 3 37 36 pm](https://cloud.githubusercontent.com/assets/17401020/18546235/742985a6-7b5a-11e6-9cc3-e507c1c21772.png)
![screen shot 2016-09-15 at 3 37 51 pm](https://cloud.githubusercontent.com/assets/17401020/18546236/742a8474-7b5a-11e6-8344-7c72d763e6c9.png)

**Comment by rogpfreck** [comment]
I get the above errors too. Using Xcode 8, converting to Swift 2.3. Using pod 'SwiftyDropbox', '~> 3.0.0'

**Comment by rogpfreck** [comment]
Noticed this error occurs in Alamofire: ServerTrusPolicy.swift. Using pod 'SwiftyDropbox', '~> 3.0.0' uses AlamoFire.

**Comment by greg-db** [comment]
Swift 2.3 support was released yesterday, in release 3.3.0. Please update to the latest version (currently [3.3.1](https://github.com/dropbox/SwiftyDropbox/releases/tag/3.3.1)) and let us know if you're still seeing this issue.
