### ISSUE TITLE
Bug 47 has reappeared since the swift 2.3 update

### ISSUE THREAD

**Issue by sportlabsMike** [dropbox/SwiftyDropbox#113]
[Bug 47](https://github.com/dropbox/SwiftyDropbox/issues/47)

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by sportlabsMike** [comment]
Thanks. I've raised pull request #114 with a fix!

**Comment by scobbe** [comment]
Thanks @sportlabsMike. This should be fixed now.

**Comment by sportlabsMike** [comment]
Thanks, is the fix only in the swift 3 update though? It might be useful to maintain a working swift 2.3 branch too for a while if possible.

Sent from my iPhone

> On 16 Sep 2016, at 22:25, Stephen Cobbe <notifications@github.com> wrote:
> 
> Thanks @sportlabsMike. This should be fixed now.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--

**Comment by greg-db** [comment]
We are planning on keeping a separate branch for Swift 2.3 for fixes like this. We'll have that out soon. Thanks!
