### ISSUE TITLE
Swift 3.0 Compatibility

### ISSUE THREAD

**Issue by winter7621** [dropbox/SwiftyDropbox#117]
I updated my Xcode today and when I opened a project that I'd been working on, Xcode prompted me to convert files to Swift 3.0 syntax. At first I tried to avoid converting, but I couldn't build the project without converting, so I had to convert.
After converting, I'm getting 800+ errors from SwiftyDropbox and another 700+ on Alamofire. I see that a commit was made a few days ago and that the current version is SwiftyDropbox 4.0.0, so I'm wondering if the latest code was made compatible with Swift 3.0 and I'm just missing something...? Or it's still not yet compatible? And if so, how can I resolve this?

**Comment by greg-db** [comment]
@winter7621 SwiftyDropbox was updated to work with Swift 3 as of 4.0.0. (Please grab the latest release though, currently 4.0.2.)

A `pod update` should be enough to get you on the latest version, but if you're still having trouble, you'll probably want to do something like:
- Delete your Pods folder and Podfile.lock file.
- Do a `pod repo update`
- Do a `pod install`
- Clean and rebuild your project.

(You may also need to set the "Use Legacy Swift Version" build setting to "No" for both Alamofire and SwiftyDropbox.)

**Comment by winter7621** [comment]
Thanks @greg-db will update tomorrow and give it a try. Off to bed for now

**Comment by Dirk23** [comment]
Once again i'm having trouble with swiftdropbox. I converted my project to Swift3.0 but it seems that Xcode 8.1 doesn't think that swiftydropbox is written in Swift3.0 even after i updated to swiftydropbox 4.1.1 and Alamofire 4.0.1

Error Message in Xcode:
`
Check dependencies
"Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
`
And suddenly there seem to be a lot of Files missing:
![bildschirmfoto 2016-12-13 um 18 22 17](https://cloud.githubusercontent.com/assets/4200682/21150977/2a50cee2-c161-11e6-948a-71893eaaea2a.png)

i already removed the pod file and the Pods Folder and reinstalled via pod install, but there are still issues.

What can i do?
