### ISSUE TITLE
JSON deserialisation crash for shared folders

### ISSUE THREAD

**Issue by lukestringer90** [dropbox/SwiftyDropbox#118]
When listing the contents of a folder (with `client.files.listFolder(path: "", recursive: false, includeMediaInfo: true, includeDeleted: false, includeHasExplicitSharedMembers: true)`) which contains shared folders, JSON deserialisation fails with a `fatalError` [at this line](https://github.com/dropbox/SwiftyDropbox/blob/master/Source/Source/PlatformNeutral/StoneSerializers.swift#L269).

The call chain:
<img width="1125" alt="screen shot 2016-09-16 at 23 49 03" src="https://cloud.githubusercontent.com/assets/987146/18603320/5d96d7bc-7c68-11e6-9a0c-0fdf30c955fc.png">

This method call appears to be of particular relevance:
<img width="1354" alt="screen shot 2016-09-16 at 23 49 47" src="https://cloud.githubusercontent.com/assets/987146/18603334/758082ba-7c68-11e6-903d-970ef1cd993d.png">

In this `deserialize(_)` method, `pathLower` identifies one of my shared folders.

**Comment by scobbe** [comment]
@lukestringer90: Thanks for reaching out. Are you using version SwiftyDropbox 4.0.2 (which was released like 10 minutes ago)?

**Comment by lukestringer90** [comment]
@scobbe That seems to have done the trick - my shared folders are now parsed correctly. Thanks for fixing! 👍
