### ISSUE TITLE
Conversion of SwiftyDropbox to Swift 3.0 requested when opening any Swift 3.0 project (e.g. TestSwifty_iOS)

### ISSUE THREAD

**Issue by dabeku** [dropbox/SwiftyDropbox#119]
When downloading the current version and installing the pods using **pod install** xcode tells me that I need to convert SwiftyDropbox to Swift 3.0. In fact, many class still have **public class** instead of **open class** and so on.

Is the conversion really necessary or do we have to wait until the whole code is ported to Swift 3?

The documentation of SwiftyDropbox says that the version is compatible with Swift 3+.

And yes, I'm definitely using the current SwiftyDropbox version:

pod install
Analyzing dependencies
Downloading dependencies
**Installing Alamofire (4.0.0)
Installing SwiftyDropbox (4.0.2)**
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.

Unfortunately, an automatic conversion of SwiftyDropbox to Swift 3.0 leads to 61 errors like:

.../Pods/SwiftyDropbox/Source/Source/PlatformNeutral/Async.swift:101:28: Incorrect argument label in call (have 'minLength:', expected 'maxLength:')

for the line: stringValidator(minLength: 1)(asyncJobId)

or

.../Pods/SwiftyDropbox/Source/Source/PlatformNeutral/Files.swift:288:31: Cannot convert call result type '(Array<_>) -> Void' to expected type '(_) -> Void'

for the line: nullableValidator(arrayValidator(itemValidator: stringValidator(minLength: 1, pattern: "(/|ptid:).*")))(includePropertyTemplates)

The required conversions:

<img width="1382" alt="screen shot 2016-09-17 at 11 07 07" src="https://cloud.githubusercontent.com/assets/14138808/18607215/0690f1be-7cc7-11e6-8f29-09178be1bd4f.png">

Thanks.

**Comment by winter7621** [comment]
No, you don't have to convert to Swift 3.0. You can instead work with your current code and tell Xcode to `Use Legacy Swift Language Version` when building. You can find this setting under **Project** > **Build Settings** > **Swift Compiler - Version** (near the end)

**Comment by dabeku** [comment]
No, you got me wrong: My project IS already Swift 3 but Xcode says that SwiftyDropbox IS NOT. Am I missing something here?

**Comment by greg-db** [comment]
SwiftyDropbox 4.0.2 should already work with Swift 3, so you don't need to have Xcode do the conversion on it. That is, you should only have Xcode convert your own app, and not the SwiftyDropbox/Alamofire pods. 

If you have gotten the pods into a bad state though, you can try deleting your Podfile.lock file and Pods folder, and then doing `pod install` to get fresh copies. 

Give that a try if you want and let us know if you're still having any trouble.

**Comment by scobbe** [comment]
b52374e cleaned a lot of this up, so try pulling the latest version (v4.0.3) and see if the problem persists.

**Comment by dabeku** [comment]
@scobbe Ah, great. A quick test shows no more conversions needed. Thanks.
