### ISSUE TITLE
A lot of hard crashes

### ISSUE THREAD

**Issue by solomon23** [dropbox/SwiftyDropbox#120]
SwiftyDropbox isn't a very friendly swift SDK.  It's got a ton of hard crashes in it which crashes out the app in all sorts of problems that is has internally.  That is not how swift likes to deal with things.  Methods that can throw need to be marked as **throws**.

Two quick examples.  If you call 'authorizeFromController' while you're already authorized.  Boom.  App crash.  Right now I'm seeing a hard app crash because dropbox isn't happy withe the response format of JSON to it's own endpoint.  Seeing as I as a consumer have no controller over either of those things - it needs to not crash my app and just set a failed state somewhere

see StoneSerializers.swift line 284
Auth.swift line 98

All the precondition code.  Those should all be hard errors ? If so, they need to all be marked as Throws

There's something like 24 fatalError calls in the code.  Are all those conditions meant to crash my app ?

SwiftyDropbox 4.0 / Swift 3

**Comment by solomon23** [comment]
Here's the JSON i'm getting back that's causing the hard crash:

([String : Dropbox.JSON]) $R1 = 1 key/value pair {
  [0] = {
    key = "reason"
    value = dictionary {
      dictionary = 1 key/value pair {
        [0] = {
          key = ".tag"
          value = str (str = "too_many_write_operations")
        }
      }
    }
  }
}

I would say that doesn't deserve an app crash.

Why can't I upload 50 files ?

**Comment by scobbe** [comment]
@solomon23: In theory, if you're hitting the assert statements, your code is incorrectly written and therefore should not be "handled". It should be rewritten, which is why we have the hard crashes in the `authorizeFromController` method.

To upload 50 files, please use our (batch upload)[https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start] endpoint, to avoid the `too_many_write_operations` error.

**Comment by solomon23** [comment]
There's two hard crashes in the code
1. the 'precondition'.  Again.  Swift has a process where if a method is going to throw it needs to be marked as throw.  Debug asserts could make sense, but production crashes seem extreme

2. It throws a bunch of fatal errors when it's having trouble parsing JSON and other cases.  These again are hard crashes that should be failure states.

Generally you want to AVOID crashes as much as possible.  Because dropbox is unhappy with something doesn't mean my app can no longer function

**Comment by scobbe** [comment]
Oh, so the `too_many_write_operations` response is causing a hard crash? Well that certainly is a problem. We'll look into it and try and get a fix out ASAP. Thanks for letting us know.

**Comment by solomon23** [comment]
Great thanks.  A good place to start is to scan the codebase for "fatalError()" calls

**Comment by scobbe** [comment]
@solomon23: I suspect that the `too_many_write_operations` crash relates to an issue that was fixed in v4.0.2 of SwiftyDropbox. Would you mind pulling the latest version of the SDK and see if you still see the problem when you get a `too_many_write_operations` error from the API? We'd really appreciate it. Thanks for your patience.

**Comment by solomon23** [comment]
@scobbe I apologize, I should have updated the ticket.  I was spawning three threads to upload the files.  Once I reduced it to two threads I stopped getting the error.  Tonight I'll both try the batch operation and update to 4.0.2

**Comment by scobbe** [comment]
@solomon23: Ok, sounds good! Thanks!

**Comment by solomon23** [comment]
Wanted to come back and update the thread:
1. Didn't have much luck getting batch to work.  Maybe some example code would help
2. I updated to 4.0.4 and with 4 threads uploading at once was able to upload 350 files without  the 'too many writes error'.  So that's nice.  I'll test it out more tomorrow.
3. I'd still like to understand the thinking about why it's ok to have FatalError calls inside the SDK.  What conditions in dropbox are ok to crash out my app ?

**Comment by solomon23** [comment]
Oh also.  Not sure if you want another bug on this but many of your methods should be marked @discardableResult.

**Comment by scobbe** [comment]
@solomon23: Thanks for the feedback. You're right about `@discardableResult`, I'll make that change tomorrow. As far as batch upload, you're also right, some example code would be helpful. I'll try and put some up in the next day or two.

As far as the `fatalError` calls, I hear you, these shouldn't be used lightly. I can take a look at surfacing some more benign errors, but honestly, these `fatalError` calls are in places that should never be executed in normal control flow. If they are, then something is seriously wrong with the SDK's state or with the server itself. But I'll take a look and see if we can reduce our reliance on them.

Let us know if you spot anything else. Thanks for the help.

**Comment by bitsarat** [comment]
I would like to report the exact same problem. I am getting an AuthError (invalid_access_token) on an upload, so I try to reauthorize the client (as suggested in the docs). My app crashes. I am not trying any batch uploads.

**Comment by scobbe** [comment]
@bitsarat: Sorry you're running into issues. Would you mind posting a strack trace of your error?

**Comment by bitsarat** [comment]
Not an issue anymore (kind of). I had to call unlinkClient() to invalidate the token.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to eliminate fatal errors from serialization. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by julianlocke** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
