### ISSUE TITLE
Umbrella header for module 'SwiftyDropbox' does not include header 'SecurityUtil.h'

### ISSUE THREAD

**Issue by xiles** [dropbox/SwiftyDropbox#123]
I got this warning message when building with Xcode 8/Swift 3.
I'm using SwiftyDropbox via CocoaPods.

**Comment by scobbe** [comment]
@xiles: Are you using the latest version of SwiftyDropbox (v4.0.3)?

**Comment by xiles** [comment]
Yes, I'm using the latest version(v4.0.3)

**Comment by scobbe** [comment]
@xiles: The `SecurityUtil.h` file is from an older version of the SDK, so there must be some corrupted state remaining from the older SDK. Please try the following:

- `rm -rf MyProject/Pods`
- `rm -rf MyProject/MyProject.xcodeworkspace`
- `rm -rf MyProject/Podfile.lock`

and then rerun `pod install`.

Let me know if the problem still persists after you follow these steps. If it does, we can try additional steps. Thanks for your patience!

**Comment by xiles** [comment]
Thanks.
It's been resolved.
I should've done it before writing here. : )
