### ISSUE TITLE
swift_2_3 branch currently does not compile

### ISSUE THREAD

**Issue by koppacetic** [dropbox/SwiftyDropbox#125]
To reproduce:

    git clone https://github.com/dropbox/SwiftyDropbox.git
    git checkout tags/3.4.0
    carthage checkout
    carthage update --platform iOS
    Build in Xcode

You'll get hundreds of errors like:

    Type 'JSON' has no member 'null'
    Type 'JSON' has no member 'number'

Using Xcode 8

**Comment by scobbe** [comment]
@koppacetic: Thanks for pointing this out and sorry for the inconvenience. Try performing these steps again, and the project should compile in Xcode now. Let me know if you run into any other issues.

**Comment by koppacetic** [comment]
That fixed it. Thank you, sir!
