### ISSUE TITLE
swift_2_3 branch: Minimum deployment target needs to iOS 9

### ISSUE THREAD

**Issue by koppacetic** [dropbox/SwiftyDropbox#126]
The current minimum deployment target on the swift_2_3 branch is iOS 10. However, I would think most people sticking with Swift 2.3 are doing so in order to support iOS 9.

**Comment by greg-db** [comment]
@koppacetic Can you let me know where you're seeing iOS 10 as the target for that branch? I believe the intent on that branch was to target iOS 8, which is what it's the podspec:

https://github.com/dropbox/SwiftyDropbox/blob/swift_2_3/SwiftyDropbox.podspec

Thanks!

**Comment by koppacetic** [comment]
I'm using Carthage so it's getting the minimum deployment target from the project file. That's where you need to change it.

**Comment by greg-db** [comment]
Thanks! We'll look into it and get that fixed up.

**Comment by scobbe** [comment]
@koppacetic: Thanks for letting us know. I updated the `swift_2_3` branch's Xcode project to include the correct iOS target. Let us know if you run into any more issues!
