### ISSUE TITLE
ld: framework not found Webkit

### ISSUE THREAD

**Issue by hoppus** [dropbox/SwiftyDropbox#128]
Using last 4.1.0 version
Getting error while trying to make build

![image](https://cloud.githubusercontent.com/assets/8390511/19830312/c15ee850-9dfd-11e6-852f-fec0b2025bd9.png)

![image](https://cloud.githubusercontent.com/assets/8390511/19830313/c76617fa-9dfd-11e6-8e84-bbc7d4327a70.png)

Please help!

**Comment by greg-db** [comment]
Hi @hoppus , what version of Xcode are you using, and what's your project's deployment target? Thanks in advance!

**Comment by hoppus** [comment]
@greg-db Xcode 8, taget 9.2

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by scobbe** [comment]
@hoppus: Sorry for the delay on our end in getting back to you here.

Could you confirm with me that you have the .xcworkspace file open and NOT the .xcodeproj file open? Sometimes these framework linking issues arise from that.

If you do have the .xcworkspace open, would you mind sending me a screenshot of this menu in your project:

![image](https://cloud.githubusercontent.com/assets/17483354/20086019/f15f8066-a521-11e6-9ea9-038b94f892d0.png)

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20136523/5e267906-a686-11e6-8c49-ff492beea6f1.png)

**Comment by scobbe** [comment]
@hoppus: Thanks for your reply and for your patience.

Would you mind sending me a screenshot from Apple Menu > About this Mac >System Report button > Software > Developer: 

![image](https://cloud.githubusercontent.com/assets/17483354/20148980/fcbd69e4-a663-11e6-90cd-d2a22ba44517.png)

Just want to rule out some more basics. Thanks for bearing with me.

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20151278/99923342-a6ca-11e6-9bb3-c6d44ce1ac88.png)

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20151308/b3cbe924-a6ca-11e6-8f11-bf2589aa6ed5.png)

**Comment by scobbe** [comment]
@hoppus: Thanks again for the reply. Is there anyway that you might be compiling with an older iOS SDK? I'm not totally sure how that might happen, but maybe an older version of Xcode or something is getting in the way.

Please confirm one more thing:

![image](https://cloud.githubusercontent.com/assets/17483354/20160714/f3df1716-a69d-11e6-990d-72541413e553.png)

I want to make sure that you're getting your frameworks (here, `Foundation.framework`) from an iOS SDK >= 8. What path is your `Foundation.framework` linking with?

Mine is: `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk/System/Library/Frameworks/Foundation.framework`

Thanks for your patience!

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20186178/fe5ee4d6-a77f-11e6-85d7-6406c140c493.png)

**Comment by scobbe** [comment]
@hoppus: Ok, thanks again. This is helpful. Would you mind attaching the full build logs of your project here? We should be able to get to the bottom of it with the logs. Thanks again for your patience.

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20213042/8005ffaa-a817-11e6-8a9f-d702e7da3bd1.png)

**Comment by scobbe** [comment]
@hoppus: Thanks a lot!

Would you also send me the output of the following commands:

Would you both of you mind sending me the output of the following two commands:
- `xcode-select -p`
- `xcodebuild -project <MY_PROJECT>.xcodeproj -target "<MY_PROJECT_TARGET>" -showBuildSettings > build_settings.txt`

This should be my last request from you two. Thanks for your patience!

And could you send the me **full** build log, using the following **Save...** button.

![image](https://cloud.githubusercontent.com/assets/17483354/20234028/151c75de-a82b-11e6-8d5a-d0852ab2075d.png)

Thanks in advance!

**Comment by hoppus** [comment]
![image](https://cloud.githubusercontent.com/assets/8390511/20239259/8a773476-a90d-11e6-9d83-b71bc64cc0a0.png)

[build_settings.txt](https://github.com/dropbox/SwiftyDropbox/files/587326/build_settings.txt)

[Build target SwiftyDropbox.txt](https://github.com/dropbox/SwiftyDropbox/files/587318/Build.target.SwiftyDropbox_2016-11-12T19-17-51.txt)

**Comment by hoppus** [comment]
@scobbe 
![image](https://cloud.githubusercontent.com/assets/8390511/20239259/8a773476-a90d-11e6-9d83-b71bc64cc0a0.png)

[build_settings.txt](https://github.com/dropbox/SwiftyDropbox/files/587337/build_settings.txt)

[Build target SwiftyDropbox.txt](https://github.com/dropbox/SwiftyDropbox/files/587335/Build.target.SwiftyDropbox.txt)

**Comment by scobbe** [comment]
This should be fixed [here](https://github.com/dropbox/SwiftyDropbox/commit/7b9792064ac9f5e41565e1cb2a6ba52d8cd3be0e).
