### ISSUE TITLE
Can it be used in a environnement without UI ?

### ISSUE THREAD

**Issue by mackoj** [dropbox/SwiftyDropbox#13]
Hi,

I need to use the Dropbox API in a environnement without UI(script/playground) in Swift.
Can your SwiftyDropbox work in this case ?

Thanks

**Comment by leah** [comment]
I think so, though I haven't tried. You won't be able to do authentication via the default OAuth flow but could use a generated access token or ask the user to go to the URL to auth. I think everything else should work fine from a script.

**Comment by mackoj** [comment]
Thanks
