### ISSUE TITLE
NSURLErrorDomain Code -999 when call SwiftyDropbox method

### ISSUE THREAD

**Issue by mamcx** [dropbox/SwiftyDropbox#132]
I have incorporated the Dropbox API V2, with permission of "App Folder".

The call using curl succeed:

    curl -X POST https://api.dropboxapi.com/2/files/list_folder \
      --header 'Authorization: Bearer vSBSoEs...............' \
      --header 'Content-Type: application/json' \
      --data '{"path":""}'

However, calling using the latest swift api fail with:

 
    Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://api.dropbox.com/2/files/list_folder, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://api.dropbox.com/2/files/list_folder}

I have followed the steps to incorporate the API, and use this to call the client:

    func authDropbox() -> DropboxClient {
        let client = DropboxClient(accessToken: DROPBOX_TOKEN)
        
        return client
    }

    enum DropBoxListResult {
        case Files(Array<Files.Metadata>)
        case Error(String)
    }

    enum DropBoxResult {
        case Result(Files.FileMetadata)
        case Error(Error)
        case PathError
    }

    func listDropbox(name:String, result: @escaping ((DropBoxListResult) -> Void))
    {
        Log.info("List:", name)
        
        let client = authDropbox()
        
        client.files.listFolder(path: name).response { response, error in
            
            if let r = response {
                Log.info(response)
                result(DropBoxListResult.Files(r.entries))
            } else if let error = error {
              //Always get error here...
                Log.error(error)
                result(DropBoxListResult.Error(String(describing: error)))
            }
        }
    }

**Comment by greg-db** [comment]
It looks like your `client` object is probably going out of scope before the request can finish. Try keeping your `client` around. For example, you can use `DropboxClientsManager.authorizedClient`.

**Comment by mamcx** [comment]
But that will not work with  `DropboxClient(accessToken: DROPBOX_TOKEN)`?

Also, why will get out of scope if the call is from client?

**Comment by greg-db** [comment]
You can manually set your own `authorizedClient` is you need to like:

`DropboxClientsManager.authorizedClient = DropboxClient.init(...)`

Also, the actual API calls are made asynchronously, so the `client` object may be gone by the time the network call finishes.
