### ISSUE TITLE
Is there a function I can use to delete a folder in Dropbox. I use the createFolder function when making a folder but I can't find one for deleting a folder? 

### ISSUE THREAD

**Issue by MarianneMoerk** [dropbox/SwiftyDropbox#134]

**Comment by greg-db** [comment]
Yes, you can use the [`delete`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes6deleteFT4pathSS_GCS_10RpcRequestCCS_5Files18MetadataSerializerCS2_21DeleteErrorSerializer_) method to delete folders in addition to files.

**Comment by MarianneMoerk** [comment]
Thanks I will try that :-)
