### ISSUE TITLE
file download issue

### ISSUE THREAD

**Issue by MarianneMoerk** [dropbox/SwiftyDropbox#135]
Hi,

I have tried using the download functionality of swiftyDropBox to access a text file in Dropbox (in JSON format).

I have used the example from the Documentation to download the file (Both the URL and the Data versions). In any case it seems like the response object only contains the metadata and the file size... not the actual content of the file (the text).

e.g.: 

   func getFileFromDropBox(){
      client?.files.download (path: "/myFolder/test.JSON")
            .response { response, error in
                if let response = response {
                    let responseMetadata = response.0
                    print("response:")
                    print(response)
                    let fileContents = response.1
                    print(fileContents)                    
                } else if let error = error {
                    print(error)
                }
            }
            .progress { progressData in
                print(progressData)
        }
    }

The print statements results in the following output:

response:
({
    "client_modified" = "2016-11-26T21:09:38Z";
    id = "id:c30e-4eX2uAAAAAAAAAAMQ";
    name = "test.JSON";
    "path_display" = "/myFolder/test.JSON";
    "path_lower" = "/myFolder/test.json";
    rev = 5150b59f20;
    "server_modified" = "2016-11-26T21:09:38Z";
    size = 128;
}, 128 bytes)
128 bytes

What am I doing wrong? :-)

Is there some way of accessing the actual contents (the text) of a file that I download from Dropbox via swiftyDropBox?

Thanks in advance!

**Comment by greg-db** [comment]
The `fileContents` variable here is a `Data` object, so if you want to treat it as text, you can convert it to a `String` object, for example:

```
if let response = response {
    let responseMetadata = response.0
    print(responseMetadata)
    let fileContents = response.1
    print(String(data: fileContents, encoding: String.Encoding.utf8))
}
```

**Comment by MarianneMoerk** [comment]
Great it works now, thank you very much :-)
