### ISSUE TITLE
How to get full path of file?

### ISSUE THREAD

**Issue by kiran5232** [dropbox/SwiftyDropbox#136]
Hello 

I want full path of file. I don't want to download file.
But i got response like :
 {  
   tag" = file;
    name = "BODYBIO_SEPT_16_.apk";
    "path_display" = "/BODYBIO_SEPT_16_.apk";
    "path_lower" = "/bodybio_sept_16_.apk";

}
Please provide me steps or any other information to get full path.

Thanks.

**Comment by greg-db** [comment]
To get file metadata without downloading file contents, you can use [`getMetadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes11getMetadataFT4pathSS16includeMediaInfoSb14includeDeletedSb31includeHasExplicitSharedMembersSb_GCS_10RpcRequestCCS_5Files18MetadataSerializerCS2_26GetMetadataErrorSerializer_) (to get information for a single file) or [`listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes10listFolderFT4pathSS9recursiveSb16includeMediaInfoSb14includeDeletedSb31includeHasExplicitSharedMembersSb_GCS_10RpcRequestCCS_5Files26ListFolderResultSerializerCS2_25ListFolderErrorSerializer_) and [`listFolderContinue`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes18listFolderContinueFT6cursorSS_GCS_10RpcRequestCCS_5Files26ListFolderResultSerializerCS2_33ListFolderContinueErrorSerializer_) (to list items in a folder).

In either case, the returned [`Metadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html) will include [`pathLower`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html#/s:vCC13SwiftyDropbox5Files8Metadata9pathLowerGSqSS_) and [`pathDisplay`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html#/s:vCC13SwiftyDropbox5Files8Metadata11pathDisplayGSqSS_), which are the full path of the files location in the account. For apps with the app folder permission though, the path is the path relative to your app folder.

For example:

    DropboxClientsManager.authorizedClient!.files.getMetadata(path:"id:25N5ksooX-sAAAAAAAAU8g").response { response, error in
        if let metadata = response {
            print(metadata.pathLower!)
        } else {
            print(error!)
        }
    }

prints:

> /photos/2013-09-18-14-05-53.jpg

**Comment by kiran5232** [comment]
Hey grab 
 Thanks for your quick answered.

Thank you so much
