### ISSUE TITLE
Share auth token between containing app and appex

### ISSUE THREAD

**Issue by evgeniyd** [dropbox/SwiftyDropbox#138]
Is it possible [out of the box] to authorize user via containing app, obtain the auth token and then, retrieve this token from the app extension (appex)?

**Comment by greg-db** [comment]
While the SDK does try to be safe for app extensions (e.g., [here](https://github.com/dropbox/SwiftyDropbox/blob/2705fe1726a286b9f95709b03b2c9c5229286cdb/Source/SwiftyDropbox/SwiftyDropbox_iOS/iOS/OAuthMobile.swift#L39)) unfortunately I don't believe SwiftyDropbox has any specific support or documentation for using it with extensions in particular. I'll be sure to pass this along as a request though.

**Comment by evgeniyd** [comment]
Hi @greg-db 

To discuss this, I'd like to point out few questions:

1. Is there any security drawbacks in sharing the auth token between containung app and appex (assumming the sharing happens via the keychain)?
2. What feature design would be more appropriate here: to add a shares keychanin support in the framework and pass the keychains group id to it at the point of configuration OR add keychain protocol and let the client to implement the secure storage in a way he wants to? Third option: none of above, but something else.

Thanks

**Comment by greg-db** [comment]
Thanks for the additional information and feedback! I don't have any official guidance or a timeline for if or when this may be added/documented right now, but I've sent this along as a feature request with a link to this issue for these questions.

**Comment by evgeniyd** [comment]
Hi @greg-db 

Thank you very much for pushing it forward!

Hopefully, there would be more people involved into this thread to discuss the existance of this feature and an appropriate design.

**Comment by julianlocke** [comment]
In the latest version of SwiftyDropbox, it's possible to call auth'd routes from app extensions. See https://github.com/dropbox/SwiftyDropbox/blob/1fd30c039ce14c1e2f293870bdb60c513ebc777b/TestSwiftyDropbox/TestSwiftyDropbox_ActionExtension/ActionRequestHandler.swift for an example. Read more about the release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
