### ISSUE TITLE
Swift 3.0 

### ISSUE THREAD

**Issue by Dirk23** [dropbox/SwiftyDropbox#140]
Once again i'm having trouble with swiftdropbox. I converted my project to Swift3.0 but it seems that Xcode 8.1 doesn't think that swiftydropbox is written in Swift3.0 even after i updated to swiftydropbox 4.1.1 and Alamofire 4.0.1

Error Message in Xcode:
`
Check dependencies
"Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
`

![bildschirmfoto 2016-12-13 um 18 25 22](https://cloud.githubusercontent.com/assets/4200682/21151097/90e67eae-c161-11e6-8d45-3c51ad671491.png)

And suddenly there seem to be a lot of Files missing:
![bildschirmfoto 2016-12-13 um 18 22 17](https://cloud.githubusercontent.com/assets/4200682/21150977/2a50cee2-c161-11e6-948a-71893eaaea2a.png)

i already removed the pod file and the Pods Folder and reinstalled via pod install, but there are still issues.

What can i do?

**Comment by greg-db** [comment]
Hi @Dirk23! SwiftyDropbox should certainly work with Swift 3.0, and doesn't need to be converted, as long as you're using version 4+ of SwiftyDropbox, as you mentioned you are.

So, while you don't need to convert them, can you check if you have `SWIFT_VERSION` set for each target? You can do that in build settings, but make sure you select each target (that is, select both SwiftyDropbox and then Alamofire to check both.) 

Also, I think the missing files issue may be related to the source control system. Are you using the Xcode source control integration?

**Comment by Dirk23** [comment]
@greg-db Thank you, but i'm not that experienced, so im not sure what exactly to do. After following some other conversions in Xcode, only Alamofire tells me that there is something wrong:
![bildschirmfoto 2016-12-15 um 19 17 00](https://cloud.githubusercontent.com/assets/4200682/21236389/1bc36f06-c2fb-11e6-84ea-214efe79d2ac.png)
So i got to Build Settings -> Alamofire and searched for "swift_version":
![bildschirmfoto 2016-12-15 um 19 21 33](https://cloud.githubusercontent.com/assets/4200682/21236552/be7fa188-c2fb-11e6-945f-f003381ab2c0.png)
But what should i do here?

I don't use Xcode for Git, i use Sourcetree. What does this have to do with the missing files?

**Comment by greg-db** [comment]
That one's still marked as unspecified. Try switching it to "No" (as in use Swift 3.0, and not "legacy" 2.3).

Also, I believe the "missing" file warnings in Xcode are for the source control system, even if you don't use the controls in Xcode itself. If you check the status of your repo via SourceTree that may provide some insight on that.

**Comment by evgeniyd** [comment]
@Dirk23 what version (`$ pod --version`) do you use?  If it is not `1.1.0.rc.2`, install that specific and try again. 

Otherwise, take a look at [this issue from Alamofire](https://github.com/Alamofire/Alamofire/issues/1526).
