### ISSUE TITLE
Use of unresolved identifier 'self'

### ISSUE THREAD

**Issue by traviskaenel** [dropbox/SwiftyDropbox#142]
I'm following the tutorial and when I put this code into the viewController 

    import UIKit
    import SwiftyDropbox

    func myButtonInControllerPressed()
    {
        DropboxClientManager.authorizeFromController(UIApplication.shared, controller: self, openURL: { (url: URL) -> Void in UIApplication.shared.openURL(url)})
    }

I get an error "Use of unresolved identifier 'self'"

I know this must be because the func is declared at the global level, but I don't know what to do to fix it since I'm following the tutorial. 

I'm using Xcode 8.2, Swift 3, and iOS 10.1

**Comment by greg-db** [comment]
The `authorizeFromController` method's `controller` parameter should be a `UIViewController`, so this method should be called from inside your view controller. That way, `self` will be defined as your controller. Try moving the method and let me know if that doesn't help.

**Comment by traviskaenel** [comment]
Thank you for your help! Moving the code got rid of the error, but now I'm getting another error, and I expect I won't be able to run the app still (this is not my first time going through the tutorial).
![screen shot 2016-12-29 at 12 07 10 pm](https://cloud.githubusercontent.com/assets/16711173/21553891/06cd2388-cdc0-11e6-9f79-f186d35868fd.png)

**Comment by greg-db** [comment]
The code in your screenshot isn't the same as the code from the documentation. It should be:

    DropboxClientsManager.authorizeFromController(UIApplication.shared,
                                                  controller: self,
                                                  openURL: { (url: URL) -> Void in
                                                    UIApplication.shared.openURL(url)
                                                  })

**Comment by traviskaenel** [comment]
Yes, but 
![screen shot 2016-12-29 at 12 18 52 pm](https://cloud.githubusercontent.com/assets/16711173/21554017/004fd3a6-cdc1-11e6-9e71-8db393655fe2.png)

**Comment by greg-db** [comment]
Yes, that's just a warning. It's ok to use for now. We'll update that in the future.

**Comment by traviskaenel** [comment]
Ok, thank you. I just ran it, and all I get is a blank screen on my phone. Aren't I supposed to get a Dropbox login screen like it says in your tutorial?
