### ISSUE TITLE
Error: Thread 1: signal SIGABRT

### ISSUE THREAD

**Issue by traviskaenel** [dropbox/SwiftyDropbox#143]
I'm following the tutorial, and am to the point where I should be able to launch the app for the first time, and log in to Dropbox. When I launch the app, and hit the button that should send me to the in-app login page, I get the error "Thread 1: signal SIGABRT"

Here's the AppDelegate code

import UIKit
import SwiftyDropbox

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {                                             **Thread 1: signal SIGABRT**

    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        DropboxClientsManager.setupWithAppKey("qcvovib4h1mn0zd")
        return true
    }
    

The ViewController code

import UIKit
import SwiftyDropbox

class ViewController: UIViewController {
    @IBOutlet weak var launchDropbox: UIButton!
    
    
    @IBAction func launchDropboxPressed(_ sender: UIButton)
    {
        DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self,
                                                      openURL: { (url: URL) -> Void in
                                                        UIApplication.shared.openURL(url)
        })
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

Here's the output

2016-12-30 13:24:35.984822 GaethrExample[1635:456488] -[GaethrExample.ViewController launchDropbox:]: unrecognized selector sent to instance 0x139e09360
2016-12-30 13:24:35.995965 GaethrExample[1635:456488] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[GaethrExample.ViewController launchDropbox:]: unrecognized selector sent to instance 0x139e09360'
*** First throw call stack:
(0x18b6a61c0 0x18a0e055c 0x18b6ad278 0x18b6aa278 0x18b5a459c 0x191536484 0x191536404 0x1915208b8 0x191535cf0 0x191535818 0x191530a60 0x19150152c 0x19f54953c 0x191ceea54 0x191ce84bc 0x18b654278 0x18b653bc0 0x18b6517c0 0x18b580048 0x18d006198 0x19156c2fc 0x191567034 0x1000fdb70 0x18a5645b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by greg-db** [comment]
[Cross-linking for reference: https://stackoverflow.com/questions/41389361/what-can-i-do-to-fix-the-error-thread-1-signal-sigabrt ]

The error is indicating that the issue is that `launchDropbox` is not recognized as a selector. That's not about the Dropbox SDK itself though, so I'm afraid I can't be much help, as that's outside my area of expertise.
