### ISSUE TITLE
Download seems to stop when app is backgrounded.

### ISSUE THREAD

**Issue by sola92** [dropbox/SwiftyDropbox#144]
Every time the app is backgrounded during a download. I receive this error inside the `SessionDelegate.taskDidComplete` after returning to the app:

`Error Domain=NSURLErrorDomain Code=-997 "Lost connection to background transfer service" UserInfo={NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/download, NSLocalizedDescription=Lost connection to background transfer service, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/download}`

Here's how I am creating the client:
```swift
let transportClient =  DropboxTransportClient(
  accessToken: token.accessToken,
  baseHosts: nil,
  userAgent: nil,
  selectUser: nil,
  sessionDelegate: nil,
  backgroundSessionDelegate: backgroundSessionDelegate,
  serverTrustPolicyManager: nil
)

client = DropboxClient(transportClient: transportClient)
```

And the subsequent request:

```swift
    client.files.download(path: file.id)
    .response(queue: queue, completionHandler: { response, error in
      if let error = error {
        print("Dropbox download error: \(error.description)")
      }
    })
    .progress { progressData in
      print("progress: \(CGFloat(progressData.fractionCompleted))")
    }
```

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as support for background sessions. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by julianlocke** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
