### ISSUE TITLE
Get id of file or folder

### ISSUE THREAD

**Issue by attheodo** [dropbox/SwiftyDropbox#147]
Hello I have a method for listing entries in a folder 

```swift
public func listFolder(path: String, withCompletionHandler handler: @escaping ListFolderResultClosure) {
        dropboxClient?.files.listFolder(path: path).response { response, error in
            
            guard let response = response, error == nil else {
                handler(nil, error)
                return
            }
            
            var entries: [Files.Metadata] = []
            
            for entry in response.entries {
                if self.isFolder(entry: entry) || self.isPhoto(entry: entry) {
                    entries.append(entry)
                }
            }
            
            // sort alphabetically
            entries = entries.sorted(by: { $0.name < $1.name })
            
            handler(entries, nil)
            
        }
    }

```

I can access the `name`, `pathDisplay`, `pathLower` and `parentFolderId` on `entry`, however I also need the id of the file or folder itself. I can see the `description` property prints the `id` but it's not included as a property.

Any ideas?

**Comment by greg-db** [comment]
The `id` property is only available on [`FileMetadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FileMetadata.html) and [`FolderMetadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FolderMetadata.html), and not [`Metadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html) itself, so you'll need to cast these objects accordingly to access these properties. For example, for a [`Metadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html) you know is a  [`FolderMetadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FolderMetadata.html), you can do something like:

    print((entry as! Files.FolderMetadata).id)
