### ISSUE TITLE
Swift Package Manager can't install / compile

### ISSUE THREAD

**Issue by rolandleth** [dropbox/SwiftyDropbox#148]
I left a comment in issue #122, but I thought it would be better to open a new one.

I added this to the `Packages` file:

```
.Package(url: "https://github.com/dropbox/SwiftyDropbox", majorVersion: 4) 
// Tried with .git as well, but I don't know the difference between them
```

It resolves to the latest version, `4.1.1`, then resolves Alamofire to `4.0.0`, then it throws an error:

```
error: the package has an unsupported layout, unexpected source file(s) found: 
<all paths to test files, located in ./Packages/Alamofire-4.0.0/Tests>
fix: move the file(s) inside a module
```

Manually changing the `Packages` file in the `SwiftyDropbox` package to resolve Alamofire to `4.3.0` fixed the issue, but compiling still throws an error, though:

```
./Packages/SwiftyDropbox-4.1.1/Source/SwiftyDropbox/SwiftyDropbox_iOS/iOS/OAuthMobile.swift:6:8: error: no such module 'UIKit'
import UIKit
```

Am I doing something utterly wrong?

**Comment by greg-db** [comment]
Thanks for the report! We'll take a look.

**Comment by rolandleth** [comment]
Awesome, let me know if I can help.

**Comment by ios3** [comment]
Same here

**Comment by Dids** [comment]
Any updates on this?

**Comment by greg-db** [comment]
@Dids I don't have a resolution for this, but I recommend instead following #252 where we're tracking the current incompatibility with Swift Package Manager. I'm closing this old issue in favor of that one.
