### ISSUE TITLE
FileMetadataSerializer is missing the field content_hash

### ISSUE THREAD

**Issue by ratzinho87** [dropbox/SwiftyDropbox#149]
The SwiftyDropbox API is missing the field content_hash from the file metadata response, as documented in the HTTP API here: https://www.dropbox.com/developers/documentation/http/documentation#files-get_metadata.

**Comment by greg-db** [comment]
Hi @ratzinho87 that field was recently introduced to the API and hasn't yet been added to SwiftyDropbox. It should be available in the next release of SwiftyDropbox.

**Comment by ratzinho87** [comment]
@greg-db Thanks for letting me know. Where can I find out when the next release is scheduled?

**Comment by greg-db** [comment]
We don't have a set schedule, but I'll ask the team for do a release soon. (cc/ @scobbe )
