### ISSUE TITLE
CocoaPods error

### ISSUE THREAD

**Issue by dennisbirch** [dropbox/SwiftyDropbox#15]
I created an empty project, added a Podfile to its base directory, added the Podfile text as copied from the Github SwiftyDropbox page to the Podfile text and then did a "pod install" command from terminal in the project's directory. I get this result in Terminal:

Analyzing dependencies
Pre-downloading: `SwiftyDropbox` from `git@github.com:dropbox/SwiftyDropbox.git`, tag `0.5`

[!] Error installing SwiftyDropbox
[!] /usr/local/bin/git clone git@github.com:dropbox/SwiftyDropbox.git /var/folders/3g/sdbb2z916x98ryt1x2fj36280000gn/T/d20151018-19994-qpyfd8 --single-branch --depth 1 --branch 0.5

Cloning into '/var/folders/3g/sdbb2z916x98ryt1x2fj36280000gn/T/d20151018-19994-qpyfd8'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

------
Anybody know what's going on and how to fix this?

**Comment by DouglasHeriot** [comment]
Have you set up your public keys in your github account?
https://help.github.com/articles/error-permission-denied-publickey/

**Comment by dennisbirch** [comment]
Yes I have. But I guess I haven't used it my SSH key with GitHub since upgrading to a new Mac. I didn't have to change anything after upgrading for the repository I use for my private projects, so I never bothered to change it on GitHub. I just updated the key on GitHub and it worked. Thanks for pointing me in the right direction.
