### ISSUE TITLE
can not upload image

### ISSUE THREAD

**Issue by MirAshrafUddin** [dropbox/SwiftyDropbox#152]
image is not uploading. where is the problem? not found any error
![screen shot 2017-03-06 at 8 27 50 pm](https://cloud.githubusercontent.com/assets/26216065/23614054/e1770aec-02ab-11e7-86ba-8543b9bba88b.png)

**Comment by greg-db** [comment]
If you're not getting `error` back, are you getting `response` back? If so, what is it?

Or is your `response` block just not getting called at all? If not, make sure your `client` object is not `nil` and that it's not going out of scope.

**Comment by MirAshrafUddin** [comment]
Thanks @greg-db I am getting this error while creating a folder
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://api.dropbox.com/2/files/create_folder, NSLocalizedDescription=cancelled, NSErrorFailingURLStringKey=https://api.dropbox.com/2/files/create_folder}

**Comment by MirAshrafUddin** [comment]
@greg-db what is TestData in your code? dont understand.
let request = client.files.upload(path: "/test/path/in/Dropbox/account", input: TestData.fileData)

I want to upload an image to dropbox. how can i do that please help me

**Comment by MirAshrafUddin** [comment]
**OK I was declaring client in my IBAction function now I declare it in my class and the previous error was gone but now i am getting this error** 
<NSProgress: 0x170123e80> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 4382 of 4382  
Success! User is logged into Dropbox.
[request-id c12601b28e9b2a92e46f9f4b0f21d451] Bad Input: Error in call to API function "files/upload": **The given OAuth 2 access token is malformed.**
[request-id cd3a180cfa26ade0e6e98a26ffcf9983] Bad Input: Error in call to API function "files/create_folder": **The given OAuth 2 access token is malformed.**

**Comment by MirAshrafUddin** [comment]
**ok i was declared client in my IBAction function. now its in my class and the previous error is gone. now i am getting a new error what does it mean**
<NSProgress: 0x170131300> : Parent: 0x0 / Fraction completed: 1.0000 / Completed: 4382 of 4382  
Success! User is logged into Dropbox.
[request-id 4cd9e52fc4609309cb35d5a68b90fb13] API route error - {
    ".tag" = path;
    reason =     {
        ".tag" = conflict;
        conflict =         {
            ".tag" = folder;
        };
    };
    "upload_session_id" = "AAAAAAAAAEVzjHyK-HNEHQ";
}

**Comment by MirAshrafUddin** [comment]
Thanks @greg-db now its solved.

**Comment by MirAshrafUddin** [comment]
@greg-db but there is another problem. before log in to dropbox file is uploaded

**Comment by greg-db** [comment]
@MirAshrafUddin I'm glad to hear that issue is solved.

If you're running in to another issue, please open a new issue or forum thread with the details so we can help.
