### ISSUE TITLE
No response on clicking 'New to dropbox?Get the App!' in Login page.

### ISSUE THREAD

**Issue by SaraAbdulWajid** [dropbox/SwiftyDropbox#154]
'New to dropbox? Get the app!' and 'Learn More' links do not redirect to their respective webpages when we login via in-app webView and while opening it in default browser it displays alert with the following message "Cannot Open Page, Safari cannot open the page because the address is invalid"

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

As a workaround, you can set `browserAuth: true` as it seems these work as expected in the actual browser:

```
DropboxClientsManager.authorizeFromController(UIApplication.shared,
                                              controller: self, openURL: { (url: URL) -> Void in
                                                UIApplication.shared.openURL(url)},
                                              browserAuth: true)
```

**Comment by SaraAbdulWajid** [comment]
I tried this approach, but when the user clicks on allow access in dropbox login in page we get a alert to open the app, on click of 'cancel' button on the alert, the links or buttons present in the browser have no response on any number of clicks.

**Comment by greg-db** [comment]
I believe that is expected. That prompt is a protection built in to recent versions of iOS. The user needs to allow the redirect for the authorization flow to complete. If they cancel it, the page will not be in a working state and they'd have to refresh it to make it work again.

**Comment by greg-db** [comment]
Apologies for the delay in closing this. This was resolved by the change to use `SFSafariViewController`.
