### ISSUE TITLE
Change 606 potential calls to fatalError() to something that does not abort.

### ISSUE THREAD

**Issue by neilt** [dropbox/SwiftyDropbox#155]
We are adding Dropbox to our Swift 3 iOS app for the first time using SwiftyDropbox, but we see that the version as of March 10, 2017 has 606 potential calls to fatalError(). Apple does not recommend including fatal error calls in shipping code.

It seems to us very risky that with this many calls to fatalError that an iOS or Dropbox upgrade/update could very easily break our app before we could release with an updated SwiftyDropbox.

Any chance of changing these function calls to something else that will not abort the app?

**Comment by scobbe** [comment]
@neilt: Thanks for reaching out. I totally understand you concern shipping code with `fatalError` calls in it. The way SwiftyDropbox is implemented now, these `fatalError`s would only be triggered in the event something is seriously wrong with Dropbox (e.g. Dropbox server is returning invalid types for a given endpoint), which is highly unlikely, but I understand the concern all the same.

We are planning on releasing a major update to SwiftyDropbox within the next couple days to address a number of outstanding bugs. I can look into exposing these unexpected errors in a more benign manner than `fatalError`.

**Comment by neilt** [comment]
Thank you.

**Comment by jpvasquez** [comment]
I just upgraded my app to apiV2 using SwiftyDropbox and, guess what, "the server returning invalid types" is the number 1 crash I have. 

http://crashes.to/s/83607e67ab9

**Comment by neilt** [comment]
@jpvasquez thanks for reminding me.  We had plans to release a new app this week containing SwiftyDropbox, but now we are going to to have to remove Dropbox support.  We just can't risk having our app crashing because of poor error programming on Dropbox's part.  BTW the latest release has 995 `fatalError()` calls, when searching the included project.

**Comment by greg-db** [comment]
Thanks for the feedback! I'll bring this up with the team again to see if we can improve this in the future.

**Comment by jpvasquez** [comment]
@greg-db Before you can embark on any large scale fix, can you at least talk to whomever is responsible for the Files.ListFolderLongpoll API and understand what it has been sending instead of the bool the API is expecting? Is it not even sending the "changes" bool field in some cases? If you understand the correct semantics in all cases for that API you can at least fix the serializer and avoid the crashes that have been bugging my user base (see link above). 

The API documentation is clearly wrong/incomplete, and thus your serializer, which seems to conform to it, crashes in some undocumented replies.

Thanks.

**Comment by greg-db** [comment]
@jpvasquez We'll be happy to investigate that specifically. Can you [open a new issue](https://github.com/dropbox/SwiftyDropbox/issues/new) with the steps to reproduce that, or if you haven't been able to reproduce it, any other information you may have on it (e.g., from user reports)? That would help us track it down. Thanks in advance!

**Comment by jpvasquez** [comment]
@greg-db Sure, here's the new issue: #188 

Thanks for fixing it.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to eliminate fatal errors from serialization. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by julianlocke** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
