### ISSUE TITLE
Podspec for v4.1.1 is not updated

### ISSUE THREAD

**Issue by akshaynhegde** [dropbox/SwiftyDropbox#159]
[The podspec on cocoa pods](https://github.com/CocoaPods/Specs/blob/master/Specs/7/4/f/SwiftyDropbox/4.1.1/SwiftyDropbox.podspec.json) repo is not updated for v4.1.1. It still has the dependency set to Alamofire v 4.0.1. (The latest is 4.4.0)

Where as the [podspec in this repo](https://github.com/dropbox/SwiftyDropbox/blob/master/SwiftyDropbox.podspec) is updated with the right dependancy version. Running pod update is still picking the cocoapods version of the pod spec. Can you please get it updated?

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by attheodo** [comment]
@greg-db any updates on this one?

**Comment by greg-db** [comment]
No, I don't have an update on this yet. I'll follow up here once I do.

**Comment by akshaynhegde** [comment]
@greg-db Any updates? We are unable to use the latest Alamofire (4.4.0) because the SwiftyDropbox has a dependency for Alamofire 4.0.1.

**Comment by greg-db** [comment]
I don't have an update on this right now unfortunately.

**Comment by greg-db** [comment]
The latest release, [4.1.2](https://github.com/dropbox/SwiftyDropbox/releases/tag/4.1.2), has this [updated in the CocoaPods spec](https://github.com/CocoaPods/Specs/blob/master/Specs/7/4/f/SwiftyDropbox/4.1.2/SwiftyDropbox.podspec.json).
