### ISSUE TITLE
Casting error "Could not cast value of type '__NSCFData' (0x19e733ca0) to 'NSString' (0x19e73e798)."

### ISSUE THREAD

**Issue by CiaoChiang** [dropbox/SwiftyDropbox#16]
It was crash on below code:
if status == noErr {
            let results = dataResult as? [[String : AnyObject]] ?? []
            return results.map { d in d["acct"] as! String }        
 }

**Comment by rpearl** [comment]
Thank you for the report, we'll investigate.

**Comment by rpearl** [comment]
Fixed in fe07dab008642b174d1017de57c0a26c54672030. Thanks for finding it!

**Comment by CiaoChiang** [comment]
Thank you so much
