### ISSUE TITLE
Ability to specify request timeouts

### ISSUE THREAD

**Issue by tomkroening** [dropbox/SwiftyDropbox#161]
I'm building an IOS app that will operate offline if dropbox is not available. SwiftyDropbox does a nice job of letting me know when there is no connection however if api.dropbox.com is not available it takes 60 seconds for the request to timeout (default).

I looked to see what I can do to override this behavior however with the manager:SessionManger being declared a constant I cannot override the SessionManager and reconfigure it.

**There should be a way to specify a default timeout when creating the DropBoxClient.**

**Comment by greg-db** [comment]
Thanks!

**Comment by julianlocke** [comment]
In the latest version of SwiftyDropbox, the initializer of the `DropboxTransportClient` accepts a `NetworkSessionConfiguration` that allows you to configure request timeouts. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
