### ISSUE TITLE
File size is always 0

### ISSUE THREAD

**Issue by jmtaverne** [dropbox/SwiftyDropbox#164]
I try to upload a pdf file but the uploaded pdf file has always a size of 0 bytes. 

This is my code for uploading the pdf.

    let exportFilePathPDF = documentsFileName
    let exportFileURLPDF = URL(fileURLWithPath: exportFilePathPDF)
    FileManager.default.createFile(atPath: exportFilePathPDF, contents: Data(), attributes: nil)
    print(exportFileURLPDF)
    
    if let client = DropboxClientsManager.authorizedClient {
        client.files.upload(path: "/test/\(self.Firma).pdf", mode: .overwrite, autorename: false, clientModified: nil, mute: true, input: exportFileURLPDF)
            .response { response, error in
                if let response = response {
                    print(response)
                } else if let error = error {
                    print(error)
                }
            }
            .progress { progressData in
                print(progressData)
    
        }
    } else{
        print("There is no authorized client.")
    }
 
Can somebody please help me. 

Thank you.

**Comment by greg-db** [comment]
@jmtaverne Looking at this line, it appears you're creating the file immediately before the upload, but aren't putting any data in it:

    FileManager.default.createFile(atPath: exportFilePathPDF, contents: Data(), attributes: nil)

That is, you're only supplying an empty `Data()`, so a zero byte file seems expected for this code. You'll need to save the PDF data there before the upload.
