### ISSUE TITLE
Carthage Update problems

### ISSUE THREAD

**Issue by Luca9307** [dropbox/SwiftyDropbox#167]
Hello, 

I try to update with `carthage update --platform iOS` but I receive this error:
`A shell task (/usr/bin/env git checkout --quiet cc1d85f33abf65bbebea0cbdf4ff780b339d4917) failed with exit code 128:
fatal: reference is not a tree: cc1d85f33abf65bbebea0cbdf4ff780b339d4917`
`Fetched in submodule path 'stone', but it did not contain cc1d85f33abf65bbebea0cbdf4ff780b339d4917. Direct fetching of that commit failed.`

Can you help me with this error?

Thank you.

**Comment by greg-db** [comment]
Thanks for the report! This looks like an issue on our side. We're working on it.

**Comment by greg-db** [comment]
This should be fixed now. Please try again and let us know if you're still seeing any issues.

**Comment by Luca9307** [comment]
Thanks you so much.
