### ISSUE TITLE
Xcode 9 beta: error message

### ISSUE THREAD

**Issue by John1843** [dropbox/SwiftyDropbox#169]
In Xcode 9 beta, I get an error message in the file OAuthMobile.swift on line 233:

` super.init(url: url, entersReaderIfAvailable: false)`

Error message: Must call a designated initializer of the superclass 'SFSafariViewController'

**Comment by octopusbaba** [comment]
Same here, desperately waiting for update in Xcode 9 .

**Comment by sohayb** [comment]
This should be fixed by this PR #168

**Comment by scobbe** [comment]
@sohayb: Thanks for the PR. Just merged. Will push to CocoaPods/Carthage this week.

**Comment by sohayb** [comment]
it wasn't me, it was @werner-freytag who submitted it. Thanks for the merge though 👍

**Comment by strike65** [comment]
Hi there!

After pod update the error message mentioned above is still be shown...

**Comment by greg-db** [comment]
@strike65 It looks like we didn't get a new release out quite yet. cc/ @scobbe

**Comment by akshaynhegde** [comment]
@scobbe @greg-db Any update on when will there be the next version with this fix?

**Comment by msmollin** [comment]
If this is seriously blocking anyone, you can always fork this repo and build against your version of `master`.

If it's just development and you use cocoapods, you can always drink straight from the hose by using:
`  pod 'SwiftyDropbox', :git => 'https://github.com/dropbox/SwiftyDropbox.git'` in your podfile.

PLEASE NOTE that by doing that, you're basically saying you're OK with introducing unstableness into your codebase as I imagine the Dropbox folks do some pretty rigorous testing before certifying code as release-worthy.
