### ISSUE TITLE
Alamofire 3.0

### ISSUE THREAD

**Issue by dwicke01** [dropbox/SwiftyDropbox#17]
Are there plans to migrate?

**Comment by rpearl** [comment]
We'll look into this soon but it's not at the top of the list right now.

**Comment by joeljfischer** [comment]
Fixed in 2.0.2?

**Comment by wkiefer** [comment]
Yep, and also more recently in https://github.com/dropbox/SwiftyDropbox/commit/75aa2a747d9b5f7e22b22fb24ad090ad500973da
