### ISSUE TITLE
Works on iPhone simulator, but not iPad simulator.

### ISSUE THREAD

**Issue by neilt** [dropbox/SwiftyDropbox#171]
Xcode: Version 8.3.3 (8E3004b)
Installed via Carthage, *** Checking out SwiftyDropbox at "4.1.2"
Using iOS 10.3 iPad simulator (14E8301)on iPad Air 2

Using the code recommended in the readme.

On the iPhone the app pulls up the web authorization page.  On the iPad the page is blank as shown in the following.  No errors show in the console.  Tapping the Done button, returns to my app.

![simulator screen shot jun 16 2017 8 01 15 am](https://user-images.githubusercontent.com/1809796/27227810-97a7780c-526a-11e7-9db6-ad3cb93db138.png)

For reference here is the same code on the iPhone.

![simulator screen shot jun 16 2017 8 07 50 am](https://user-images.githubusercontent.com/1809796/27227883-fa4251bc-526a-11e7-867e-78d4c6e94a85.png)

**Comment by neilt** [comment]
Also note that the same problems exist when using a device, works on iPhone, not iPad.

**Comment by neilt** [comment]
Further investigation shows that rotating the device left causes the Dropbox view to disappear and return to my app and its views, then selecting drop box sign in again, works correctly.

It should be noted that the initial sign attempt the split view controller has the primary view overlaid. When it works correctly the primary and secondary views are both shown side by side.

**Comment by greg-db** [comment]
Thanks for the report. I just tried this with the same version of Xcode, SwiftyDropbox, and iOS Simulator, and I didn't see the issue, so it sounds like it may be related to the view setup in your app.  (I was just using a basic single view controller test app.) Would you be able to share a sample app with the view controller setup you mentioned so we can reproduce this? Thanks in advance!

**Comment by neilt** [comment]
My view hierarchy is UISplitViewController with UINavigationController as the primary view controller. The UINavigationController has a UITableViewController (menu) as the root view controller.

Selecting a row in the primary (menu) view controller causes a new (settings) UITableViewController to be pushed onto the primary view navigation controller.  Selecting Dropbox from the settings view controller executes the following:

`DropboxClientsManager.authorizeFromController(UIApplication.shared,
											  controller: viewController,
											  openURL: { (url: URL) -> Void in
												if #available(iOS 10.0, *) {
													UIApplication.shared.open(url, options: [:], completionHandler: nil)
												}   else {
													UIApplication.shared.openURL(url)
												}})
`

The UISplitViewController uses the default preferred display mode, which is automatic.

**Comment by wootanis** [comment]
[B148D693-A54E-4FFE-B4C0-55B896D8145A]Sent from Yandex.Mail for mobile17.06.2560, 18:32, "Neil Tiffin" <notifications@github.com>:My view hierarchy is UISplitViewController with UINavigationController as the primary view controller. The UINavigationController has a UITableViewController (menu) as the root view controller.
Selecting a row in the primary (menu) view controller causes a new (settings) UITableViewController to be pushed onto the primary view navigation controller.  Selecting Dropbox from the settings view controller executes the following:
DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: viewController, openURL: { (url: URL) -> Void in if #available(iOS 10.0, *) { UIApplication.shared.open(url, options: [:], completionHandler: nil) } else { UIApplication.shared.openURL(url) }})
The UISplitViewController uses the default preferred display mode, which is automatic.

**Comment by wootanis** [comment]
[B148D693-A54E-4FFE-B4C0-55B896D8145A]Sent from Yandex.Mail for mobile17.06.2560, 09:07, "Greg K" <notifications@github.com>:Thanks for the report. I just tried this with the same version of Xcode, SwiftyDropbox, and iOS Simulator, and I didn't see the issue, so it sounds like it may be related to the view setup in your app.  (I was just using a basic single view controller test app.) Would you be able to share a sample app with the view controller setup you mentioned so we can reproduce this? Thanks in advance!

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by wootanis** [comment]
[B148D693-A54E-4FFE-B4C0-55B896D8145A]Sent from Yandex.Mail for mobile

**Comment by neilt** [comment]
It appears that setting `splitViewController.preferredDisplayMode = .allVisible` before the call to `DropboxClientsManager.authorizeFromController()` and then setting it back to .primaryHidden when processing `DropboxClientsManager.handleRedirectURL()` works around this problem.

**Comment by greg-db** [comment]
Thanks for sharing that!

**Comment by greg-db** [comment]
We're still looking into this, but it no longer reproduces for us. If anyone is still seeing this issue, would you be able to share a sample project that shows it? Thanks!

**Comment by neilt** [comment]
Unfortunately, with other problems listed in #155 we are no longer using SwiftyDropbox.

**Comment by greg-db** [comment]
To close this out for anyone else seeing this, we've determined that this can happen when the `controller` passed in to `authorizeFromController` isn't the top-most controller. The solution would be to make sure that you're passing the topmost view controller when authorizing. With the `UISplitViewController` case, it's not necessarily `self`. We'll update the documentation to cover this.
