### ISSUE TITLE
How to check if it is folder or not from FileMetadata

### ISSUE THREAD

**Issue by umekun123** [dropbox/SwiftyDropbox#172]
Hi!

After getting a Dropbox file list, I want to check each file is a folder or not.  Is there any way to do that?  It could be possible in obj-c Dropbox SDK I used before.

This is the document for FileMetadata, but I cannot find anything like that.
http://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FileMetadata.html

**Comment by greg-db** [comment]
You can `switch` on the object to check which kind it is, as shown here:

https://github.com/dropbox/SwiftyDropbox#response-handling-edge-cases

**Comment by umekun123** [comment]
Very cool, thanks!
