### ISSUE TITLE
Swift 4.x Support?

### ISSUE THREAD

**Issue by msmollin** [dropbox/SwiftyDropbox#173]
I have an iOS 11 app I'm building with Dropbox support, and Xcode 9's compiler of course won't use any Swift 3.1 frameworks. 

This is basically a hard stop for anyone using Carthage as there's no easy way to override the Swift version setting I can figure out. If you're using Cocoapods, you can do the good ol' hack that anyone who has dealt with Swift version pain before has done:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
```

But really, I'd prefer just proper Swift 3.2 support :) Obviously this has some dependency requirements on AlamoFire, which hasn't announced their plans yet for migration to 4.0 (https://github.com/Alamofire/Alamofire/issues/2139).

**Comment by greg-db** [comment]
Thanks for opening this Matt! I don't have a timeline to offer for this right now. We'll follow up here once we do.

**Comment by cliftonlabrum** [comment]
May as well update this issue to **Swift 4** support now. :)

**Comment by lf-araujo** [comment]
And Swift 4 on Linux!

**Comment by msmollin** [comment]
Updated the title.

**Comment by joshzana** [comment]
Fixed in https://github.com/dropbox/SwiftyDropbox/releases/tag/5.0.0
