### ISSUE TITLE
API to upload and share via emails

### ISSUE THREAD

**Issue by ntthanh** [dropbox/SwiftyDropbox#174]
Hi,

I'd like to know if there is any Dropbox API to upload a file, and then share it immediately with others via emails?

Best,
Thanh

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://www.dropboxforum.com/t5/API-support/How-to-share-a-folder-through-Dropbox-Core-API/m-p/231573#M12626](https://www.dropboxforum.com/t5/API-support/How-to-share-a-folder-through-Dropbox-Core-API/m-p/231573#M12626) ]

Yes, you can upload files using [the `upload` methods](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes6uploadFT4pathSS4modeOCS_5Files9WriteMode10autorenameSb14clientModifiedGSqV10Foundation4Date_4muteSb5inputVS3_4Data_GCS_13UploadRequestCS1_22FileMetadataSerializerCS1_21UploadErrorSerializer_), and then share it with another user using [`addFileMember`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/SharingRoutes.html#/s:FC13SwiftyDropbox13SharingRoutes13addFileMemberFT4fileSS7membersGSaOCS_7Sharing14MemberSelector_13customMessageGSqSS_5quietSb11accessLevelOS1_11AccessLevel19addMessageAsCommentSb_GCS_10RpcRequestGCS_15ArraySerializerCS1_32FileMemberActionResultSerializer_CS1_28AddFileMemberErrorSerializer_).

Or, you can get a link to the file using [`createSharedLinkWithSettings`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/SharingRoutes.html#/s:FC13SwiftyDropbox13SharingRoutes28createSharedLinkWithSettingsFT4pathSS8settingsGSqCCS_7Sharing18SharedLinkSettings__GCS_10RpcRequestCS1_28SharedLinkMetadataSerializerCS1_43CreateSharedLinkWithSettingsErrorSerializer_). You would then have to email that link yourself though.
