### ISSUE TITLE
File upload doesn't accept relative paths

### ISSUE THREAD

**Issue by rav3r** [dropbox/SwiftyDropbox#175]
Hi,

I have folder with id id:8kAhzGLBbGAAAAAAAAAAcw and I try to upload file named firstVoiceTrack.m4a, so my final path is id:8kAhzGLBbGAAAAAAAAAAcw/firstVoiceTrack.m4a.

When I call upload function with that path then following error shows up:

```
precondition failed: "id:8kAhzGLBbGAAAAAAAAAAcw/firstVoiceTrack.m4a must match pattern "\A(?:(/(.|[\r\n])*)|(ns:[0-9]+(/.*)?))\z": file Pods/SwiftyDropbox/Source/SwiftyDropbox/Shared/Generated/StoneValidators.swift, line 9
```

**Comment by greg-db** [comment]
The Dropbox API was recently updated to accept file IDs as parameters for this endpoint, but the SDK hasn't yet been updated to match. This should be supported with the next update of the SDK.
