### ISSUE TITLE
iOS 11 File Provider Services

### ISSUE THREAD

**Issue by RiverbayChris** [dropbox/SwiftyDropbox#177]
How does the new functionality of iOS 11's file provider "services" play into the future of SwiftyDropbox?  If the main Dropbox app integrates this feature from the get go (hopefully in Sept), then does that mean that SwiftyDropbox won't be needed anymore?  I'm finishing up an app for launch in the next 2 months, and I'm trying to decide which route to go (or wait for).

**Comment by greg-db** [comment]
There aren't any changes planned for SwiftyDropbox as a result of the new iOS 11 functionality. The SwiftyDropbox SDK will continue to be supported for accessing the Dropbox API (just like [the rest of the Dropbox API v2 SDKs](https://www.dropbox.com/developers/documentation)).
