### ISSUE TITLE
Dropbox file listing pagination

### ISSUE THREAD

**Issue by nikeshakya** [dropbox/SwiftyDropbox#179]
Is there any possible way to manage dropbox get request in pagination form ?

**Comment by greg-db** [comment]
When listing files and folders, the results are automatically paginated across [`listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes10listFolderFT4pathSS9recursiveSb16includeMediaInfoSb14includeDeletedSb31includeHasExplicitSharedMembersSb_GCS_10RpcRequestCCS_5Files26ListFolderResultSerializerCS2_25ListFolderErrorSerializer_) and [`listFolderContinue`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes18listFolderContinueFT6cursorSS_GCS_10RpcRequestCCS_5Files26ListFolderResultSerializerCS2_33ListFolderContinueErrorSerializer_).

The [`documentation for listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes10listFolderFT4pathSS9recursiveSb16includeMediaInfoSb14includeDeletedSb31includeHasExplicitSharedMembersSb_GCS_10RpcRequestCCS_5Files26ListFolderResultSerializerCS2_25ListFolderErrorSerializer_) has information on how to process these.

**Comment by nikeshakya** [comment]
@greg-db thanks for the reply
but what's the page limit for listFolder ?

**Comment by greg-db** [comment]
By default, it's about 2,000 items. This isn't a strict limit though, and some pages may contain more or less than 2,000.

We recently introduced a new `limit` parameter to let you control this, which should be available in the next version of the SDK.

**Comment by greg-db** [comment]
You can now set an approximate limit on the [`listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC10listFolderAA10RpcRequestCyAA0C0C04ListF16ResultSerializerCAH0if5ErrorK0CGSS4path_Sb9recursiveSb16includeMediaInfoSb0O7DeletedSb0O24HasExplicitSharedMembersSb0O14MountedFolderss6UInt32VSg5limittF) page size using the `limit` parameter on [`listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC10listFolderAA10RpcRequestCyAA0C0C04ListF16ResultSerializerCAH0if5ErrorK0CGSS4path_Sb9recursiveSb16includeMediaInfoSb0O7DeletedSb0O24HasExplicitSharedMembersSb0O14MountedFolderss6UInt32VSg5limittF).

**Comment by nikeshakya** [comment]
thanks @greg-db
