### ISSUE TITLE
Extract image data as BLOB.

### ISSUE THREAD

**Issue by nikeshakya** [dropbox/SwiftyDropbox#180]
I want to download image files as blob...
how can I get blob as response from get request ? 
Is there way to change response type ?

**Comment by greg-db** [comment]
I'm not sure I understand exactly what you're aiming to do. Can you elaborate?

The SwiftyDropbox SDK allows you to download files, e.g., images, to a file URL or as Data, using [`download(path:rev:overwrite:destination:)`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes8downloadFT4pathSS3revGSqSS_9overwriteSb11destinationFTV10Foundation3URLCSo15HTTPURLResponse_S2__GCS_19DownloadRequestFileCCS_5Files22FileMetadataSerializerCS5_23DownloadErrorSerializer_) and [`download(path:rev:)`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes8downloadFT4pathSS3revGSqSS__GCS_21DownloadRequestMemoryCCS_5Files22FileMetadataSerializerCS2_23DownloadErrorSerializer_) respectively.

**Comment by julianlocke** [comment]
In iOS, `Data` is the type for a blob, use the flavor of the download route that returns `Data` in the result.
