### ISSUE TITLE
Does not work with documentPicker

### ISSUE THREAD

**Issue by h36ahmed** [dropbox/SwiftyDropbox#182]
Hi Dropbox Team, I have been trying to import a document from Dropbox app into another app using documentPicker but the following method is not called "optional func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL])". I am not sure if this is Dropbox's issue or Apple's. I checked with other apps like Onedrive, iCloud and Box and it works with them, just not Dropbox. It used to work with iOS 10.3. Could you let me know who to contact or when the fix will be issued? It's urgent! :) I am testing this in iOS 11 beta 10 with iPhone 7.

**Comment by greg-db** [comment]
@h36ahmed This SwiftyDropbox library is for interacting with the Dropbox API servers, not the local document picker, so I'm afraid I can't offer help with your question.

If you open a ticket here we can route it to the right people though:

https://www.dropbox.com/developers/contact

Thanks!
