### ISSUE TITLE
Sign out from Dropbox

### ISSUE THREAD

**Issue by mob-rockstar** [dropbox/SwiftyDropbox#183]
I want to sign out from dropbox programatically.
But I didn't find any solutions for it.
I am using SwiftyDropbox SDK in Swift 3.1

Looking forward to hear soon.

**Comment by bhatti-waqas** [comment]
Any update on i ??

**Comment by greg-db** [comment]
You can use [`DropboxClientsManager.unlinkClients()`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/DropboxClientsManager.html#/s:ZFC13SwiftyDropbox21DropboxClientsManager13unlinkClientsFT_T_) to unlink the authorized clients.

**Comment by mob-rockstar** [comment]
Thanks for your help.

I tried to implement your code.
But it’s still storing my credentials.(screenshot 1)
Is there a way to go to login screen of dropbox? (screenshot 2)

**Comment by greg-db** [comment]
It looks like you wanted to post some screenshots, but nothing came through.

In any case, if you want to clear stored access tokens, you can use [`DropboxOAuthManager.clearStoredAccessToken`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/DropboxOAuthManager.html#/s:FC13SwiftyDropbox19DropboxOAuthManager22clearStoredAccessTokenFCS_18DropboxAccessTokenSb) or [`DropboxOAuthManager.clearStoredAccessTokens`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/DropboxOAuthManager.html#/s:FC13SwiftyDropbox19DropboxOAuthManager23clearStoredAccessTokensFT_Sb).

If you want to restart the app authorization flow, you can use [`DropboxClientsManager.authorizeFromController`](https://github.com/dropbox/SwiftyDropbox/blob/345f460558cd1b1c4faf8c6c5fff80f5809044d1/README.md#begin-the-authorization-flow) as shown here.

**Comment by mob-rockstar** [comment]
Let me know your email address, I will send the screenshots
when I put the code you provided, dropbox is still storing my credentials even though I have unlinked the account.
I want to display dropbox signIn screen.

Regards

**Comment by greg-db** [comment]
You should be able to drop in screenshots in GitHub comments.

In any case, are you referring to being signed in to the Dropbox web site, where you choose to authorize the app or not, as opposed to the API client? That uses a different set of credentials, that is, your Dropbox web site session in Safari. The SDK doesn't offer a way to control that programmatically, but the user can sign themselves out when they want (using the "Sign out" link in the upper right of the page).
