### ISSUE TITLE
Missing argument for voidSerializer

### ISSUE THREAD

**Issue by hms-github** [dropbox/SwiftyDropbox#185]
I'm trying to compile an app using SwiftyDropbox/AlamoFire/CocoaPods for Swift 4 under Xcode 9 GM. I'm getting a Swift compiler error in line 82 of DropboxTransportClient.swift in SwiftyDropbox:

let jsonRequestObj = voidSerializer.serialize()      // Missing argument for parameter #1 in call

Has anyone else seen this or know how to fix it?

I've not seen this before; the app has compiled fine under Swift 3 & Xcode 8

**Comment by greg-db** [comment]
Was this an existing Swift 3 project that you converted to Swift 4? If so, did you have SwiftyDropbox and Alamofire themselves selected for the automatic conversion? If so, please try uninstalling/reinstalling those, and don't have Xcode convert them.

**Comment by greg-db** [comment]
Also, make sure the "Swift Language Version" for both libraries is set to "Swift 3.2".

**Comment by hms-github** [comment]
Greg - it looks like that fixed it; thanks for your help!

best,
Steve

**Comment by greg-db** [comment]
Great, thanks for letting me know!

**Comment by hms-github** [comment]
Greg,

The new instructions worked great on my second app, too. One thing I’ve noticed is that both apps generate the same 12 warnings for SwiftyDropbox. Four start with “Redundant conformance constraint ‘ESerial’: ‘JSONSerializer’”, and there’s four similar warnings each for RSerial and ASerial. All warnings are in DropboxTransportClient.swift. Each is also followed with an explanation of the form of "Conformance constraint ‘ESerial’:’JSONSerializer’ inferred from type here."

Is this something you’re all aware of (and do I have a different setting incorrect that’s causing it)?

best,
Steve

**Comment by greg-db** [comment]
I don't believe you need to configure anything else. The library just needs some maintenance. I'll ask the team to work on that.

**Comment by hms-github** [comment]
Thanks!

**Comment by greg-db** [comment]
The warnings should be gone now with [v4.2.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/4.2.0).

**Comment by hms-github** [comment]
Thanks, Greg - I'll try it.

**Comment by gerchicov-bp** [comment]
@greg-db I have the same issue when I use the following library via cocoapods:
https://github.com/Sahilberi/SwiftyDropDataListing
if you have already fixed this issue then fix your cocoapods too please

**Comment by greg-db** [comment]
@gerchicov-bp This should be fixed as of SwiftyDropbox v4.2.0. The [SwiftyDropDataListing project](https://github.com/Sahilberi/SwiftyDropDataListing) you linked to [requests v4.1.1](https://github.com/Sahilberi/SwiftyDropDataListing/blob/master/Podfile#L6) though. You'll need to ask the maintainer to update that.
