### ISSUE TITLE
Please fix crash on the deserializer for Files.ListFolderLongpoll

### ISSUE THREAD

**Issue by jpvasquez** [dropbox/SwiftyDropbox#188]
Using the `files.listFolderLongpoll` call to get near instant notifications when a file it uses gets changed from another device or computer. It turns out the deserializer for such call is crashing on its own when apparently the server is not sending a boolean it's expecting (or is sending some other type of data) on the `changes` field. 

Please reach out to the API team and understand the (undocumented) edge case which is making `/2/files/list_folder/longpoll` produce a result which crashes the SDK and then fix either the SDK or the HTTP API so that this doesn't  happen anymore.

**Comment by greg-db** [comment]
Thanks for writing this up! [This endpoint](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-longpoll) shouldn't be sending anything off-[spec](https://github.com/dropbox/dropbox-api-spec/blob/52ee61988f0bd92fbd75a41383567e5acaca96f6/files.stone#L340), so we'll have to investigate further.

To help us do so, can you let me know:
- the exact version number of the SwiftyDropbox library you have installed
- the exact code you're using to make the `listFolderLongpoll` call

Thanks in advance!

**Comment by jpvasquez** [comment]
Hi @greg-db 

I'm using version 4.1.1

The code which calls is is the following:

```swift
  private func callLongpoll(context: DropboxMonitorChangesContext, backoff: UInt64? = nil) {
    guard let client = _client
      else {
        ASLog("Called callLongpoll without being linked to Dropbox")
        context.callback(nil, context, SafeProviderError.NotLinkedToAccount)
        return;
    }

    if let backoff = backoff, backoff > 0 {
      ASLog("Backing off for \(backoff) seconds")
      DispatchQueue.main.asyncAfter(deadline: .now() + Double(backoff)) {
        self.callLongpoll(context: context, backoff: nil)
      }
      return
    }

    ASLog("Calling listFolderLongpoll for remotePath = \(context.remotePath)")

    let rpcContext = client.files.listFolderLongpoll(cursor: context.cursor!)
      .response {
        (longpollResult, longpollError) in
        context.cancelFunc = nil
        guard let longpollResult = longpollResult else {
          ASLog("Failed to execute longPoll for path \(context.remotePath): \(String.init(describing: longpollError))")
          if let longpollError = longpollError,
             case .clientError(let err) = longpollError,
             let innerErr = err,
             case URLError.cancelled = innerErr
          {
            ASLog("longPoll cancelled")
            return
          }
          DispatchQueue.main.asyncAfter(deadline: .now() + 15) {
            self.callLongpoll(context: context)
          }
          return
        }
        ASLog("longPoll returned changes: \(longpollResult.changes), backoff: \(String(describing: longpollResult.backoff))")

        if longpollResult.changes {
          self.callContinueAndLongpoll(context: context, backoff: longpollResult.backoff)
          return
        }
        self.callLongpoll(context: context, backoff: longpollResult.backoff)
    }

    context.cancelFunc = {
      rpcContext.cancel()
    } as (() -> Void)
  }


```

**Comment by greg-db** [comment]
Thanks! Can you try updating to the latest version of the SDK (currently 4.2.0)? There were some fixes in 4.1.2. We'll look into the issue anyway in the mean time.

**Comment by jpvasquez** [comment]
I will update on the next version, but please rush into fixing it. I've looked at the diffs, and I can see no related fixes for that API. Please see below the result of migrating to Dropbox APIv2 and the Swift SDK has done to my app's stability.

<img width="607" alt="napkin 09-25-17 23 00 36" src="https://user-images.githubusercontent.com/838134/30844774-5a3651fc-a245-11e7-9607-4dec60f0ccfd.png">

**Comment by greg-db** [comment]
Thanks! I'll follow up here once we have more information on this.

**Comment by jpvasquez** [comment]
@greg-db 

I could finally reproduce the issue by calling the function below and the one I pasted above in quick succession multiple times. The end result can be seen on my next update.

```swift
  private func getLatestCursorAndLongPoll(context: DropboxMonitorChangesContext) {
    guard let client = _client
      else {
        ASLog("Called getLatestCursor without being linked to Dropbox")
        context.callback(nil, context, SafeProviderError.NotLinkedToAccount)
        return;
    }

    var remotePath = context.remotePath
    if remotePath == "/" {
      remotePath = ""
    }

    client.files.listFolderGetLatestCursor(path:remotePath, recursive:true, includeMediaInfo:false, includeDeleted:false, includeHasExplicitSharedMembers:false)
      .response {
        (latestcursorResult, latestcursorError) in
        guard let result = latestcursorResult else {
          ASLog("Failed to get latest cursor for \(context.remotePath): \(String.init(describing: latestcursorError))")
          DispatchQueue.main.asyncAfter(deadline: .now() + 15) {
            self.getLatestCursorAndLongPoll(context: context)
          }
          return
        }
        let cursor = result.cursor
        ASLog("Got a cursor for \(context.remotePath): \(cursor)")
        context.cursor = cursor
        self.callLongpoll(context: context)
    }

  }

```

**Comment by jpvasquez** [comment]
When my app gets a new cursor and call long poll in quick succession, the SDK mixes up requests and responses, and throws an error when deserializing. See debugging output below. As I said before, the deserializer is crashing because it cannot find `changes`.

```
(lldb) po dataResponse.request
▿ Optional<URLRequest>
  ▿ some : https://notify.dropboxapi.com/2/files/list_folder/longpoll
    ▿ url : Optional<URL>
      ▿ some : https://notify.dropboxapi.com/2/files/list_folder/longpoll
    - cachePolicy : 0
    - timeoutInterval : 60.0
    - mainDocumentURL : nil
    - networkServiceType : __ObjC.NSURLRequest.NetworkServiceType
    - allowsCellularAccess : true
    ▿ httpMethod : Optional<String>
      - some : "POST"
    ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
      ▿ some : 2 elements
        ▿ 0 : 2 elements
          - key : "Content-Type"
          - value : "application/json"
        ▿ 1 : 2 elements
          - key : "User-Agent"
          - value : "OfficialDropboxSwiftSDKv2/4.2.0"
    ▿ httpBody : Optional<Data>
      ▿ some : 200 bytes
        - count : 200
        ▿ pointer : 0x00007b800018d000
          - pointerValue : 135789687656448
    - httpBodyStream : nil
    - httpShouldHandleCookies : true
    - httpShouldUsePipelining : false

(lldb) po dataResponse.response
nil

(lldb) po dataResponse.data
▿ Optional<Data>
  ▿ some : 209 bytes
    - count : 209
    ▿ pointer : 0x00007b4400010cc0
      - pointerValue : 135531988061376

(lldb) po String(data: dataResponse.data, encoding: String.Encoding.utf8)
▿ Optional<String>
  - some : "{\"cursor\": \"AAHz4QiuUsX2u9w7o06tj1K3a8p9rL0rKJ3kYXApPfyyAuuyzAXXm52fh-h12G6ZcCiaw8wWAgIcWXI_qZp8TqWXMYdaKd8vn3-PJV5_pdBc0yofEatElwOWPkSOCpKGkqWSZ4uvxQpjokZbBSgvM1W79PquU4zB40tPqsl8dhqQJkS0zZIUUFHqX8vbyo83B38\"}"

  Fix-it applied, fixed expression was: 
    String(data: dataResponse.data!, encoding: String.Encoding.utf8)
(lldb) po String(data: dataResponse.request?.httpBody!, encoding: String.Encoding.utf8)
▿ Optional<String>
  - some : "{\"timeout\":30,\"cursor\":\"AAE82A_kjhXwrBMAjATKOzPNHS1pi_8cigq_aQ5Vg-AYwmsElsj03JwPv-jiAOd2iHxtyRvsZ2_3vr-4xV383zZXCF09lTd1qiaafZrjgQaZqTwcvbkIy_rD-ushE4gkDErH82DHDqqXeod8CBni1PFHljd6HLtb9CfVDqFdf_DRWg\"}"

  Fix-it applied, fixed expression was: 
    String(data: (dataResponse.request?.httpBody!)!, encoding: String.Encoding.utf8)
```

**Comment by jpvasquez** [comment]
BTW, doing the call to long poll manually using NSURLSession fixes the issue. There's something wrong with the way responses are matched to requests currently.

**Comment by greg-db** [comment]
Thanks! That's very helpful.

**Comment by jpvasquez** [comment]
Hi.

Any progress, @greg-db ?

**Comment by greg-db** [comment]
@jpvasquez No, I don't have an update on this yet. I'll follow up here once I do.

**Comment by peymojo** [comment]
I am seeing a possibly related intermittent crash parsing an UploadRequest response while a listFolderLongpoll call is active.

In my case I see the following error in the Xcode debugger, within SerializeUtil.parseJSON:

fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end."

Inspecting the data it's trying to parse, I see:

{"name": (redacted), "path_lower": (redacted), ..., "content_hash": (redacted)}{"changes":true}

Notably, the "changes":true value (which I associate with the listFolderLongpoll) appears to be *appended* as a separate json entity. I believe this is causing the parser to complain about "garbage at end".

Let me know if I can perform additional tests or provide more info. Thanks for looking into this!

**Comment by peymojo** [comment]
Looked at it a bit more.

As a first pass sketch of where the problem might lie:

DropboxTransportClient has a longpollManager SessionManager and a (normal operations) manager SessionManager. These share the same SessionDelegate. However, internally they have distinct URLSessions.

As requests are generated, they're stored in the SessionDelegate using the taskIdentifier as the key in a dictionary. However, per the Apple docs, "This value is unique only within the context of a single session; tasks in other sessions may have the same taskIdentifier value."

Thus if an overlapping normal request and longpoll request happen to have the same taskIdentifier, the response data for one of them can end up in the wrong place. This would seem to be consistent with the error I'm seeing as well as the error @jpvasquez reported.

Apologies if I've made any mistakes in the above analysis but take a look with this in mind, hopefully it will trigger something on your end.

**Comment by greg-db** [comment]
@peymojo Thanks for the detailed analysis and write up! That looks very helpful. I'll make sure the team reviews it while investigating this here.

**Comment by scobbe** [comment]
@peymojo: Great suggestion. I'm surprised that the session delegate wouldn't store the session ID as part of the the lookup key, but I guess that's an indication that a session delegate should only be managing one suggestion.

I made the update [here](https://github.com/dropbox/SwiftyDropbox/releases/tag/4.2.2). Please fetch the latest version of the SDK and see if this resolves your issue.

Thanks for the help! It is much appreciated.

**Comment by peymojo** [comment]
Cheers! I've installed the update and I'm not seeing the crashes. The change looks good, many thanks for the quick turnaround.

**Comment by scobbe** [comment]
Great to hear @peymojo! Thanks for the detailed investigation you conducted. Good luck!
