### ISSUE TITLE
Update Alamofire dependency to the latest release, v4.5

### ISSUE THREAD

**Issue by gereons** [dropbox/SwiftyDropbox#189]
Using these 4 pods:

````   
pod 'SwiftyDropbox'
pod 'Alamofire'
pod 'AlamofireImage'
pod 'AlamofireNetworkActivityIndicator'`
````

I'm getting outdated versions of all 4:
````
Using Alamofire (3.5.1)
Using AlamofireImage (2.5.0)
Using AlamofireNetworkActivityIndicator (1.1.0)
Using SwiftyDropbox (3.3.1)
````

Bumping SwiftyDropbox' dependency on Alamofire to use v4.5 instead of v4.4 resolves this.

````
diff --git a/SwiftyDropbox.podspec b/SwiftyDropbox.podspec
index 2a34536..806ae27 100644
--- a/SwiftyDropbox.podspec
+++ b/SwiftyDropbox.podspec
@@ -19,5 +19,5 @@ Pod::Spec.new do |s|
   s.osx.frameworks = 'AppKit', 'WebKit', 'SystemConfiguration', 'Foundation'
   s.ios.frameworks = 'UIKit', 'WebKit', 'SystemConfiguration', 'Foundation'
 
-  s.dependency       'Alamofire', '~> 4.4.0'
+  s.dependency       'Alamofire', '~> 4.5.0'
 end
````

**Comment by greg-db** [comment]
Thanks for writing this up! I'll ask the team to look into doing this.

**Comment by PierreMardon** [comment]
Needed here too.

**Comment by PierreMardon** [comment]
I copy my previous duplicate issue text here : 

> AlamoFire released its 4.5.0 then 4.5.1 version that fix bugs for XCode 9 and Swift 3.2.
> We are heavily using AlamoFire (like many people) and given the ~> 4.4.0 dependency of SwiftyDropbox, we can't upgrade Alamofire properly in Cocoapods.
>

**Comment by gereons** [comment]
Until this is fixed, feel free to use `pod "SwiftyDropbox", :git => "https://github.com/gereons/SwiftyDropbox"` to use my fork which has just this change.

**Comment by PierreMardon** [comment]
Didn't see, did it also on my side :P Thanks anyway !

**Comment by gereons** [comment]
Updated the PR to also change the dependency when using Cartharge. Any change you'll be able to merge this soon(ish)?

**Comment by greg-db** [comment]
Thanks @gereons ! I'll bring this up with the team.

**Comment by PierreMardon** [comment]
Thanks @gereons for updating your repo, I use it now ;)
@greg-db please tell your team to just update this single line (also the Cartfile as @gereons did on his repo), it will take only a few minutes and will avoid workarounds for people like us who just want to be up to date.

**Comment by greg-db** [comment]
@PierreMardon Thanks! I'll make a note of that with the team.
