### ISSUE TITLE
framework not found Alamofire

### ISSUE THREAD

**Issue by Dirk23** [dropbox/SwiftyDropbox#19]
I setup an empty Project in Xcode and followed the instruction from the Readme file:

* installed cocoapods
* ran pod setup
* created a File called "Pod" in the Folder of the Project
* copy & pasted the text from the Readme into the Pod File
* ran pod install

Thats what my Shell says:
>Updating local specs repositories
>Analyzing dependencies
>Pre-downloading: `SwiftyDropbox` from `git@github.com:dropbox/SwiftyDropbox.git`, tag `0.5`
>Downloading dependencies
>Installing Alamofire (2.0.2)
>Installing SwiftyDropbox (0.5)
>Generating Pods project
>Integrating client project
>
>[!] Please close any current Xcode sessions and use `brauhelfer.xcworkspace` for this project from now >on.
>Sending stats
>Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

After restarting Xcode i open the Project and Build it. I Alway get the same error:

>ld: framework not found Alamofire
>clang: error: linker command failed with exit code 1 (use -v to see invocation)

Am i doing something wrong here?

best regards
Dirk

**Comment by rpearl** [comment]
Make sure to open up the xcode *workspace* instead of just the project. Cocoapods uses workspaces to manage dependencies.

**Comment by Dirk23** [comment]
Great, that did the trick! Thank you
