### ISSUE TITLE
unlinkClients doesnt clear access token to user account

### ISSUE THREAD

**Issue by Raywilliams01** [dropbox/SwiftyDropbox#191]
Hi everyone, 

Im create a way for the user to login out and have another user login on the same instances of the app. 
The problem here is the user A log outs and the DropboxClient unlinkClient is called and  user B logs in but user A information is still showing on the app

```
@IBAction func logOutButton(_ sender: Any) {
      DropboxClient.unlickClient();
}

```

**Comment by greg-db** [comment]
@Raywilliams01 `DropboxClient.unlickClient` isn't a method in the SDK. (I think you might mean `DropboxClientsManager.unlinkClients`?) Can you share the actual pieces of code and steps that are giving you trouble? Thanks in advance!
