### ISSUE TITLE
quitting my app from iOS11.?? does not execute my file upload anymore (iOS10.?? still does)

### ISSUE THREAD

**Issue by michel-ledermann** [dropbox/SwiftyDropbox#193]
My applicationdidenterbackground(_) function does extra work like uploading my file on dropbox
When putting my app in background mode, everything works fine from an iOS 10.?? or iOS 11.?? device
When quitting from an iOS 10.?? device, everything works fine
However, when quitting from an iOS11.?? device, the file is not uploaded on dropbox
What goes wrong ?

**Comment by greg-db** [comment]
I'll be happy to help with any issues you're having with the Dropbox API, but I'll need some more information. Please reply with:

- the version number of the SDK you are using
- the specific steps to reproduce the issue
- the relevant code snippet(s)
- any errors or output

**Comment by ChanchalW** [comment]
[request-id de98172c5dd7512fb1d06b3882d34282] Bad Input: Error in call to API function "files/upload": This app is currently disabled.
Always getting this error while uploading pdf file from ios. 
I am using version 4.1.2 on swift 3 Project.
Xcode 9.0 
Tested on iPhone 6 (ios 11) and iPhone 5s (ios 10)

**Comment by greg-db** [comment]
@ChanchalW Your error seems unrelated to this existing issue, so for future reference, it would be more appropriate to [open a new issue](https://github.com/dropbox/SwiftyDropbox/issues/new).

The error you posted is "This app is currently disabled" though, which indicates that the access token you're using is for a disabled app, so it will no longer work. You'll need to throw away that access token and get a new one for an active app.

If you still need help, [open a new issue](https://github.com/dropbox/SwiftyDropbox/issues/new) with the details.
