### ISSUE TITLE
how to get only audio files in dropbox?

### ISSUE THREAD

**Issue by huongtran84** [dropbox/SwiftyDropbox#194]
can you help me?

**Comment by greg-db** [comment]
The Dropbox API doesn't offer a way to list only files of a specific type, but you can apply whatever filtering you want in your app's client-side code.

That is, you can use [`listFolder`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC10listFolderAA10RpcRequestCyAA0C0C04ListF16ResultSerializerCAH0if5ErrorK0CGSS4path_Sb9recursiveSb16includeMediaInfoSb0O7DeletedSb0O24HasExplicitSharedMembersSb0O14MountedFolderss6UInt32VSg5limittF) and [`listFolderContinue`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC18listFolderContinueAA10RpcRequestCyAA0C0C04ListF16ResultSerializerCAH0jfg5ErrorL0CGSS6cursor_tF) to list files, and then filter the returned entries based on the extension in the [`Metadata.pathLower`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html#/s:13SwiftyDropbox5FilesC8MetadataC9pathLowerSSSgv) in the returned [`ListFolderResult.entries`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/ListFolderResult.html#/s:13SwiftyDropbox5FilesC16ListFolderResultC7entriesSayAC8MetadataCGv).
