### ISSUE TITLE
Can't use Xcode9.0.1 swift4 ?

### ISSUE THREAD

**Issue by ShuheiOno** [dropbox/SwiftyDropbox#195]
Hi, everyone

I use SwiftyDropbox on Xcode8.3 installed by Carthage.
Recently, I update Xcode to 9.0.1  and I build my project, I got the error "Module compiled with Swift 3.1 cannot be imported in Swift 4.0:" on `import SwiftyDropbox` line.

Then I execute 'carthage update SwiftyDropbox --platform iOS',  SwiftyDropbox.xcodeproj build failed.

SwiftyDropbx does not yet support Xcode9?

**Comment by greg-db** [comment]
You should be able to use SwiftyDropbox in Xcode 9. SwiftyDropbox is written for Swift 3, so Xcode 9's Swift 3.2 support should be sufficient. I just tried it and it is working for me using Xcode 9.0.1 and SwiftyDropbox 4.2.1.

Can you share the output you got from `carthage update`?

For reference, there's more information about this error here:

https://stackoverflow.com/questions/44399109/xcode-9-module-compiled-with-swift-3-1-cannot-be-imported-in-swift-4-0

**Comment by ShuheiOno** [comment]
@greg-db 

Thank you.
I could resoleve the problem by above information.
By the way, SwiftyDropbox have plans to support Swift 4?

**Comment by greg-db** [comment]
I'm glad to hear you got this working.

I don't have any plans to share for upgrading SwiftyDropbox to Swift 4 right now, but I'll pass this along as a request.

**Comment by ShuheiOno** [comment]
@greg-db 

Thank you, I understand.

**Comment by greg-db** [comment]
SwiftyDropbox has been updated for Swift 4 as of [v5.0.0](https://www.dropbox.com/developers/documentation/http/documentation#authorization).
