### ISSUE TITLE
background download

### ISSUE THREAD

**Issue by ludovicgrimbert** [dropbox/SwiftyDropbox#198]
is it possible to download files in background ?

**Comment by greg-db** [comment]
Downloads in SwiftyDropbox currently don't work if the app goes to the background, but I'll send this along to the team to see if this can be fixed in a future version.

**Comment by uniqby** [comment]
Almost 2 years have passed... Is there any progress?

**Comment by greg-db** [comment]
@uniqby No, unfortunately I don't have an update on this request.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as support for background sessions. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441
