### ISSUE TITLE
Authentication Screen is not loading if Dropbox App is not installed

### ISSUE THREAD

**Issue by georgbachmann** [dropbox/SwiftyDropbox#199]
In my app users have reported the following bug and I can reproduce it all the time.

- Uninstall the Dropbox App from your device
- Make a call to `DropboxClientsManager.authorizeFromController(...)`

You will then be shown an empty SafariViewController where nothing is loading... no matter how long you wait...
There is also no back or cancel button... the user will be stuck and will have to force-quite and restart the app...

Is this issue known? Everything works perfectly if the App is installed... just not if the app isn't installed

Also... there are no log messages whatsoever to help find the problem...

Cheers,
Georg

**Comment by greg-db** [comment]
We've seen this happen when the controller passed in to `authorizeFromController` isn't the top-most controller. The solution would be to make sure that you're passing the top-most view controller when authorizing. For example, with the `UISplitViewController` case, it's not necessarily `self`. Can you check if that's what's happening in your case?

**Comment by georgbachmann** [comment]
Hey Greg,
thanks for your fast reply.
The ViewController that's presenting is the top one. It itself is presented modaly, but the Safari-VC is pushed into (NavigationController)
It appears but just doesn't load anything...

**Comment by 1aozcan** [comment]
kimlik doğrulamasına gerek yok

**Comment by sourabhardwaj** [comment]
> We've seen this happen when the controller passed in to `authorizeFromController` isn't the top-most controller. The solution would be to make sure that you're passing the top-most view controller when authorizing. For example, with the `UISplitViewController` case, it's not necessarily `self`. Can you check if that's what's happening in your case?

This is very useful information which should actually be documented in the code itself.

**Comment by greg-db** [comment]
@sourabhardwaj Thanks for the feedback! I'll ask the team to do so.

**Comment by julianlocke** [comment]
Out latest version, https://github.com/dropbox/SwiftyDropbox/releases/tag/10.0.1, documents the requirement the the controller authorized from is the top-most.

If you're upgrading from a version below 10.0.0, learn more about our recent major release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
