### ISSUE TITLE
Alamofire? But why?

### ISSUE THREAD

**Issue by atljeremy** [dropbox/SwiftyDropbox#200]
As a best practice, when writing client libraries, you should use the internal core API's that are provided by the platform to not force additional lib requirements on those using your lib. In some cases there's no avoiding it, but in the case of networking, this can and should be avoided. Not everyone is using Alamofire and doesn't want to add the additional dependency/bloat to their app.

Apple has made it easier and easier to write solid/stable networking code using the built in API's like `URLSession`. Is there something you're using in Alamofire that you can't get by using the platform provided networking API's? Hopefully the answer is no being that Alamofire is just a wrapper around `URLSession`. I'd love to see this lib updated to use the platform provided networking API's. Hell, if I had more time, I'd love to help with that effort.

Here are some articles/other libs that highlight this concept:
* https://sendgrid.com/blog/building-a-dependency-free-http-client-in-go/
* https://github.com/bustoutsolutions/siesta#what-it-doesnt-do
* https://thatthinginswift.com/write-your-own-api-clients-swift/

**Comment by greg-db** [comment]
Thanks for writing this up! I'm sending this along to the team.

**Comment by slizeray** [comment]
100% agree with @atljeremy !

**Comment by FabienLydoire** [comment]
@greg-db what's the status on this issue ?
The dependency to Alamofire is segregated to the file `DropboxTransportClient.swift`.
What's the technical reason for using Alamofire over `URLSession` ?

**Comment by greg-db** [comment]
@FabienLydoire This is still open with the team, but unfortunately I don't have any update or additional information to share.

**Comment by ioskunal** [comment]
Hey @FabienLydoire , @greg-db do we have any plans of removing Alamofire from the library?

**Comment by greg-db** [comment]
@greg-db I don't have any news or plans for this request to share. I'll reply here if/when I do.

**Comment by wilwet** [comment]
Please remove Alamofire dependency or keep it current. +1 either case.

**Comment by greg-db** [comment]
@wilwet Thanks for the feedback!

**Comment by alak** [comment]
Ping! Can you remove alamofire please ?

**Comment by greg-db** [comment]
@alak Thanks for checking in. I don't have an update on this unfortunately though. I'll follow up here if/when I do.

**Comment by ChrisPearce** [comment]
Is a change to remove the AlamoFire dependency currently on the roadmap?

**Comment by greg-db** [comment]
@ChrisPearce I don't have any news to share on this.

**Comment by greg-db** [comment]
The request to remove Alamofire entirely is still open, but for reference SwiftyDropbox now supports Alamofire 5 as of [v8.0.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/8.0.0).

**Comment by slizeray** [comment]
Good question! This request is open since almost 5 years...I guess it gives us some string indication? LOL

**Comment by greg-db** [comment]
I don't have any update on this right now.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by FabienLydoire** [comment]
Great release @greg-db !
Congrats to the Team 👍🏻
