### ISSUE TITLE
Update Alamofire dependency to the latest release, v4.7.0

### ISSUE THREAD

**Issue by gereons** [dropbox/SwiftyDropbox#204]
As long as Alamofire is used (and I agree with #200 that it shouldn't be), SwiftyDropbox should use the latest version.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to update this.

**Comment by AnnieNinaJoyceV** [comment]
Encountered the same issue.
What is the suggested solution/alternate method to use until this gets fixed?
TIA!

**Comment by gereons** [comment]
For the time being you can use my fork which has this change. Use 

    pod 'SwiftyDropbox', :git => "https://github.com/gereons/SwiftyDropbox"

in your Podfile

**Comment by AnnieNinaJoyceV** [comment]
Thank you! 👍

**Comment by slizeray** [comment]
@greg-db what is the status of this issue? Thanks.

**Comment by greg-db** [comment]
@slizeray I don't have an update on this. I'll follow up here once I do.

**Comment by slizeray** [comment]
@greg-db It is difficult to understand why such a request takes so much time, 9 months, to fix. Is this framework actively maintained? Many issues are opened since many months.

**Comment by greg-db** [comment]
@slizeray Thanks for the feedback! This SDK is maintained, but the team isn't always able to prioritize every issue. I will send this along to them though.

**Comment by gereons** [comment]
I have to agree with @slizeray. Two releases of the SDK have ignored this trivial but important PR, and that makes both using as well as contributing to Dropbox much less enjoyable than it could be.

**Comment by slizeray** [comment]
@greg-db Are you suggesting that the team was not able to prioritize this issue during 9 months???

**Comment by greg-db** [comment]
Thanks for the additional feedback everyone! This issue is still open with the team, and we'll follow up here once we have an update.

**Comment by greg-db** [comment]
The podspec and Cartfile have been updated for Alamofire 4.7 in the latest release of the SwiftyDropbox SDK.
