### ISSUE TITLE
I cannot find any documentation for using namespaces to access content in shared folders

### ISSUE THREAD

**Issue by sixfngers** [dropbox/SwiftyDropbox#206]
example from the dropbox documentation https://www.dropbox.com/developers/reference/namespace-guide

I can make this call from a terminal with a -TOKEN- and namespace id and get a return, But I cannot figure out how to mimic this call using swiftydropbox.

curl -X POST https://api.dropboxapi.com/2/files/list_folder \
    --header 'Authorization: Bearer -TOKEN-' \
    --header 'Content-Type: application/json' \
    --header 'Dropbox-API-Path-Root: {".tag": "namespace_id", "namespace_id": "#"}' \
    --data '{"path":""}'

**Comment by greg-db** [comment]
The SwiftyDropbox SDK doesn't currently have support for the `Dropbox-API-Path-Root` header, but I'll pass this along as a feature request. 

Depending on what you're trying to do though, you can specify namespace ID in the `path` value in the SDK directly, e.g.:

```
DropboxClientsManager.authorizedClient!.files.listFolder(path: "ns:\(sharedFolderId)").response(...)
```

**Comment by sixfngers** [comment]
Thank you,
I will give that a try. When you say depending on what you're trying to do... are there limitations to this method that do not apply when using the custom header?

**Comment by greg-db** [comment]
Yes, the `Dropbox-API-Path-Root` header also supports other "modes", which can't be specified in `path` itself.

**Comment by sixfngers** [comment]
thanks again.

**Comment by julianlocke** [comment]
In the latest release of SwiftyDropbox you can specify values for the `Dropbox-API-Path-Root` into the `DropboxTransportClient` initializer. Read more about the release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816

**Comment by greg-db** [comment]
You can also set that value using [`DropboxClient withPathRoot`](http://dropbox.github.io/SwiftyDropbox/api-docs/10.0.0/Classes/DropboxClient.html#/s:13SwiftyDropbox0B6ClientC12withPathRootyAcA6CommonC0eF0OF).
