### ISSUE TITLE
reduce library size

### ISSUE THREAD

**Issue by nerd0geek1** [dropbox/SwiftyDropbox#208]
Hi, guys.

Is it possible to reduce framework size less than 100MB?
I import SwiftyDropbox using Carthage, and add SwiftyDropbox.framework under git control to reduce compile time.

But currently the size of SwiftyDropbox.framework is about 180MB, so I have to compress that file to push my commit to GitHub.

Many Thanks
Kohei

**Comment by greg-db** [comment]
I can't make any promises, but I'm sending this request along to the team.

**Comment by nerd0geek1** [comment]
That's enough, thanks.
