### ISSUE TITLE
Network progress reporting incorrect ("totalUnitCount" and "fractionCompleted")

### ISSUE THREAD

**Issue by cannawen** [dropbox/SwiftyDropbox#210]
I am uploading an image to Dropbox using SwiftyDropbox 4.5.0, but it looks like the progress reported is incorrect. `progress.fractionCompleted` is always 0, and `progress.totalUnitCount` is always -1. 

Is this a bug with the Dropbox SDK? Or should I updating my progress bar some other way?

```swift
        DropboxClientsManager.authorizedClient.files.upload(path: path, input: InputStream(fileAtPath: fileUrl)!).response { response, error in
            if let result = response {
                self.uploadToDropboxSuccess(from: fileUrl)
            } else {
                self.uploadToDropboxFail()
                print("Error: \(error!)")
            }
        }.progress { progress in
            print(progress)
            self.progressView?.progress = Float(progress.fractionCompleted)
        }
```
<img width="663" alt="screen shot 2018-04-30 at 2 37 40 pm" src="https://user-images.githubusercontent.com/1088336/39425514-82e34e0e-4c84-11e8-9e00-fd85b2020070.png">

**Comment by greg-db** [comment]
You're [supplying the file data as `InputStream`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC6uploadAA13UploadRequestCyAA0C0C22FileMetadataSerializerCAH0f5ErrorJ0CGSS4path_AH9WriteModeO4modeSb10autorename10Foundation4DateVSg14clientModifiedSb4muteSayAA0H10PropertiesC13PropertyGroupCGSg14propertyGroupsSo11InputStreamC5inputtF), so the total size isn't known, and the fraction/total accordingly can't be reported.

If you want those values, you'll need to switch to [supplying the file data as `Data`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC6uploadAA13UploadRequestCyAA0C0C22FileMetadataSerializerCAH0f5ErrorJ0CGSS4path_AH9WriteModeO4modeSb10autorename10Foundation4DateVSg14clientModifiedSb4muteSayAA0H10PropertiesC13PropertyGroupCGSg14propertyGroupsAS4DataV5inputtF) or [`URL`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC6uploadAA13UploadRequestCyAA0C0C22FileMetadataSerializerCAH0f5ErrorJ0CGSS4path_AH9WriteModeO4modeSb10autorename10Foundation4DateVSg14clientModifiedSb4muteSayAA0H10PropertiesC13PropertyGroupCGSg14propertyGroupsAS3URLV5inputtF).

**Comment by cannawen** [comment]
Using `Data` resolves my issue, thanks @greg-db !
