### ISSUE TITLE
Keychain sharing between main app and extension

### ISSUE THREAD

**Issue by struddie** [dropbox/SwiftyDropbox#216]
I'd like to use the same Dropbox authorisation in my app and its app extension. In the main app, the user authorises the app to use Dropbox (which is stored in the keychain using the `<MainBundleIdentifier>.dropbox.authv2` keychain group). The extension performs some action which requires a change to be made in Dropbox. As the bundle identifier of the app extension is different to the main app (usually `<MainBundleIdentifier>.<ExtensionName>`), the credentials in the keychain are not available and therefore `DropboxClientsManager.authorizedClient` returns nil.

The behaviour in for using the bundle identifier as the keychain group is in the OAuth.swift file:
```
    class func queryWithDict(_ query: [String : AnyObject]) -> CFDictionary {
        let bundleId = Bundle.main.bundleIdentifier ?? ""
...
        queryDict[kSecAttrService as String] = "\(bundleId).dropbox.authv2" as AnyObject?
...
        return queryDict as CFDictionary
    }
```

I have enabled Keychain Sharing under Capabilities/entitlements file with both Id's but of course this the app and the extension are accessing separate keychain groups.

Unless I'm wrong, the code above could simply remove the line which sets the `kSecAttrService` key, as this would use the default group (the first one under Keychain Sharing). Alternatively, an optional property could be set on the `DropboxClientsManager` which is passed to the `Keychain` class methods when reading from and writing to the Keychain. If the value is null, the existing behaviour is used.

**Comment by greg-db** [comment]
Thanks for writing this up! I'm sending this along to the team to see if we can get this supported.

**Comment by Appelg** [comment]
Has this been resolved? Is there a way to share login between a "main" app and it's extension? Ping @greg-db

**Comment by greg-db** [comment]
@Appelg No, unfortunately I don't have an update on this request.

**Comment by Appelg** [comment]
@greg-db ok, thanks for the update.
I (probably) managed to solve this by, after auth in the main app, manually saving this token into my own shared keychain:

`DropboxClientsManager.authorizedClient.files.client.accessToken`

And then in my share extension I init the Dropbox Api by doing this:
```
let dropboxAuthTokenForShareExtension = << Fetch from keychain >>
let t = DropboxAccessToken(accessToken: dropboxAuthTokenForShareExtension, uid: UUID().uuidString)
DropboxOAuthManager.sharedOAuthManager.storeAccessToken(t)
DropboxClientsManager.reauthorizeClient(t.uid)
```

It seems to be working :D

**Comment by julianlocke** [comment]
This is natively supported in the latest version of SwiftyDropbox. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
