### ISSUE TITLE
Memory leaks when using getThumbnail, and several other API calls

### ISSUE THREAD

**Issue by vkozlovskyi** [dropbox/SwiftyDropbox#217]
Easy to reproduce with this example app:
https://github.com/vkozlovskyi/TestDropboxApp

Just need to run it with Xcode Instruments, and request a thumbnail.

Looks like there are some reference cycles when using self in a closure, in RpcRequest, DownloadRequestMemory, and some other classes.

**Comment by greg-db** [comment]
Thanks for the report, and the sample project! We'll look into it.

**Comment by julianlocke** [comment]
Out latest version, https://github.com/dropbox/SwiftyDropbox/releases/tag/10.0.1, should be free of memory leaks.

If you're upgrading from a version below 10.0.0, learn more about our recent major release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
