### ISSUE TITLE
FilesRoutes.upload no timeout when WIFI turned off?

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#218]
Testing the WIFI off scenario for my app; seems the FilesRoutes.upload just stuck there:
no progress and no response.

Should I rely on the upload API's response or use other connectivity checking API when WIFI is off?

Thanks.

**Comment by greg-db** [comment]
To clarify, is the WiFi off before the upload is attempted? You should be getting an error returned in the response block (e.g., as `error` in [the sample here](https://github.com/dropbox/SwiftyDropbox#upload-style-request)). 

If that's not working for you, please let me know:
- the version number of the SwiftyDropbox SDK you're using
- the version number(s) of iOS you're seeing this on
- if you're seeing this on simulator and/or device
- the code you're using

(In any case, you can check network connectivity first if you wish, e.g., using `Reachability`.)

**Comment by allea** [comment]
WIFI is turned off before upload start;

tried the sample code:
when the input: is Data, there's a failure response; when the input: is URL, no response.

Thanks.

**Comment by greg-db** [comment]
Thanks for the additional information! For uploading from `URL` specifically, I believe this is expected. An upload from `URL` will use a background `NSURLSession`, which won't immediately fail when offline. (In fact it should actually still succeed later when the network connection is available again.)

If you need the immediate error feedback, please do use `Data`. I'll send this along as a request for a way to get this error feedback immediately even when using `URL`, but I can't promise if/when that would be implemented.

**Comment by allea** [comment]
yes, it’s better to have an option to detect this and the caller will have a chance either to wait or cancel. 

thanks.

**Comment by julianlocke** [comment]
This won't occur in the latest version of SwiftyDropbox: upload and download routes use a foreground session by default, or a background session if specifically requested. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816. If you need custom behavior on background loads in offline scenarios consider checking Reachability prior to making the request.
