### ISSUE TITLE
No Documentation for Swift API v2

### ISSUE THREAD

**Issue by Dirk23** [dropbox/SwiftyDropbox#22]
There is no documentation on https://www.dropbox.com/developers/documentation/swift#documentation
Where can i find some more Information on how to handle up- and downloads to my Dropboxfolder? Is there a "did finish downloading" method i can use? I'm a bit stuck, because i'm searching something like the DBRestclient from API v1 for Swift.

Thanks

Dirk

**Comment by leah** [comment]
Hi Dirk - We're working on getting some documentation up on the site soon. In the meantime, the tutorial has an example of downloading a file: https://www.dropbox.com/developers/documentation/swift#tutorial

**Comment by Dirk23** [comment]
Hey Leah, 

thank you, but i already used the Tutorial. My Problem is, that the Download finishes after i try to access the file. So i need to have something wich tells me that the download is done.
I also cant find the file in the filesystem of the simulator. My download path is "/filename.extension"

**Comment by leah** [comment]
SwiftyDropbox uses blocks, which is a different pattern than the Dropbox Core API for Obj-C which uses delegates. So there's no need to implement a separate method for when the download completes - you can just put your code in the body of the block (curly braces).

The variable `data` in this line in the tutuorial:
```
print("Downloaded file data: \(data)")
```
should be what you're looking for. At that point you can save the raw data to a file in the filesystem. Unlike the Obj-C library the file isn't saved to the filesystem automatically.

**Comment by rpearl** [comment]
While we're going to continue to use blocks (so your callback will be called only when the download completes) we are going to be changing how downloads are done substantially within the next few days, stay tuned. There will also be more detailed docs on all these intricacies coming soon.

**Comment by Dirk23** [comment]
@rpearl seems you already changed the way how to download a file. The tutorial Code doesn't seem to work since 0.7:

client.filesDownload(path: kDatabaseFileName).response { response, error in ....... }

leads to an Error:
Missing argument for parameter 'destination' in call

What do i have to change here?

**Comment by Thunor** [comment]
Dirk23, 
  I had this same issue.  It appears that the download code is attempting to reference a property on self before self is initialized.  This fix will get it working.  The NSURL and NSHTTPURLResponse are passed back when `destination()` is called.

Here is my fix:
 
Change the init code in Client.swift BabelDownloadRequest to:
```
public class BabelDownloadRequest<RType : JSONSerializer, EType : JSONSerializer> : BabelRequest<RType, EType>  {

    var urlPath : NSURL?
    init(client: BabelClient, host: String, route: String, params: JSON, responseSerializer: RType, errorSerializer: EType, destination: (NSURL, NSHTTPURLResponse) -> NSURL) {
        let url = "\(client.baseHosts[host]!)\(route)"
        var headers = [String : String]()
        urlPath = nil

        if let data = dumpJSON(params) {
            let value = asciiEscape(utf8Decode(data))
            headers["Dropbox-Api-Arg"] = value
        }

        let dest : (NSURL, NSHTTPURLResponse) -> NSURL = { url, resp in
            let ret = destination(url, resp)
            return ret
        }
        
        let request = client.manager.download(.POST, url, headers: headers, destination: dest)

        super.init(request: request, responseSerializer: responseSerializer, errorSerializer: errorSerializer)
    }
```

**Comment by rpearl** [comment]
@Thunor, I don't think that is a problem (it shouldn't be, we don't *use* self) but I might be wrong there, in which case I need to restructure the code. 

@Dirk23 The `destination` parameter is a closure which computes the save destination from the response and temporary location. Really soon (hopefully this week) we're going to be publishing full documentation on the site and taking steps to make sure the tutorial is always up-to-date.

**Comment by rpearl** [comment]
http://dropbox.github.io/SwiftyDropbox/api-docs/latest/
