### ISSUE TITLE
"carthage update --platform iOS" first time project "failed with exit code 72"

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#221]
I'm a real newbie. I'm on Terminal on Mac mini. I followed instructions below from the beginning.

I created my Cartfile like instructed below and typed:

brew update
brew install carthage
carthage update --platform iOS

Result:

*** Cloning SwiftyDropbox
*** Cloning Alamofire
*** Checking out SwiftyDropbox at "4.6.0"
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.29i88J.log
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/shinehah/Documents/Xcode\ Projects/IPv4\ Calculator\ folder/IPv4Calculator/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by greg-db** [comment]
@Shinehah-Gnolaum Based on your other issue #222, it looks like you've already resolved this one, so I'm closing this. Let me know if not though.
