### ISSUE TITLE
carthage update --platform iOS Task failed with exit code 70: /usr/bin/xcrun xcodebuild

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#222]
_I am really new to this._

_Following the instructions below to get started, after typing_ `carthage update --platform iOS` _in Terminal on my Mac mini, I got the following results_:

*** Fetching SwiftyDropbox
*** Fetching Alamofire
*** Checking out SwiftyDropbox at "4.6.0"
*** Checking out Alamofire at "4.7.3"
*** xcodebuild output can be found in /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.06AVAd.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
Build Failed
Task failed with exit code 70:
/usr/bin/xcrun xcodebuild -workspace /Users/shinehah/Documents/Xcode\ Projects/IPv4\ Calculator\ folder/New\ Home\ 02/IPv4Calculator/Carthage/Checkouts/Alamofire/Alamofire.xcworkspace -scheme Alamofire\ iOS -configuration Release -derivedDataPath /Users/shinehah/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4.1_9F2000/Alamofire/4.7.3 -sdk iphonesimulator -destination platform=iOS\ Simulator,id=4DC4901C-B822-43E7-AB12-7A811B7C9083 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/shinehah/Documents/Xcode Projects/IPv4 Calculator folder/New Home 02/IPv4Calculator/Carthage/Checkouts/Alamofire)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/gc/bnd0bmfs5x79n8rnjkc2r06m0000gn/T/carthage-xcodebuild.06AVAd.log

_I tried running_ `carthage update --platform iOS` _several times, changing the factors that might affect it._

_I attached the xcodebuild log below._

[carthage-xcodebuild.06AVAd.log](https://github.com/dropbox/SwiftyDropbox/files/2237703/carthage-xcodebuild.06AVAd.log)

_Any help will be appreciated. I need to know what to do._

**Comment by greg-db** [comment]
@Shinehah-Gnolaum From the log you provided, the actual issue appears to be:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ platform:iOS Simulator, id:4DC4901C-B822-43E7-AB12-7A811B7C9083 }
```

This is apparently an issue that can arise with Carthage. Please review the following Carthage posts for more information and potential fixes:
- https://github.com/Carthage/Carthage/issues/950
- https://github.com/Carthage/Carthage/issues/1385
