### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by kaizenkaizen** [dropbox/SwiftyDropbox#223]
Documentation suggests:

DropboxClientsManager
            .authorizeFromController(UIApplication.shared,
                                     controller: self,
                                     openURL: { (url: URL) -> Void
                in UIApplication.shared.openURL(url)
        })

But this gives xcode warning: 'openURL' was deprecated in iOS 10.0: Please use openURL:options:completionHandler: instead

**Comment by greg-db** [comment]
Thanks! I'll ask the team to get that updated.
