### ISSUE TITLE
Library not loaded ... image not found

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#224]
I am doing a trial project and got as far as https://github.com/dropbox/SwiftyDropbox#begin-the-authorization-flow. When I run the project on an actual device, I get an error that says in the following in the debug window:

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /var/containers/Bundle/Application/768D0CA2-305B-4280-B99B-2BAB2B8A7879/Kokaubeam.app/Kokaubeam
  Reason: image not found

What does this error message mean and how do I fix the error?

**Comment by greg-db** [comment]
Alamofire is an HTTP client library used by SwiftyDropbox to make the HTTPS connections to the Dropbox API. The error you're getting seems to indicate that it was not installed correctly with your app.

Which [SwiftyDropbox installation method](https://github.com/dropbox/SwiftyDropbox#sdk-distribution) did you use? Did it complete successfully?

**Comment by Shinehah-Gnolaum** [comment]
I used Carthage. I made sure It completed successfully.

**Comment by Shinehah-Gnolaum** [comment]
I don't get that error when I use Simulator. In this case it's iPhone 8 Simulator.

**Comment by greg-db** [comment]
I just tried [the Carthage installation method](https://github.com/dropbox/SwiftyDropbox#carthage) and it worked successfully for me. Can you double check that you followed all of the steps exactly as documented? E.g., make sure you didn't miss the 'New Run Script Phase' or 'Input Files' steps. I believe you can get this error if you miss those.

It may be worth uninstalling and reinstalling to be sure.

**Comment by Shinehah-Gnolaum** [comment]
I didn't do that step. I thought I was supposed to skip that step if I do a manual installation. I misunderstood. That must be the problem. I will totally do a a new a different test project. Thank you. I will see if this next project works. and post the results.

**Comment by Shinehah-Gnolaum** [comment]
I am in the process of creating a whole new test project like I said I would do. I got to this step here: https://github.com/dropbox/SwiftyDropbox#manually-add-subproject. Is this an optional step?

**Comment by Shinehah-Gnolaum** [comment]
I have concluded for myself that must be an optional step and that the instructions mean I could either take one route using Carthage or take the manual route using Carthage manually in the instructions that come after the first instructions.

**Comment by Shinehah-Gnolaum** [comment]
I forgot to say that I did the Carthage installation that is not the Carthage manual installation and the error did not occur.
