### ISSUE TITLE
-canOpenURL: failed for URL . . . OSStatus error -10814

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#225]
On execution of the following code statement, I get the following error messages in the debug window. What do those messages mean and how do I fix the errors? I get those messages before I as the user log into Dropbox.

`DropboxClientsManager.authorizeFromController(UIApplication.shared,`
`                                                      controller: self,`
`                                                      openURL: { (url: URL) -> Void in`
`                                                      UIApplication.shared.open(url, options: [:], completionHandler: nil)`
`        })`

2018-08-01 12:11:45.396172-0500 Kokaubeam[8962:19275317] -canOpenURL: failed for URL: "dbapi-2://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2018-08-01 12:11:45.397782-0500 Kokaubeam[8962:19275317] -canOpenURL: failed for URL: "dbapi-8-emm://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

**Comment by greg-db** [comment]
The 10814 errors themselves are expected if the official Dropbox app isn't installed, so they're safe to ignore. The SDK should automatically fall back to processing the app authorization flow in Safari in that case. (More specifically, it should present a `SFSafariViewController` with the OAuth 2 app authorization flow on the Dropbox web site.)

**Comment by Shinehah-Gnolaum** [comment]
When you say the Dropbox app isn't installed, you must NOT mean the SwiftyDropbox Xcode project right?

**Comment by greg-db** [comment]
Correct, by "the official Dropbox app" I do mean [the actual Dropbox app itself](https://itunes.apple.com/us/app/Dropbox/id327630330), not your app. There's [an explanation of the auth flows here](https://github.com/dropbox/SwiftyDropbox#handling-the-authorization-flow).

**Comment by Shinehah-Gnolaum** [comment]
Ok. Thank you very much for all your help.
