### ISSUE TITLE
files.listFolder error code -999 cancelled

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#227]
I have the following code:

`    let client = DropboxClient(accessToken: "<ACCESS_TOKEN>")`

`        client.files.listFolder(path: "").response {`

`            response, error in`

`            if let result = response {`

`                print("Folder contents:")`

`                for entry in result.entries {`

`                    print(entry.name)`

`                }`

`            } else {`

`                print(error!)`

`            }`

`        }`

`    }`

I get the following messages in the debug window:

> !!! client= SwiftyDropbox.DropboxClient

> Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://api.dropbox.com/2/files/list_folder, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://api.dropbox.com/2/files/list_folder}

> 2018-08-02 01:14:51.190174-0500 Gnolaum[38319:28928969] Task <DB6BC310-C929-4503-9903-DA5EBBAA9638>.<1> finished with error - code: -999

What do those messages mean and how do I fix the errors?

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-Support-Feedback/files-listFolder-error-code-999-cancelled/td-p/288487 ]

I'll follow up on your forum thread.
