### ISSUE TITLE
'let' properties are implicitly 'final'; use 'public' instead of 'open'

### ISSUE THREAD

**Issue by slizeray** [dropbox/SwiftyDropbox#228]
With XCode 10, there are 1640 this warning...

**Comment by greg-db** [comment]
Thanks for the report! I'll ask the team to clean that up.

**Comment by TomMajor** [comment]
Would be great if this could be fix soon.
I get like 1651 warnings, the quick view warnings symbol on the right side of the project title bar reads 999+ warnings and this will "mask" warnings in other modules on quick view.
Please make SwiftyDropbox Xcode 10 / Swift 4.2 compatible.
Thanks,

**Comment by greg-db** [comment]
Thanks for the feedback! I'll send this note along to the team about this.

**Comment by wilwet** [comment]
Thnx, Any idea when this is fixed.

**Comment by greg-db** [comment]
No, I'm afraid I can't offer a timeline for this.

**Comment by wilwet** [comment]
No problem,  the code works fine but it gives an uneasy feeling :)

**Comment by marcelmendesfilho** [comment]
Just replaced 'open let' with 'public let' to solve those warnings. If this can be a solution, let me know how to open a PR (I'm kinda new here). My repo is https://github.com/marcelmendesfilho/SwiftyDropbox

**Comment by greg-db** [comment]
@marcelmendesfilho It sounds like that is likely the correct solution, however note that [the SDK is generated](https://github.com/dropbox/SwiftyDropbox#stone), so the fix would likely need to be implemented in the generator itself. We do welcome pull requests: https://github.com/dropbox/SwiftyDropbox/pulls

**Comment by TomMajor** [comment]
I think the use of 'public' instead of 'open' will fix the warnings, but since they are in so many places and Apple released a major update to Xcode and Swift, shouldn't the creator of SwiftyDropbox fix it asap to make the framework ready for Xcode 10 / Swift 4.2 instead of waiting for pull-requests?
Many developers have to switch to newest Xcode fast because of needed support for new iOS, it's always the same every year in September.. :unamused:

**Comment by slizeray** [comment]
Such a trivial fix and can't offer a timeline.... Who can say that this framework is maintained?

**Comment by slizeray** [comment]
With Xcode 10.1...
<img width="383" alt="screenshot 2018-10-31 at 20 50 58" src="https://user-images.githubusercontent.com/5292428/47814724-c2c9e900-dd4e-11e8-9b3d-8220633380b2.png">

**Comment by greg-db** [comment]
Thanks for the reminder! I'll check in with the team on this.

**Comment by ZakiRKaram** [comment]
I can't believe we are dealing with Dropbox. More than a month and still we are waiting for a small update to fix the problem. Come on Dropbox.

**Comment by TomMajor** [comment]
As mentioned earlier in this thread, please make SwiftyDropbox Xcode 10 / Swift 4.2 compatible.
What kind of team is working on this which can't fix this in two months?
I really don't want to be disrespectful, but honestly from a company like Dropbox one really would assume a bit faster and more professional support, I don't understand this either...
If you have problems with the work on this repository or think about giving up support for new versions, it would be helpful to communicate this so that developers can adjust their plans accordingly. Thanks

**Comment by greg-db** [comment]
Thanks for the feedback everyone! I'll pass this along to the team.

**Comment by greg-db** [comment]
@slizeray I'm certainly a real person, but I can't make promises on behalf of the team as to when they'll be able to prioritize any particular task. I wouldn't want to do so and accidentally lie, in case the team's timeline for any particular work changes. Apologies I can't offer more specific guidance!

**Comment by slizeray** [comment]
@greg-db Please escalate this issue and ask the team lead to provide explanations why the community is waiting so long for such a trivial task and to give a specific guidance. Like @TomMajor I don't want to be disrespectful, but we are far away from professional support standards. Thanks!

**Comment by greg-db** [comment]
@slizeray No problem, I'll escalate this further now.

**Comment by flexfrank** [comment]
@greg-db 
You said: 

>the SDK is generated, so the fix would likely need to be implemented in the generator itself. We do welcome pull requests

I created a pull request for that generator: https://github.com/dropbox/stone/pull/119
Nine days have passed...

What's the problem?
All you (or other dropbox guys) have to do is to **PUSH THE MERGE BUTTON**!!

**Comment by greg-db** [comment]
@flexfrank Thanks! It looks like the team did just merge https://github.com/dropbox/stone/pull/119 . There are a few more steps to get the updated/regenerated code released. I'll follow up here once that's done.

**Comment by greg-db** [comment]
This is fixed now in the latest release.

**Comment by slizeray** [comment]
@greg-db Thanks. Is it on purpose that the framework has been ported to Swift 4.0, and not Swift 4?2?

**Comment by slizeray** [comment]
<img width="387" alt="screenshot 2018-11-07 at 23 04 38" src="https://user-images.githubusercontent.com/5292428/48164007-962f4780-e2e1-11e8-9f40-c5512fbae576.png">

**Comment by slizeray** [comment]
@greg-db  There are also 3 remaining warnings (even in Swift 4.0)
<img width="388" alt="screenshot 2018-11-07 at 23 10 25" src="https://user-images.githubusercontent.com/5292428/48164315-67fe3780-e2e2-11e8-9aed-fc327758bb69.png">

**Comment by greg-db** [comment]
@slizeray Yes, the work for Swift 4.2 has not been completed. That's open as #237 .

The characters warning is open as #207 .

I don't believe there's an open issue for the deprecated '!' usage warning, but I'll ask the team to clean that up as well.

**Comment by TomMajor** [comment]
The 1651 warnings are fixed now, that is great news.
The other 2 errors (UIAlertController) and 3 warnings need still a fix, but the errors are easy to patch in a project for the meantime.
Hope they get fixed soon.
Anyway, thanks for showing us that this repository is still alive :)

**Comment by slizeray** [comment]
@greg-db Are you really waiting for people complaining before updating this framework for each new Swift release? This is a shame. Please update to Swift 5.0 and XCode 10.2.1

**Comment by greg-db** [comment]
@slizeray Thanks for the feedback. Can you elaborate on what isn't working for you specifically? I tried this library with Swift 5 and Xcode 10.2 for #249 without issue. If it's not working as expected, please [open an issue](https://github.com/dropbox/SwiftyDropbox/issues/new) with details. Thanks in advance!

**Comment by slizeray** [comment]
I expect SwiftDropbox to compile as Swift 5. This is not the case at the moment, it is compiled as Swift 4.2.

<img width="260" alt="Screenshot 2019-05-03 at 18 48 15" src="https://user-images.githubusercontent.com/5292428/57152587-2a332500-6dd4-11e9-8ccf-d2f37292cd59.png">

I am sorry, this is unacceptable to wait for your users asking to support the latest Swift version. You should do it automatically. It happens again and again. I am not going to open an issue. I expect Dropbox to maintain professionally this framework. This topic has already been discussed at length in this thread.

**Comment by greg-db** [comment]
@slizeray Thanks for clarifying! I'll ask the team to make that update.

And thanks again for the feedback. I'll also bring this up with the team.

**Comment by o-zaporozhchenko** [comment]
just use 
`inhibit_all_warnings!`
to silence warnings. As soon it doesn't block ur usage of a framework, there is no real problem.

**Comment by greg-db** [comment]
SwiftyDropbox has been updated to Swift 5 in the latest release.
