### ISSUE TITLE
What kind of encryption is used by SwiftyDropbox for API calls? 

### ISSUE THREAD

**Issue by kaizenkaizen** [dropbox/SwiftyDropbox#230]
When I call APIs using SwiftyDropbox library such as client?.files.upload, is the data encrypted as it is traveling from the ios device to dropbox servers? If so, what kind of encryption do you use?

**Comment by greg-db** [comment]
Yes, all Dropbox API calls require TLS. You can find more information about Dropbox security in the following help articles:
- https://www.dropbox.com/help/security/safe-to-use
- https://www.dropbox.com/help/sign-in/how-security-works

You can also see the Dropbox API server TLS configurations using SSL Labs:
- https://www.ssllabs.com/ssltest/analyze.html?d=api.dropboxapi.com&latest
- https://www.ssllabs.com/ssltest/analyze.html?d=content.dropboxapi.com&latest
