### ISSUE TITLE
Do we always include "db-" before the app key as in the application's plist file?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [dropbox/SwiftyDropbox#235]
In the application's AppDelegate, where the following code goes, do we include "db-" before the <APP_KEY> that we get from our Dropbox App Console as in the plist file, or do we exclude it?

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    DropboxClientsManager.setupWithAppKey("<APP_KEY>")
    return true
}`

**Comment by greg-db** [comment]
When supplying your app key value to `setupWithAppKey`, you should not include the "db-" prefix. That prefix is only used when registering the URL scheme in the plist.
