### ISSUE TITLE
SwiftyDropbox failed to build for Swift 4.2 : UIAlertControllerStyle has been renamed

### ISSUE THREAD

**Issue by ProgrammerLT** [dropbox/SwiftyDropbox#237]
Hi,

I've just pod-installed SwiftyDropbox 4.6.0 in a Xcode10, Swift 4.2 project and Swift failed to build due to UIAlertControllerStyle being renamed in OAuthMobile.swift.

**Comment by vewert** [comment]
I'm guessing that the latest release (4.8.1) doesn't address this issue? Could we get this cleaned up as well?

**Comment by slizeray** [comment]
Yes I confirm that the last release does not address this issue. The last release is compatible with Swift 4.0, not Swift 4.2

**Comment by greg-db** [comment]
That's correct, this issue is still open. I'll follow up here once I have an update on this.

**Comment by vewert** [comment]
Thanks for your efforts. It sure would be nice to get all of these Swift 4.2 issues cleared up so we can move forward with Swift 4.2.

**Comment by vewert** [comment]
I see that version 4.8.2 has been released; does this version address this and the other Swift 4.2 issues?

**Comment by greg-db** [comment]
No, [v4.8.2 is only a Dropbox API spec update](https://github.com/dropbox/SwiftyDropbox/releases/tag/4.8.2); this issue is still open and we'll follow up here when we have an update on it.

**Comment by slizeray** [comment]
@greg-db I hope we are not going to have a crazy thread with dozen of messages for a trivial update? The community expects to have an update for each iOS/Swift update once a year. There is nothing to argue. You should realize that Dropbox must maintain this SDK according the best practices in this ecosystem. It is not the case. The update for Swift 4.0 was released in September 2017 and you did update this framework for Swift 4.0 only last month after dozen of messages. This is unacceptable. I am sorry to have to say this.
Please update asap this SDK for Swift 4.2. It should have already been done. Thanks ahead.

**Comment by slizeray** [comment]
@greg-db are you serious? Are you suggesting that the "team" does not watch this repository? Please ask the "team" to watch/subscribe to this repository. Thanks

**Comment by tjdhome** [comment]
@greg-db Perhaps a simple [re-] statement of Dropbox iOS support policy would suffice. I'd hope that includes test specifying:
- when would 'release x' expect to be officially supported by Dropbox?
- how long would this particular SDK version be supported

Something like "Dropbox commits to support iOS releases (X.Y) within 4 seconds after an Apple release and commits to maintain support for two centuries after a new iOS version is released."

For Swift, Objective-C etc.

Bonus points awarded for Beta release support too.

Now, I expect you guys or someone to point out "wait! we rely on "Alamofire" and "shinyToyCode" as part of our SDK. Yes, these transitive dependencies makes it hard-- but to be frank, many of us don't care about the things you use internally. We just need a crisp statement from ya'll to set our expectations. And yes, if our code depends on Alamofire, then we'd bear the responsibility of making sure our dependencies and yours all work together (as much fun as that is).

If we had such a thing, then you could point to it and say 'Apple will release Swift 921.2 on Jan 173rd and we'll follow up with our Dropbox version 4 seconds later'. And just possibly, we'd stop haranguing you about it.

**Comment by greg-db** [comment]
@slizeray They are also subscribed, but I make sure to collect and share feedback internally as well.

**Comment by greg-db** [comment]
@tjdhome Thanks! That looks like a very helpful format.

**Comment by joshzana** [comment]
Fixed in https://github.com/dropbox/SwiftyDropbox/releases/tag/5.0.0
