### ISSUE TITLE
sharing features in v2

### ISSUE THREAD

**Issue by tjdhome** [dropbox/SwiftyDropbox#24]
Can you tell me (ok, us) what state the sharing api in the v2 code is? I get 400 errors. Would dearly love to use it for my TVos app.

**Comment by leah** [comment]
What API endpoints are you looking at in particular? Can you share more about the error? Also, could you re-post this discussion in our API forums? I think it might be a more general issue.

https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development
