### ISSUE TITLE
Carthage update missing dir ?

### ISSUE THREAD

**Issue by ejssoft2** [dropbox/SwiftyDropbox#241]
Carthage update gives me the following...

A shell task (/usr/bin/env git checkout --quiet 3c5d0c1229417caf7a2ad3d56ccb1fb2b422075f (launched in /Users/jorge/Escalas/Carthage/Checkouts/SwiftyDropbox/stone)) failed with exit code 128:
fatal: reference is not a tree: 3c5d0c1229417caf7a2ad3d56ccb1fb2b422075f

catrafile is:

github "https://github.com/dropbox/SwiftyDropbox" ~> 4.8.0

Thank you!

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
This should be fixed now. Please try again and let me know if not. Apologies for the trouble!
