### ISSUE TITLE
Swift Compiler Error- use of undeclared type 'ContactsRoutes'

### ISSUE THREAD

**Issue by Connor24601** [dropbox/SwiftyDropbox#243]
My project now fails to build with this error. I've tried updating all the pods, cleaning build folders, and building just the swiftydropbox pod in its own scheme. I get two errors:
Swift Compiler Error-
Use of undeclared type 'ContactsRoutes' in Base.swift line 15
Use of unresolved identifier 'ContactsRoutes' in Base.swift line 33

I'm using SwiftyDropbox (5.0.0) and Alamofire (4.7.3).
If this isn't enough information, just ask what information you want. I did recently update to swift 4, which is required should I want to push my app to the app store.

**Comment by greg-db** [comment]
Thanks for the report! `ContactsRoutes` is new in the latest version, but it [is defined](https://github.com/dropbox/SwiftyDropbox/blob/7285db5e7cf28d9fa2c68cc9d0595019edbad21a/Source/SwiftyDropbox/Shared/Generated/ContactsRoutes.swift#L8).

First, double check that your `pod update` was successful and that you have the new 'ContactsRoutes.swift' file (e.g., in Terminal or in Finder).

I also saw this issue, and was able to resolve it by cleaning, restarting Xcode, and building again. It looks like Xcode can be slow to see the new files, and the restart is necessary. Xcode wasn't listing the 'ContactsRoutes.swift' in the project before the restart.  Can you try that?

**Comment by Connor24601** [comment]
Hi Greg, thanks for replying so quickly. I did a new pod update, and SwiftyDropbox/Source/SwiftyDropbox/Shared/Generated/ Does not have a file ContactsRoutes.swift? So it's not just Xcode.

**Comment by greg-db** [comment]
Thanks! That's unexpected, as that file is [committed](https://github.com/dropbox/SwiftyDropbox/blob/master/Source/SwiftyDropbox/Shared/Generated/ContactsRoutes.swift). Can you share the output you got from `pod update`?

**Comment by Connor24601** [comment]
Update all pods
Updating local specs repositories

Analyzing dependencies
Downloading dependencies
Using Alamofire (4.7.3)
Using AlamofireImage (3.4.1)
Using GTMSessionFetcher (1.2.1)
Using GoogleAPIClientForREST (1.2.1)
Using GoogleSignIn (4.4.0)
Using GoogleToolboxForMac (2.2.0)
Using SwiftyDropbox (5.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 7 total pods installed.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

[!] Automatically assigning platform `ios` with version `9.0` on target `<project>` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by greg-db** [comment]
It does look like CocoaPods is seeing the right version number, but it's not downloading the latest files. I just tried again myself, and I am getting the updated files, including ContactsRoutes.swift.

Can you try removing and reinstalling the SwiftyDropbox pod entirely? It looks like you are stuck on an old version for some reason. (Perhaps CocoaPods is incorrectly caching it on your machine somehow.)

You can also try a `pod repo update` to get CocoaPods to update its master repo.

**Comment by Connor24601** [comment]
Well, I'm not sure what's going on exactly, but I decided to check the cached files to see if that's the problem, and ContactsRoutes is in fact in /Library/Caches/CocoaPods/Pods/Release/SwiftyDropbox/5.0.0-378b4/Source/SwiftyDropbox/Shared/Generated
So I didn't bother to clear my cache, but rather just removed swiftyDropbox from my podfile, ran a pod update, readded it and ran pod update again, and now it works.

Thanks for the help with the weird issue! Hopefully if someone else has this issue, this solution can help them too.
