### ISSUE TITLE
please treat warnings as errors before you qualify a release

### ISSUE THREAD

**Issue by rayfix** [dropbox/SwiftyDropbox#244]
It is a best practice to treat warnings as errors.  Before you go to the hard work to qualify a release, you should make sure it compiles in all modes without warnings.  This happened yet again on 5.0.  There was one (and it is rather silly warning) of unreachable code.

There is unreachable code in appendRemainingFileChunks.  Just looking at the code I see several suspect commented out lines in that file that make me nervous about code quality.

To get rid of the warning I have to fork my own version, which is not ideal.

**Comment by greg-db** [comment]
Thanks for the feedback! I'll bring this up with the team.

**Comment by julianlocke** [comment]
Out latest version, https://github.com/dropbox/SwiftyDropbox/releases/tag/10.0.1, compiles without warnings. Please continue to open issues if you encounter any more.

Also, learn more about our recent major release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
