### ISSUE TITLE
Remove template doesn't remove the associated file properties?

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#247]
In my test, I delete the template first and found the file properties are not auto deleted. 

Now when I try to remove via:
`{{dropbox-api}}/file_properties/properties/remove`

Got an error:
```json
{
    "error_summary": "template_not_found/.",
    "error": {
        ".tag": "template_not_found",
        "template_not_found": "ptid:vQLS8vuTyUoAAAAAAAAa-g"
    }
}
```
How to go from here? Thanks.

**Comment by greg-db** [comment]
Thanks for the report! Can you elaborate on how you're checking for and are seeing the file properties on the file for the deleted file template? E.g., are you using files/get_metadata or files/list_folder, or file_properties/properties/search?

**Comment by allea** [comment]
I’m using the file_properties/properties/search

**Comment by greg-db** [comment]
Thanks for confirming that. It looks like there may be an issue related to updating the search index for deleted templates. We'll look into it.

**Comment by greg-db** [comment]
This should be fixed now. Please try again and let me know if you're still seeing any issues. Thanks!
