### ISSUE TITLE
Fails to Compile in Xcode 10.2 with Swift 5

### ISSUE THREAD

**Issue by cliftonlabrum** [dropbox/SwiftyDropbox#249]
I attempted to build SwiftyDropbox with Carthage in **Xcode 10.2** running **Swift 5** and it fails. I imagine an updated version of SwiftyDropbox with Swift 5 support is coming soon. 🙂

**Comment by greg-db** [comment]
I just tried this out with a project set to Swift 5 in Xcode 10.2, and building and using SwiftyDropbox via Carthage is working fine for me.

Please make sure you're using the latest version of SwiftyDropbox (currently v5.0.0). If you're still seeing this issue with that, can you share the steps you're following to see the failure, and the full error output? Thanks in advance!

**Comment by cliftonlabrum** [comment]
Thanks, Greg. I must have been pulling in an older version of SwiftDropbox by accident. I tried it again making sure I was using `5.0.0` and it worked. Thank you! 😁
