### ISSUE TITLE
Swift Package Manager - Cannot resolve dependency graph

### ISSUE THREAD

**Issue by dsmurfin** [dropbox/SwiftyDropbox#252]
Swift Package Manager in Xcode 11 Beta 2, cannot resolve the dependency graph due to tag issues.

Resolving Package Dependencies >
The package dependency graph cannot be resolved; unable find any available tag for the following requirements:
https://github.com/dropbox/SwiftyDropbox.git = 5.1.0..<6.0.0

It makes no difference if I specify explicit 5.1.0 or a range. I've verified that this works with a number of other repositories, so it does seem to be related to SwiftyDropbox.

**Comment by dsmurfin** [comment]
<img width="646" alt="Screenshot 2019-06-30 at 12 37 44" src="https://user-images.githubusercontent.com/4533485/60396050-7ed4f100-9b34-11e9-9e44-43b0a85d23cc.png">

**Comment by TaylorKrusen** [comment]
I'm having a hard time getting that version of Xcode to run on my system with any sort of stability. Would you mind providing some repro steps while I get that sorted out?

**Comment by dsmurfin** [comment]
Absolutely...

Open Xcode
Select the Project
Select the Swift Packages tab
Click + to add a package
Enter "https://github.com/dropbox/SwiftyDropbox"
Rules: Version Up to Next Major 5.1.0 < 6.0.0 OR Exact 5.1.0 (doesn't seem to make a difference)
Resolving SwiftyDropbox...
Package Resolution Failed

Thanks

**Comment by greg-db** [comment]
Thanks! I can reproduce this in Xcode 11 beta 3. I'll ask the team to look into it.

**Comment by dsmurfin** [comment]
> Thanks! I can reproduce this in Xcode 11 beta 3. I'll ask the team to look into it.

Thank you.

**Comment by fvvliet** [comment]
This error still exists ;-(

**Comment by greg-db** [comment]
@fvvliet Thanks for the note. This issue is still open with engineering. We'll follow up here once we have an update on this.

**Comment by vookimedlo** [comment]
I have the same issue. Looking forward to the fix.
Thanks.

**Comment by cliftonlabrum** [comment]
FYI... this is still an issue in the final release of Xcode 11.0 (11A420a). It'll be great when SwiftyDropbox is available via SPM. 🙂

**Comment by greg-db** [comment]
@cliftonlabrum Thanks for the note!

**Comment by greg-db** [comment]
@danielsaidi Thanks for the information!

**Comment by rubengarciam** [comment]
+1 to for SPM support.
Alamofire supports Swift Package Manager already and if it has been previously added to the Xcode project, adding SwiftyDropbox (even manually) cascades in build time issues.

**Comment by greg-db** [comment]
@rubengarciam Thanks for the note. I'll share this with the team.

**Comment by wugulino** [comment]
@greg-db 

I suggest my students use only the Swift Package Manager and only for things like Dropbox integration. I don't use Cocoapods or any other resource. It would be so nice to see it working on SPM...

<img width="715" alt="Screenshot 2019-12-06 at 12 38 28" src="https://user-images.githubusercontent.com/7506402/70320566-5957bc00-1825-11ea-9ba3-e126987f5b2c.png">

**Comment by greg-db** [comment]
@wugulino Thanks for the feedback!

**Comment by wugulino** [comment]
> @wugulino Thanks for the feedback!

You're welcome, Greg! Looking forward to starting playing with Dropbox through SPM!

**Comment by cliftonlabrum** [comment]
@greg-db Is your Swift dev team even working on SPM support? Or should we not get our hopes up? :)

**Comment by greg-db** [comment]
@cliftonlabrum I can see this is open with engineering, but I don't have any update or timeline to share for it. Apologies I don't more information to offer!

**Comment by danielsaidi** [comment]
Yeah, as one who have built Dropbox-specific extensions to open source projects, it's pretty frustrating to have such a big gap between this repository and the development team. You are always quick to reply @greg-db but it does little for us who try to use DB in our projects, when very little comes out and we have no roadmap or anything to relate to. I think I will just drop support for Dropbox, which is really sad since I've enjoyed both integrating with the framework and using the end result.

**Comment by greg-db** [comment]
@danielsaidi Thanks for the note. I'll share this with the team.

**Comment by gavineadie** [comment]
I've just run into this problem with Xcode 11.3.1 (11C504).  The SPM library is my own and I've been tagging it `1.0.1` upwards.  The actual latest tag in the repo (github) is `1.0.15` but Xcode will only acquire up to tag `1.0.11` and if explicitly told to get tag `1.0.15` it reports:

```
The package dependency graph can not be resolved; 
unable find any available tag for the following requirements:
http://github.com/gavineadie/SatelliteKit.git — 1.0.15
```

That was the story till I tried fooling with the tags.  I had no tags `1.0.12` and `1.0.13` [I don't remember if I made them and deleted them, or I never made them] and when I added them to a couple of untagged commits before `1.0.14` Xcode updated only to the `1.0.13` tag.  I deleted and re-created `1.0.14` and Xcode advanced to that one.  Then I deleted and replaced `1.0.15` and Xcode found it.

I hope this little additional experience helps.

**Comment by greg-db** [comment]
@gavineadie Thanks for sharing that!

**Comment by christianhuck** [comment]
@greg-db Is it possible to share a timeline and/or decision to not support it at the moment now?

**Comment by greg-db** [comment]
@christianhuck This is still open, but unfortunately I don't have any timeline or news right now.

**Comment by crspybits** [comment]
+1 on this.

**Comment by bengottlieb** [comment]
I created a PR that should fix this: https://github.com/dropbox/SwiftyDropbox/pull/281

**Comment by greg-db** [comment]
Thanks @bengottlieb! For reference, there's another PR (#273) up for this too. I'll make sure engineering is aware of both of them.

**Comment by paulfreeman** [comment]
Would be great if this could get some attention. Not being able to use SPM is creating friction in my toolchain now that there are more platforms to work with on iOS Apple post WWDC.

**Comment by greg-db** [comment]
@paulfreeman Thanks for the note. I'll share this with engineering.

**Comment by slizeray** [comment]
@greg-db The maintenance of this framework is below any standard. You keep saying that you will share the information with the team, which is difficult to understand since the team subscribes to this repository. There is very little consideration for the  developers using this framework.

**Comment by greg-db** [comment]
@slizeray Thanks for the feedback. We appreciate you taking the time to communicate this. Not all of the relevant employees necessarily subscribe to the repository, so I also pass these along internally.

**Comment by paulfreeman** [comment]
I'm considering removing Dropbox support from my application due to the lack of support for SPM.  I very much want to simplify dependency management going forward and removing Dropbox is the simplest solution if no progress is made in modernising this SDK.

**Comment by greg-db** [comment]
@paulfreeman Thanks for the additional feedback. I'll highlight this with the team.

**Comment by slizeray** [comment]
@greg-db please "highlight" the super old request for dropping Alamofire which bloats this SDK....

**Comment by greg-db** [comment]
@slizeray Yes, I have brought that one up with them as well. I will do so again.

**Comment by cliftonlabrum** [comment]
SPM support is now available in SwiftyDropbox `6.0.2`! It's a miracle! 😂

In Xcode, go to **File > Swift Packages > Add Package Dependency...** and enter:

```
https://github.com/dropbox/SwiftyDropbox
```
Enjoy!

**Comment by danielsaidi** [comment]
And I who recently gave up and removed the add-on library that added Dropbox Support :/

**Comment by paulfreeman** [comment]
Thanks to the team!

**Comment by greg-db** [comment]
Hi all, yes, as some of you already saw, we've updated SwiftyDropbox to work with Swift Package Manager as of [v6.0.2](https://github.com/dropbox/SwiftyDropbox/releases/tag/6.0.2). Please give it a try and [let us know](https://github.com/dropbox/SwiftyDropbox/issues/new) if you run in to any issues. Thanks!
