### ISSUE TITLE
Request's header encode/decode issue

### ISSUE THREAD

**Issue by Xzot** [dropbox/SwiftyDropbox#253]
Drop box sdk's issue:

To get file from DropBox cloud it is need to set file path. At some point inside SwiftyDropBox sdk the file path damage. That is why some times dropbox return error which say that file don't exist at current file path.

Example: 
File path which comes in drop box ---> "/egge/папка/Njkcnjq ntcn.txt" 
Current file path right before sending request -----> "{\"path\":\"\\/egge\\/\\u043f\\u0430\\u043f\\u043a\\u0430\\/Njkcnjq ntcn.txt\"}"

So the DropBox SDK damage path after file path value where added into request's header fields.

This issue is valid also for latin symbols.

**Comment by greg-db** [comment]
Can you share the code you're running to reproduce this issue? Also, what version number of the SwiftyDropbox library do you have installed? 

I just tried the following with SwiftyDropbox v5.1.0 (after uploading a file at that same path via the Dropbox web site) and both calls worked for me:
```
DropboxClientsManager.authorizedClient!.files.getMetadata(path: "/egge/папка/Njkcnjq ntcn.txt")
    .response(completionHandler: { (response, error) in
        if let response = response {
            print(response)
        } else if let error = error {
            print(error)
        }
    })
    
DropboxClientsManager.authorizedClient!.files.download(path: "/egge/папка/Njkcnjq ntcn.txt")
    .response(completionHandler: { (response, error) in
        if let response = response {
            let responseMetadata = response.0
            print(responseMetadata)
            let fileContents = response.1
            print(fileContents)
        } else if let error = error {
            print(error)
        }
    })
```
They did not return an error, and instead returned the expected file metadata/data.

Thanks in advance!

**Comment by julianlocke** [comment]
@Xzot , I'm closing this issue, please comment here if you still encounter this on the latest version of SwiftyDropbox.
