### ISSUE TITLE
Folder access level

### ISSUE THREAD

**Issue by dchirita** [dropbox/SwiftyDropbox#254]
Is there a way to get access to the files/folders outside of the App Folder?
I understand there are more access levels:
https://help.dropbox.com/installs-integrations/third-party/third-party-apps

In the permissions screen, after login, I only see that "My app name" would like to access its own folder... Is there a way to change the permission level?

**Comment by greg-db** [comment]
The permission level (e.g., app folder or full access) is chosen when first registering your API app. It's not possible to switch the permission on an existing Dropbox API app.

If you want to change the permission used for an app that hasn't been released to users, you can do so by deleting the current API app registration and registering another with the desired permission. Deleting an API app in development mode frees up the name so you can register it again. Once you do, just be sure to update your app accordingly to use the new app key and secret. Access tokens for the deleted app will also no longer work.

If your app has already been released to users, we do not recommend disabling your API app, as it would break the integration for existing users. Instead, we recommend you register another API app for the other permission and add that as an option in your app.

You can register a new API app here:

https://www.dropbox.com/developers/apps/create

**Comment by dchirita** [comment]
Ok. Good to know. Maybe that can be documented somewhere. Thanks a lot! That saved me a lot of time.
