### ISSUE TITLE
Failed to issue sandbox extension for file

### ISSUE THREAD

**Issue by yarodevuci** [dropbox/SwiftyDropbox#256]
Unable to upload selected .MOV files 
getting the error. Issue came with iOS 13. Worked fine before..

**Comment by greg-db** [comment]
We'll be happy to help with any issues you're having with the Dropbox API, but we'll need some more information. Please reply with:

- the version number of the SwiftyDropbox SDK you're using
- the steps to reproduce the issue, including relevant code snippet(s) and a sample file, if this is specific to certain files
- the full text of any error or unexpected output

**Comment by yarodevuci** [comment]
@greg-db the version number of the SwiftyDropbox SDK is 5.1.0
Full error I am getting:

```
Failed to issue sandbox extension for file file:///private/var/mobile/Containers/Data/PluginKitPlugin/CD01FFB6-3925-4ECE-B0F0-E2B1BB3E2668/tmp/trim.174CFBD5-F677-4763-9F79-308AE81C10CF.MOV, errno = 1
2019-09-25 14:11:40.687955-0700 Eclipse[1261:388382] Task <4A69DD24-48FF-4E7E-B246-47FA3F7F0C67>.<1> finished with error [-1] Error Domain=NSURLErrorDomain Code=-1 "unknown error" UserInfo={NSErrorFailingURLStringKey=https://api-content.dropbox.com/2/files/upload, NSErrorFailingURLKey=https://api-content.dropbox.com/2/files/upload, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundUploadTask <4A69DD24-48FF-4E7E-B246-47FA3F7F0C67>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundUploadTask <4A69DD24-48FF-4E7E-B246-47FA3F7F0C67>.<1>, NSLocalizedDescription=unknown error}
```


Code snippet that I been always using:

```
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
        // Local variable inserted by Swift 4.2 migrator.
        let info = convertFromUIImagePickerControllerInfoKeyDictionary(info)
        
        if let videoURL = info["UIImagePickerControllerMediaURL"] as? URL {
           client.files.upload(path: "/\(videoname).mp4", input: videoURL)
            .response { (metadata, error) in
                
                if let response = metadata {
                    print(response)
                }
            }
            .progress { (progressData) in
        }
        }
        dismiss(animated: true, completion: nil)
    }
```

**Comment by greg-db** [comment]
Thanks! It looks like something changed with iOS 13, preventing the use of this file URL for uploads like this. Unfortunately that's outside our control, so I recommend bringing that up with Apple. This looks like it may be an iOS bug preventing the use of the returned URL as the source for a background `URLSession`. (For reference, the Dropbox SwiftyDropbox library passes the `URL` for the file to upload to Alamofire, which passes it to `URLSession.uploadTask`.)

It looks like there's an identical issue, but not for uploading to Dropbox, posted [here](https://stackoverflow.com/questions/56909566/video-upload-error-when-choosing-from-library).

For reference, I tried supplying a `URL` from `documentDirectory` inside `imagePickerController` (but not from the `didFinishPickingMediaWithInfo info`, for comparison), and confirmed that the Dropbox upload could complete with that normal `URL`, so it appears the Dropbox library upload from URL functionality is itself still working on iOS 13.

As a workaround, it looks like uploading from `Data` works, even based on the image picker URL, so you can use that instead:

    client.files.upload(path: "/\(videoname).mp4", input: Data.init(contentsOf: mediaURL))

**Comment by yarodevuci** [comment]
@greg-db Thank you for the idea!
