### ISSUE TITLE
Alamofire conflicts

### ISSUE THREAD

**Issue by sergeymild** [dropbox/SwiftyDropbox#257]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (= 4.9.0)

  In Podfile:
    Alamofire

    SwiftyDropbox was resolved to 2.0.1, which depends on
      Alamofire (~> 2.0.2)

**Comment by greg-db** [comment]
Based on the output here, CocoaPods is attempting to install [SwiftyDropbox v2.0.1](https://github.com/dropbox/SwiftyDropbox/releases/tag/2.0.1), which is several years old. The latest version is [SwiftyDropbox v5.1.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/5.1.0). The error message is indicating that CocoaPods can't find a version of Alamofire that is compatible with both your own requirement and the requirement of SwiftyDropbox v2.0.1. 

What does your `Podfile` look like?  The newer versions of SwiftyDropbox use newer versions of Alamofire, so you should upgrade to get to compatibility. If you're explicitly setting that old version for the SwiftyDropbox pod, you can remove the version requirement, or set it to something newer with a compatible Alamofire dependency.

Note that may be some breaking changes between SwiftyDropbox v2.0.1 and v5.1.0. You can find information in [the release history](https://github.com/dropbox/SwiftyDropbox/releases).

**Comment by sergeymild** [comment]
ok, thanks, i'll check it.

**Comment by julianlocke** [comment]
The latest version of SwiftyDropbox no longer includes Alamofire. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
