### ISSUE TITLE
Support for Alamofire 5.0.0-rc.2

### ISSUE THREAD

**Issue by srinivasprabhug** [dropbox/SwiftyDropbox#258]
I have Alamofire 5.0.0-rc.2 integrated in my project for server communication. When I integrate SwiftyDropbox, Pod dependencies is not resolved. SwiftyDropbox depends on 4.8.2 version of Alamofire. Is there a fix available this?

**Comment by greg-db** [comment]
SwiftyDropbox is currently only tested and released with Alamofire 4.8.2, but I'll pass this along as a request to update it to use Alamofire 5.0.0. I can't promise if or when that might be done though.

**Comment by srinivasprabhug** [comment]
Thanks, Greg. It helps  if you can provide an update.

**Comment by greg-db** [comment]
I'll follow up here with any updates on this.

**Comment by sssbohdan** [comment]
Hi @greg-db. How are things going with increasing version of Alamofire?

**Comment by greg-db** [comment]
@sssbohdan This request is still open with the team, but I don't have any news on it right now.

**Comment by gereons** [comment]
IMHO it would be much better if you could get rid of the Alamofire dependency entirely. See #200

**Comment by sssbohdan** [comment]
Of course, It would be much better to get rid of dependencies, but easier would be to just increase the version because I(and most of you guys I guess) had to lower a lot of dependencies version in my project.

**Comment by juangz** [comment]
Hi @greg-db, 
Due to the recent update in RXSwift (they had an issue with UIWebView that it's now deprecated for new apps), Moya and Alamofire updated their version to the latest version of RX. So now, Alamofire 5.1.0 is the first version that supports RXSwift. And Swiftydropbox now is not compatible at all with it.

Is there any chance you can prioritize this fix in the pipeline? 

Thanks

**Comment by greg-db** [comment]
@juangz Thanks for the information! I can't make any guarantees, but I'll ask the team to prioritize this.

**Comment by slozo** [comment]
I've remade the project to work with latest Alamofire > 5.0 and it could be used with SwiftPM as well. I've tested this in my project and it seems to work, unfortunately I had to add some stuff into `Genrated` files as well (`import Foundation`). Some file structures had to be changed, so that objC files are compiled separately. I didn't check how to handle background sessions in alamofire, so some of the sessions are made as `af.default` in order to not crash. NOTE use it at your own risk. It's not tested for all use cases.

https://github.com/slozo/SwiftyDropbox

**Comment by hakkurishian** [comment]
@greg-db is the team actively working on this one? It seems to be blocking the update of many other alamofire-depending frameworks.

**Comment by greg-db** [comment]
@hakkurishian Thanks for the note. Unfortunately I don't have any news on this from the team yet.

**Comment by brizzly** [comment]
Hi there,  need Alamofire5 support too, let us know?

**Comment by greg-db** [comment]
@brizzly I'll follow up here with any updates on this, but I don't have anything to report right now.

**Comment by brizzly** [comment]
> @brizzly I'll follow up here with any updates on this, but I don't have anything to report right now.

Thanks!
Btw. It's very frustrating , not saying I don't succeed into building the fork project up there..

**Comment by hakkurishian** [comment]
@greg-db  maybe communication to developers could be improved by mentioning where this issue is on the teams backlog and if its on the schedule for the upcoming year or not.

**Comment by greg-db** [comment]
@hakkurishian Thanks! I know the team has generally opted not to share potential future plans as they're always subject to change, and we don't want to accidentally mislead anyone, but I'll pass this note along.

**Comment by brizzly** [comment]
> @hakkurishian Thanks! I know the team has generally opted not to share potential future plans as they're always subject to change, and we don't want to accidentally mislead anyone, but I'll pass this note along.

Actually this Alamofire old version is a blocker for many developers, should be at top priority. We talk about DropBox. 
Any startup around there will update this in a few days and we are waiting for years !!!

**Comment by greg-db** [comment]
@brizzly Thanks for the additional feedback!

**Comment by victorcampeanu** [comment]
god you are lazy and incompetent, I'm dropping you lib, good luck!

**Comment by ChrisPearce** [comment]
Is a change to update the AlamoFire dependency currently on the roadmap?

**Comment by greg-db** [comment]
@ChrisPearce I don't have any news to share on this.

**Comment by hakkurishian** [comment]
The only way we found to upgrade to Alamofire 5 was to remove SwiftyDropbox from our apps and prevent users from using dropbox as a data source. Sad, but the world moves on.

**Comment by brizzly** [comment]
We have to Drop Drop Box :D Seriously this is unbelievable suck amateurism such company.

**Comment by amoshsueh** [comment]
Please resolve this issue ASAP, it really blocks the development for Dropbox support.

**Comment by greg-db** [comment]
Thanks for the notes! I'll emphasize this with the team.

**Comment by greg-db** [comment]
SwiftyDropbox now supports Alamofire 5 as of [v8.0.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/8.0.0).

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by greg-db** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
