### ISSUE TITLE
iOS, 13.1, url-handler not called

### ISSUE THREAD

**Issue by Appelg** [dropbox/SwiftyDropbox#259]
I'm using xcode with iOS 13.1 as target.

I just copied the instructions for auth into my application.
I get redirected to the dropbox app and click "allow", but the following in app delegate is never hit:

```
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
```
I _think_ this may be because of something new and fancy called "Scene Delegate", but I have not had time to read up on that.

I _guess_ we need to handle the url-redirect in the SceneDelegate.swift file instead?

Update: 
Adding the following func to SceneDelegate.swift seems to work:

```
func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        if let url = URLContexts.first?.url {
            print(url)
            
            if let authResult = DropboxClientsManager.handleRedirectURL(url) {
                switch authResult {
                case .success:
                    print("Success! User is logged into Dropbox.")
                case .cancel:
                    print("Authorization flow was manually canceled by user!")
                case .error(_, let description):
                    print("Error: \(description)")
                }
            }
        }
    }
```

**Comment by greg-db** [comment]
Thanks for the report! I'm glad to hear you already got this working.

It looks like the relevant iOS documentation is [here, under "Specifying the Scenes Your App Supports" > "Adopt Scene-Based Life-Cycle Semantics"](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/specifying_the_scenes_your_app_supports#3262270):
>Adding support for scenes changes how your app responds to life-cycle events. In an app without scenes, the app delegate object handles transitions to the foreground or background. When you add scene support to your app, UIKit shifts that responsibility to your scene delegate objects. Scene life cycles are independent of one another, and independent of the app itself, so your scene delegate objects must handle the transitions.
>
>If your app also supports iOS 12, you can handle life-cycle transitions in both your app delegate and scene delegate objects. UIKit notifies only one delegate object. In iOS 13 and later, UIKit notifies your scene delegate objects. In iOS 12 and earlier, UIKit notifies your app delegate.

I'll ask the team to update [the SwiftyDropbox documentation](https://github.com/dropbox/SwiftyDropbox#handle-redirect-back-into-sdk) with information on how to set up the authorization flow in an app that supports scenes like this.

**Comment by inPhilly** [comment]
Doesn't look like the documentation has been updated yet. Am I wrong? This is pretty important.

**Comment by greg-db** [comment]
@inPhilly That's correct, this issue is still open with the team; the documentation hasn't been updated yet.

**Comment by jem5519** [comment]
Ran into the this same issue building a test app to work with SwiftyDropbox. It would be worth updating the docs for iOS.

**Comment by greg-db** [comment]
@jem5519 Thanks for the note. I'll remind the team this still needs to be updated.

**Comment by greg-db** [comment]
The documentation has been updated for this. Thanks all!
