### ISSUE TITLE
Conditionally including SwiftyDropbox

### ISSUE THREAD

**Issue by dmitrym0** [dropbox/SwiftyDropbox#264]
I'm writing some code that works with and without SwiftyDropbox. In the olden days, I'd do a conditional include like so:

```
#if SwiftyDropbox
...
#end
```

I'm not seeing any `#define`s in SwiftyDropbox. I'm a newcomer to Swift, what am I missing?

**Comment by greg-db** [comment]
It sounds like this is more of a question about using packages in Swift in general and not applicable only to SwiftyDropbox in particular. I can't really offer support for Swift itself so I can't be too helpful. 

That said, it looks like this question and answer covers this: https://stackoverflow.com/questions/42252776/how-to-check-at-compile-time-if-a-swift-module-exists-on-the-current-project

**Comment by dmitrym0** [comment]
Thanks @greg-db I did not find this in my search!
