### ISSUE TITLE
Сancel handler is not called after auth process is canceled

### ISSUE THREAD

**Issue by CFIFok** [dropbox/SwiftyDropbox#265]
In process of loading the OAuth screen (by `presentAuthChannel()` method) the user can press the cross-like button (X) at the right top of the SFSafariViewController, not expecting to finish the loading process by user. The `cancelHandler()` closure will not be called. But the ViewController will be immediately dismissed. Anyway, but the calling of `cancelHandler()` is expected by me, as a developer.

```
    public func safariViewController(_ controller: SFSafariViewController, didCompleteInitialLoad didLoadSuccessfully: Bool) {
        if (!didLoadSuccessfully) {
            controller.dismiss(animated: true, completion: nil)
        }
    }
```

![IMG_88FA5EA75824-1](https://user-images.githubusercontent.com/52627825/76771347-46ec0780-67b0-11ea-887e-d4d528952a6d.jpeg)

**Comment by greg-db** [comment]
Thanks for the report! It looks like we're not returning an error in that case. (We'd probably want to make that into a `.cancel` case for [the `handleRedirectURL` result](https://github.com/dropbox/SwiftyDropbox#handle-redirect-back-into-sdk).) I'll ask the team to do so.

**Comment by CFIFok** [comment]
Thank you so much for your reply, I'll follow the changes.

**Comment by julianlocke** [comment]
The cancellation behavior requested above is now released in a stable version, https://github.com/dropbox/SwiftyDropbox/releases/tag/10.0.1.

 Read more about our recent major release here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
