### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by timbueno** [dropbox/SwiftyDropbox#27]
My package manager of choice is Carthage at the moment. Is it possible to add support for Carthage?

**Comment by nerd0geek1** [comment]
+1

**Comment by webdevotion** [comment]
I use SwiftyDropbox with Carthage today.  

Just add this line to your Cartfile.
Carthage will checkout the repo in it's Carthage/checkouts/SwiftyDropbox folder
from which you can drag and drop the checkout files.

Minor issues occur, but nothing drastic.  Try it.  It's not too bad.
Better support would be nice.

```
github "dropbox/SwiftyDropbox" >= 0.7
```

**Comment by atomkirk** [comment]
Yeah, really needs to be module namespaced. I also have a JSON symbol in my own project, so this is a no-go.

**Comment by Laban1** [comment]
+1

**Comment by blue-toe** [comment]
+1

**Comment by greg-db** [comment]
Thanks for the feedback all! I can't make any promises right now, but we'll consider this a feature request.

**Comment by scobbe** [comment]
Added in ab71ab5
