### ISSUE TITLE
Package resolution Failed with Swift Package manager (incompatible tools version)

### ISSUE THREAD

**Issue by wilwet** [dropbox/SwiftyDropbox#272]
I get an error when trying to use the xcode 11 swift package manager. Is there a fix for this?
Using xcode Version 11.4.1 (11E503a).

<img width="712" alt="Schermafbeelding 2020-05-11 om 17 26 09" src="https://user-images.githubusercontent.com/25547191/81580172-61f08780-93ad-11ea-963d-bba8c7dbb9d5.png">

Error:  because SwiftyDropbox >=4.0.4 contains incompatible tools version and root depends on SwiftyDropbox 5.1.0..<6.0.0, version solving failed.

**Comment by greg-db** [comment]
Thanks for the report. SwiftyDropbox doesn't currently work with Swift Package Manager unfortunately. Please follow #252 where we're tracking the incompatibility with Swift Package Manager. I'm closing this issue in favor of that one.

**Comment by wilwet** [comment]
Thank you for the answer, I hope it will be fixed in the near future.
