### ISSUE TITLE
Conflict with Alamofire

### ISSUE THREAD

**Issue by shalutyagihike** [dropbox/SwiftyDropbox#274]
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    Alamofire (~> 5.0)

    SwiftyDropbox (~> 5.1.0) was resolved to 5.1.0, which depends on
      Alamofire (~> 4.8.2)

**Comment by greg-db** [comment]
Thanks for the report. It looks like your project uses a newer version of Alamofire than the SwiftyDropbox SDK supports.

Please find the discussion for this issue here: https://github.com/dropbox/SwiftyDropbox/issues/258

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by greg-db** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
