### ISSUE TITLE
Swift Version 5.0 ?

### ISSUE THREAD

**Issue by StefaniOSApps** [dropbox/SwiftyDropbox#275]
Could you Update to Swift 5.0?

See https://github.com/dropbox/SwiftyDropbox/blob/master/Source/SwiftyDropbox/SwiftyDropbox.xcodeproj/project.pbxproj and search for `SWIFT_VERSION = 4.2`

**Comment by StefaniOSApps** [comment]
#276

**Comment by greg-db** [comment]
Thanks! I'll ask the team to look into this.

**Comment by slizeray** [comment]
@greg-db Did the "team look into this"?

**Comment by greg-db** [comment]
@slizeray This is still open with the team, but I don't have an update yet.

**Comment by greg-db** [comment]
SwiftyDropbox has been updated to Swift 5 in the latest release.
