### ISSUE TITLE
“Precondition failed: ” must match pattern” - Cannot download or fetch from dropbox , if pass the Empty string in Path

### ISSUE THREAD

**Issue by saifudheenMustafa** [dropbox/SwiftyDropbox#277]
am getting an error while am trying to download/ fetching  the all content from dropbox , I use the download source -code from documents which is download to data  and passing the path "" to get  the root folder details . its shows error - "Precondition failed: ” must match pattern".Cannot access the root folder while passing the path as: "" as empty string

**Comment by greg-db** [comment]
It sounds like you're trying to download files/folders using the [`download`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC8download4path3revAA21DownloadRequestMemoryCyAA0C0C22FileMetadataSerializerCAJ0h5ErrorM0CGSS_SSSgtF) or [`downloadZip`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC11downloadZip4pathAA21DownloadRequestMemoryCyAA0C0C0hF16ResultSerializerCAI0hf5ErrorL0CGSS_tF) method, is that correct?

These methods unfortunately do not support downloading the entire root at once. 

To download any specific file, you should use the  [`download`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC8download4path3revAA21DownloadRequestMemoryCyAA0C0C22FileMetadataSerializerCAJ0h5ErrorM0CGSS_SSSgtF) method and specify the path of the specific file you want to download, like "/folder/file.ext". You can get that path value from [`Metadata.path_lower`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/Metadata.html#/s:13SwiftyDropbox5FilesC8MetadataC9pathLowerSSSgvp) when retrieving the file metadata elsewhere on the API, for instance.

To download a whole folder, you should use the [`downloadZip`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC11downloadZip4pathAA21DownloadRequestMemoryCyAA0C0C0hF16ResultSerializerCAI0hf5ErrorL0CGSS_tF) method. That can only be used to download specific folders, likewise by passing in a path like "/folder", but not the root folder "'.
