### ISSUE TITLE
SwiftyDropBox and MSGraph APIs in the same app ?

### ISSUE THREAD

**Issue by RegisStGelais** [dropbox/SwiftyDropbox#285]
I implemented OneDrive access in my app using the MSAL authentification library found at https://github.com/AzureAD/microsoft-authentication-library-for-objc

MSAL requires me to add this app delegate:
`  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool
    {
        
        guard let sourceApplication = options[UIApplication.OpenURLOptionsKey.sourceApplication] as? String
            else
        {
            return false
        }
        
        return MSALPublicClientApplication.handleMSALResponse(url, sourceApplication: sourceApplication)
    }`

and SwiftyDropbox requires to add:
`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
let oauthCompletion: DropboxOAuthCompletion = {
if let authResult = $0 {
switch authResult {
case .success:
print("Success! User is logged into DropboxClientsManager.")
case .cancel:
print("Authorization flow was manually canceled by user!")
case .error(_, let description):
print("Error: \(String(describing: description))")
}
}
}
DropboxClientsManager.handleRedirectURL(url, completion: oauthCompletion)
return true
}`

How can I merge these ?

Regards,

**Comment by RegisStGelais** [comment]
According to this stackoverflow post I just need to pass the same result to both api managers
[https://stackoverflow.com/questions/47271628/how-to-handling-login-redirects-back-to-app-from-multiple-social-login-accounts](url)

**Comment by greg-db** [comment]
Yes, that's the right idea. Essentially you pass the URL along to each one so they each can check it. The `DropboxClientsManager.handleRedirectURL` method, for instance, will just ignore it if it's not of the format it expects and can handle.
