### ISSUE TITLE
iOS14: Allowing access window is corrupted

### ISSUE THREAD

**Issue by AlexG-MK** [dropbox/SwiftyDropbox#288]
1. Have Dropbox app installed on iPad
2. Observe allowing Dropbox access window appearance
![IMG_0008](https://user-images.githubusercontent.com/59370172/93597477-ca86eb00-f9c3-11ea-99e7-ade2eae0e13f.PNG)

**Comment by greg-db** [comment]
Thanks! I'll ask the team to fix this up.

**Comment by greg-db** [comment]
This is fixed in the latest version of the official Dropbox iOS app, v232.2. Thanks again.
