### ISSUE TITLE
Include Xcode Project

### ISSUE THREAD

**Issue by atomkirk** [dropbox/SwiftyDropbox#29]
If you could be so kind as to include the (or an) Xcode project that will let me include this in my project without CocoaPods, that would be great.

**Comment by xeokeri** [comment]
@atomkirk The easiest way is to add git submodules for both SwiftyDropbox and AlomaFire to your project.

Drop in the AlomaFire project to your app's workspace and add in the Alomafire.framework to your project's frameworks.

Then, add in the SwiftyDropbox/Source .swift files to your project, including the .h/.m files, except the SwiftyDropbox.h file.

After that, add this line to your bridging header file.
```
#import "SecurityUtil.h"
```
The "DropboxUtils.swift" file, you will need to add the following line or else it won't compile correctly. As the file uses UIKit content but doesn't include the correct import.

```
import UIKit
```

Then you should be able to do the rest as normal.

**Comment by atomkirk** [comment]
I also have a type `JSON` so i need it in its own module

**Comment by xeokeri** [comment]
@atomkirk You could create a new Xcode project, create a Cocoa Touch framework, and add the Dropbox code. Including the submodule for AlomaFire and that would allow you to separate it further.

**Comment by atomkirk** [comment]
That's what I ended up doing https://github.com/spoken-co/SwiftyDropbox , but the point of this issue is that it wouldn't hurt anything or anyone to include it, but it would save a lot of headache for people who don't see the need for cocoapods anymore with touch frameworks

**Comment by jpittman** [comment]
I have to second what @atomkirk is pointing out here.  While this issue helps me resolve getting the SDK integrated, it seems a bit short sighted to only support one approach of integration.  Between pull requests #44, #68 and @atomkirk's linked repo, seems like you have a good starting point to throw into a branch for those of us to test externally.

Please make this a priority.

**Comment by scobbe** [comment]
Added in ab71ab5
