### ISSUE TITLE
init(url:entersReaderIfAvailable:)' was deprecated in iOS 11.0

### ISSUE THREAD

**Issue by wilwet** [dropbox/SwiftyDropbox#290]
DropboxClientsManager -> MobileSafariViewController line 432 has een deprecated init. 

init(url:entersReaderIfAvailable:)' was deprecated in iOS 11.0

**Comment by greg-db** [comment]
Thanks! I'll ask the team to fix that up.

**Comment by drewbratcher** [comment]
+1 on this request, the warning still appears to be there

**Comment by greg-db** [comment]
Thanks for the note. This is still open with engineering. I'll follow up here once I have an update on it.

**Comment by greg-db** [comment]
This should be fixed as of SwiftyDropbox v8.1.0.
