### ISSUE TITLE
Building Alamofire 4.8.2 on Xcode 12 generates toolchain warnings

### ISSUE THREAD

**Issue by davemfecholabs** [dropbox/SwiftyDropbox#291]
Hi,

When I build using Xcode 12 the following warnings are generated (see below).

Here's what I found:
1. SwiftyDropbox depends on the pod Alamofire 4.8.2
2. Alamofire 4.8.2's iOS deployment target is 8.0
3. The Xcode 12 toolchain now requires iOS 9.0

### Warnings:
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingRuntime.cpp.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingFile.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingBuffer.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingWriter.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingPlatformDarwin.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingMerge.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingNameVar.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfiling.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingUtil.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingValue.c.o)) was built for newer iOS version (9.0) than being linked (8.0)
ld: warning: object file (/Users/me/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/lib/darwin/libclang_rt.profile_ios.a(InstrProfilingMergeFile.c.o)) was built for newer iOS version (9.0) than being linked (8.0)

**Comment by greg-db** [comment]
Thanks! It looks like Alamofire bumped their target in their v5.0.0, so I'll send this along as a request to update SwiftyDropbox's dependency.

**Comment by EliteTechnicalCare** [comment]
Even better Dropbox should get rid of Alamofire entirely and just use the built in URLSession

**Comment by greg-db** [comment]
@EliteTechnicalCare Thanks for the feedback!

**Comment by greg-db** [comment]
SwiftyDropbox now supports Alamofire 5 as of [v8.0.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/8.0.0).

(There's also still [an open request to remove the Alamofire dependency here](https://github.com/dropbox/SwiftyDropbox/issues/200).)

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by greg-db** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
