### ISSUE TITLE
Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by ashikask** [dropbox/SwiftyDropbox#293]
On running the project on Xcode 12 version facing this error **`Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3 compiler`**, our project has swift version of 4
can some one please help with solution for same
we have integrated swiftydropbox using Carthage 
<img width="677" alt="Screenshot 2020-10-15 at 9 54 07 PM" src="https://user-images.githubusercontent.com/13530237/96161052-6f013c00-0f34-11eb-82f0-a3b4f1d0241f.png">

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
It looks like this can occur when switching Swift compiler versions (e.g., when going from Xcode 11 to Xcode 12). We'll look into supporting Module Stability in the future to avoid this, but in the meantime you should be able to resolve this by rebuilding, e.g., using `carthage update --platform iOS`. (Note that you may run in to a different issue with Carthage itself when using Xcode 12 though. Please refer to [this issue](https://github.com/Carthage/Carthage/issues/3019) for information on that.)

**Comment by julianlocke** [comment]
We don't have plans to support Module Stability, but as Greg says above, rebuilding will fix this.
