### ISSUE TITLE
DropboxClientsManager.authorizeFromController is not releasing a respective view controller

### ISSUE THREAD

**Issue by Mattijah** [dropbox/SwiftyDropbox#294]
`DropboxClientsManager.authorizeFromController` and `MobileSharedApplication.sharedMobileApplication` respectively, keep a _strong_ reference to the view controller that was passed in the `authorizeFromController`. The view controller will not be released and deallocated even upon successful authentication. Keeping a reference to VC, VM and others - despite the fact that this particular controller was already dismissed might cause an unexpected problems as I've just witnessed. 

For now as a workaround, I've decided to simply reset the `sharedMobileApplication` (`MobileSharedApplication.sharedMobileApplication = nil`) when the authentication is finished. It would be however nice if this was handled directly in the library or maybe it was at least mentioned in the documentation.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to take care of this.

**Comment by YufeiG** [comment]
The controller should be weak, and it should be strongly held in the view hierarchy. I will send a pull request for this and this will probably require a major update since it may affect people who depend on the strong reference and haven't added the controller to the view until later.

**Comment by greg-db** [comment]
This should be fixed in the latest version, v7.0.1.
