### ISSUE TITLE
The file information acquired by FilesRoutes.listFolder() is less than the actual number of files.

### ISSUE THREAD

**Issue by Yamauchi-ALPS** [dropbox/SwiftyDropbox#296]
When I get the list of files under the folder specified in the following process, even if there are actually 15 files, only 13 files may be obtained.
It may be retrieved correctly depending on the folder.

```
guard let client = DropboxClientsManager.authorizedClient else { return }
client.files.listFolder(path: path, recursive: true, limit: 100).response {
    [weak self] response, error in
    ...
}
```

The version of Swifty Dropbox is 6.0.1.

**Comment by greg-db** [comment]
What is the value of [`ListFolderResult.hasMore`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/ListFolderResult.html#/s:13SwiftyDropbox5FilesC16ListFolderResultC7hasMoreSbvp)? If it's true, you need to call back to [`listFolderContinue`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC18listFolderContinue6cursorAA10RpcRequestCyAA0C0C04ListF16ResultSerializerCAI0kfg5ErrorM0CGSS_tF) to get more results.

**Comment by Yamauchi-ALPS** [comment]
This issue has been resolved with `listFolderContinue`. Thank you very much.
I didn't expect the HasMore flag to be set because there were only 10 responses.
