### ISSUE TITLE
App is crashed for the reason LoadingViewController is not key value coding-compliant for the key imageView (Version: SwiftyDropbox (6.0.3)) 

### ISSUE THREAD

**Issue by SymonRahman** [dropbox/SwiftyDropbox#299]
I've updated swiftyDropbox from version 5.1.0 to 6.0.3. I've also updated web console & code for short lived access token. But
App is crashed when sign in to dropbox.

Xcode Console displays:
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: [<SwiftyDropbox.LoadingViewController 0x103334500> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key imageView.

ScreenShots
<img width="655" alt="Screenshot 2020-12-12 at 8 19 03 PM" src="https://user-images.githubusercontent.com/27943982/101986266-4f2d9080-3cb7-11eb-8779-de5cda9f86df.png">

**Comment by greg-db** [comment]
Can you share the relevant code snippet, and let us know what line this fails on? Thanks in advance!
