### ISSUE TITLE
[crash] Offline Support

### ISSUE THREAD

**Issue by chriseidhof** [dropbox/SwiftyDropbox#30]
Hey!

I'm trying to make sure my app behaves well when being offline, and I got a crash here when trying to access the API while offline (flight mode):

    public func response(completionHandler: ( (RType.ValueType, NSURL)?, CallError<EType.ValueType>?) -> Void) -> Self {
        
        self.request.validate().response {
            (request, response, dataObj, error) -> Void in
            let data = NSData(contentsOfURL: self.urlPath!)!

(For some reason, the `urlPath` is nil). I'll try to find a workaround, haven't really debugged it yet, just wanted to let you know!

**Comment by chriseidhof** [comment]
I changed that line to this, and now it doesn't crash anymore:

            let data = self.urlPath.flatMap { NSData(contentsOfURL: $0) }

**Comment by rpearl** [comment]
Yeah there is a bug with this urlPath behavior, working on a fix. Thanks for the report.
