### ISSUE TITLE
Alamofire for SwiftPM supports minor versions only

### ISSUE THREAD

**Issue by ytroyan** [dropbox/SwiftyDropbox#300]
The last release(6.0.3) supports alamofire .upToMinorVersion("4.8.2") 
But the latest 4.x.x version of Alamofire is 4.9.1
Current SwiftPM settings make it difficult to use with other dependencies
I would like to propose to change from .upToMinorVersion to .upToMajorVersion for next release
It will help find the best configuration for various dependencies

**Comment by greg-db** [comment]
Thanks for writing this up! I can't make any promises but I'll send this request along to the team.

**Comment by ytroyan** [comment]
@greg-db Thank you.
For my project, I already made a fork and made these changes. All tests passed so I think it should not take a lot of time for you as well.

**Comment by greg-db** [comment]
SwiftyDropbox now supports Alamofire 5 with `upToMajorVersion` as of [v8.0.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/8.0.0).

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by greg-db** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
