### ISSUE TITLE
 Sign in with Apple

### ISSUE THREAD

**Issue by cristea2017** [dropbox/SwiftyDropbox#301]
does someone integrated this : [https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple](url)

with dropbox ? 

note that official dropbox app have this feature

**Comment by greg-db** [comment]
While the official Dropbox iOS app itself does implement the Sign in with Apple flow, Dropbox can't offer support for using that, as it's not made by Dropbox. I recommend referring to Apple's documentation and support resources for that.
