### ISSUE TITLE
Fresh pod install - Unbuildable package

### ISSUE THREAD

**Issue by chaitanyaAppic** [dropbox/SwiftyDropbox#302]
Please add iOS version requirement in package.swift. Getting error saying that this is available only on iOS 9.0 and above, while my project targets iOS 12.

**Comment by greg-db** [comment]
To make sure we fully understand this issue, can you let me know what steps you're following when you see this issue, and share the full text of the error?

From your subject, you mention "pod install", so it sounds like you're referring to installing via CocoaPods. [SwiftyDropbox supports iOS 9.0+](https://github.com/dropbox/SwiftyDropbox#system-requirements) and [the SwiftyDropbox.podspec does specify `ios.deployment_target = '9.0'`](https://github.com/dropbox/SwiftyDropbox/blob/master/SwiftyDropbox.podspec), so it should work when targeting iOS 12.

In your message though, you then mention Package.swift, which seems to indicate installing via Swift Package Manager instead. It should be possible to [install SwiftyDropbox via Swift Package Manager](https://github.com/dropbox/SwiftyDropbox#swift-package-manager) when targeting iOS 12 too, so please do let us know how we can reproduce the issue so we can take a look. I'll send this along as a request to specify the version requirement in Package.swift none the less. Thanks!
