### ISSUE TITLE
DropboxClientsManager.authorizedClient is nil after succesful login (iOS)

### ISSUE THREAD

**Issue by gerocar** [dropbox/SwiftyDropbox#304]
I'm setting up an app swift for iOS with the SwiftyDropbox SDK where I want to show and modify data which are stored in a json-file. The files should be accessible from  a dropbox account. Part of my app is a view where the user can select the filedestination at dropbox and type in the necessary information (filename etc) to be accessed. Once the input is finished I start a method to check the inserted data and to check the connectivity to the specified source.

If dropbox is selected I try to launch the authorization within this method as follows:

`if newAccess.credentials.accesstype == .dropbox {
            let scopeRequest = ScopeRequest(scopeType: .user, scopes: ["account_info.read"], includeGrantedScopes: false)
            DropboxClientsManager.authorizeFromControllerV2(
                UIApplication.shared,
                controller: self,
                loadingStatusDelegate: nil,
              openURL: { (url: URL) -> Void in UIApplication.shared.open(url, options: [:], completionHandler: nil) },
                scopeRequest: scopeRequest
            )
           }`

I'm using Xcode 12.3 and test it with an iPhone 8 simulator.

The sign-in workflow of dropbox is launched properly and I can type in my login data for dropbox and grant access. But after allowing the access in the dropbox view the dropbox view remains and there is no jump back to my app. Furthermore, I get the following error in swift: 2021-01-16 06:52:20.212331+0100 ..[1805:55943] -canOpenURL: failed for URL: "dbapi-8-emm://1/connect?k=..........&s=" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)

I checked several hints, but nothing fixed my issue.

If I test my app on my iPhone, where the dropboxApp is installed, the shortened authorization workflow via this app leads to a jump back to my app, but the connection to the dropbox is not authorized- DropboxClientsManager.authorizedClient = nil

Within my dropbox account I have registered my app and created my app-key. The permissions I request are "account.info.read", "files.content.write" and "files.content.read".

I have changed the AppDelegate and the Info.plist as described in the documentation of SDK SwiftyDropbox:

App-Delegate:

`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
[UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    DropboxClientsManager.setupWithAppKey(dropboxAppKey) // my key
    return true
}`

`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    let oauthCompletion: DropboxOAuthCompletion = {
      if let authResult = $0 {
          switch authResult {
          case .success:
              print("Success! User is logged into DropboxClientsManager.")
          case .cancel:
              print("Authorization flow was manually canceled by user!")
          case .error(_, let description):
              print("Error: \(String(describing: description))")
          }
      }
    }
    let canHandleUrl = DropboxClientsManager.handleRedirectURL(url, completion: oauthCompletion)
    return canHandleUrl
}`

Info.plist:

`<key>LSApplicationQueriesSchemes</key>
    <array>
        <string>dbapi-8-emm</string>
        <string>dbapi-2</string>
    </array>
<key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleIdentifier</key>
                <string></string>
                <key>CFBundleTypeRole</key>
                <string>Editor</string>
                <key>CFBundleURLSchemes</key>
                <array>
                    <string>db-...myKey...</string>
                </array>
        </dict>
    </array>`

Has anyone an idea what I'm doing wrong? Thanks for your support.

**Comment by greg-db** [comment]
The "10814" error is safe to ignore; it just means that the EMM version of the Dropbox app isn't installed. The SDK will fall back to the standard flow though.

The redirect back to your app would be handled by the "db-<APP_KEY>" URL scheme registered in [this step](https://github.com/dropbox/SwiftyDropbox#application-plist-file). Can you double check that "<APP_KEY>" is replaced with the exact same value as your `dropboxAppKey` value?

Also, the handling is then implemented by [this step](https://github.com/dropbox/SwiftyDropbox#handle-redirect-back-into-sdk). It seems like you have that in place. Are you using scenes though? If so, you may be running in to [this issue](https://github.com/dropbox/SwiftyDropbox/issues/259).

**Comment by gerocar** [comment]
Dear greg-db,

thanks for your reply. I checked the info.plist - the entries are correct.
The handling in AppDelegate is as described too. 

I have scenes (automatically added to the App when setting it up in Xcode) - is there meanwhile a documentation available how this has then to handled as announced in the other post? Would be highly appreciated.

Thanks for your support

**Comment by greg-db** [comment]
Thanks for following up. We don't have the official documentation updated for scenes yet unfortunately.

I have a slightly updated version of the code in [this post](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Re-Can-t-close-the-page-after-authentication/m-p/464801/highlight/true#M23758) actually. Please give that a try and let me know if that doesn't help.

**Comment by gerocar** [comment]
Dear greg-db,

thanks for your last advice. It works on my iPhone-App and solved the issue. But it doesn't work on my iPad-version. 

My iPad-app is in splitscreen mode and I want to launch the dropbox access from a modally shown view on the detailscreen. But the access screen from dropbox is not popping up when I want to request access via `DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self, openURL: {(url: URL) -> Void in UIApplication.shared.openURL(url)})`.

Info.plist shows the correct entries and I have put the code from your last advise into SceneDelegate in addition to the entries in AppDelegate.

Another question: with the above shown acces request I get the remark that "'openURL' was deprecated in iOS 10.0". How has this to be fixed?
Thanks for your help

**Comment by greg-db** [comment]
Do you get any error or output when you call `authorizeFromController` in that case?

And yes, that usage of `openURL` is deprecated. I'll ask the team to update the documentation with the new usage, which I believe would be [`open(_:options:completionHandler:)`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open).

**Comment by gerocar** [comment]
I guess, I could solve it at least to a certain extend:

I had set up a method on the MasterViewController `func connectDropbox() {
              DropboxClientsManager.authorizeFromController(UIApplication.shared, controller: self, openURL: {(url: URL) -> Void in UIApplication.shared.openURL(url)})    }` to initiate the DropboxConnect from different views in my app. With this setup I get the following error messages and it doesn't work:

> 2021-02-02 05:51:55.640248+0100 Kochbuch-iPad[1583:46047] XPC connection interrupted
2021-02-02 05:52:03.079577+0100 Kochbuch-iPad[1583:44726] -canOpenURL: failed for URL: "dbapi-2://1/connect?k=q*************z&s=" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)"
2021-02-02 05:52:03.080547+0100 Kochbuch-iPad[1583:44726] -canOpenURL: failed for URL: "dbapi-8-emm://1/connect?k=q*************z&s=" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)"
2021-02-02 05:52:03.609669+0100 Kochbuch-iPad[1583:44726] [Presentation] Attempt to present <SwiftyDropbox.MobileSafariViewController: 0x7ff0f78f5800> on <UISplitViewController: 0x7ff0f6e082e0> (from <Kochbuch_iPad.HomeVC: 0x7ff0f801b000>) which is already presenting <Kochbuch_iPad.EinstellungenVC: 0x7ff0f6e17020>.

When I modify my programm and insert the `authorizeFromController`directly into the actual ViewController the call works and I get access to the dropbox. However, the following error messages still appear (is it due to the depreciated `openURL`?

> 2021-02-02 05:55:22.628240+0100 Kochbuch-iPad[1652:49460] -canOpenURL: failed for URL: "dbapi-2://1/connect?k=q*************z&s=" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)"
2021-02-02 05:55:22.629027+0100 Kochbuch-iPad[1652:49460] -canOpenURL: failed for URL: "dbapi-8-emm://1/connect?k=q*************z&s=" - error: "Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -10814.)"

**Comment by greg-db** [comment]
The "10814" errors are safe to ignore. That's the SDK checking if the official Dropbox iOS app (either the standard or EMM version) is installed. This indicates they are not, but the SDK will fall back to using the web flow in that case.

That being the case, it sounds like this is working for you now so I'll close this out, but let us know if there are still any issues.
