### ISSUE TITLE
Login without showing web view interface ? 

### ISSUE THREAD

**Issue by PrashantKT** [dropbox/SwiftyDropbox#306]
I need to login in dropbox without showing web view is it possible ?

**Comment by greg-db** [comment]
In order for the app to get access to the user's account, the user needs to manually authorize the app. This involves sending the user through the app authorization flow. If the official Dropbox iOS app is installed, that will be used for that flow. If it isn't, the SDK will use a `SFSafariViewController` instead.

This only needs to be done once per user though. Once they do so, the SDK will store and re-use the access token. Make sure your [configure your app as instructed](https://github.com/dropbox/SwiftyDropbox#configure-your-project) to do so. You can then use the stored access token by using the `DropboxClientsManager.authorizedClient` [as shown here](https://github.com/dropbox/SwiftyDropbox#dropbox-client-instance).
