### ISSUE TITLE
Unexpectedly found nil while unwrapping optional value

### ISSUE THREAD

**Issue by alex1704** [dropbox/SwiftyDropbox#31]
Unexpectedly found nil while unwrapping optional value in Client.swift (BabelDownloadRequest::init) file on line 285 (_self.urlPath = ret)

**Comment by alex1704** [comment]
version 0.7.1

**Comment by rpearl** [comment]
Yeah there is a bug here, working on it! Thanks for the report.

**Comment by spyrospassas** [comment]
This appears in v2.0.3 as well: Unexpectedly found nil while unwrapping optional value in Client.swift (BabelDownloadRequest::init) file on line 302 (_self.urlPath = ret)
