### ISSUE TITLE
Support for Alamofire 5.2

### ISSUE THREAD

**Issue by MunteanBeniamin** [dropbox/SwiftyDropbox#318]
Is there any chance that you guys will update to Alamofire 5.2? I read the thread for Alamofire 5.0.0 and got disappointed, after almost 3 years you guys are still on the same 4.8 version. Shame on the management team! this improvement is really needed by most of the applications. There are a lot of guides on how to migrate to the latest version.

Thanks!

**Comment by greg-db** [comment]
Thanks for the note! I can't make any promises myself, but I'll send this request along to the team.

**Comment by inPhilly** [comment]
Any progress on this issue?

**Comment by greg-db** [comment]
@inPhilly No, I don't have an update on this right now.

**Comment by yangyu2010** [comment]
Really have to take this issue seriously

**Comment by greg-db** [comment]
SwiftyDropbox now supports Alamofire 5 as of [v8.0.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/8.0.0).

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as to remove the dependency on Alamofire. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by greg-db** [comment]
The beta mentioned above has been promoted to stable release. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
