### ISSUE TITLE
Authorize with Generated Access Token

### ISSUE THREAD

**Issue by ludoded** [dropbox/SwiftyDropbox#320]
Can I authorize the user of the app, without presenting the external web view with Dropbox authentication, but instead set a generated OAuth2 Access Token?

In our case, we don't want to give a direct access to our Dropbox Team account. We want all the app users be able to upload files to our team space through a single, general dropbox account, so they won't have their own dropbox accounts.

Is that possible to achieve with the current version of this SDK?

Thanks

**Comment by greg-db** [comment]
Yes, it is technically possible to create a client object using a specific predefined access token like this, for instance by using [one of these initializers](http://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/DropboxClient.html).

However, please note that the Dropbox API was designed with the intention that each end-user would directly connect their own Dropbox account to the API app. It's technically possible to connect to just one account like this, by always using a specific access token, but we generally don't recommend or support doing so though, for various technical and security reasons.
