### ISSUE TITLE
Can not parse search result

### ISSUE THREAD

**Issue by JituAudify** [dropbox/SwiftyDropbox#326]
if let client = DropboxClientsManager.authorizedClient {
           
            client.files.searchV2(query: ".mp3").response { (response, error) in
                
                if let err = error {
                    print("DROPBOX ERROR ",err.description)
                    Helper.globalAlert(msg: err.description)
                    self.viewIndicator.isHidden = true
                    return
                }
                
                guard let result = response else {return}
                
                for entry in result.matches {
                    print(entry.metadata)
                    //here i am not able to parse this metadata into File or Folder metadata
                }
            }
        }

I got response like below:

{
    ".tag" = metadata;
    metadata =     {
        ".tag" = file;
        "client_modified" = "2021-01-19T11:57:39Z";
        "content_hash" = b07c744cd374977fba8335c9604a80225245665fa622123b0408461880eaa34b;
        id = "id:RstmrXtv2GYAAAAAAAABNw";
        "is_downloadable" = 1;
        name = "02. Viraaniya.mp3";
        "path_display" = "/02. Viraaniya.mp3";
        "path_lower" = "/02. viraaniya.mp3";
        rev = 5c6242bd906b76b356761;
        "server_modified" = "2021-07-02T13:45:40Z";
        size = 5544704;
    };
}

How to convert this response into Files.Metadata?

**Comment by greg-db** [comment]
You can use `switch` and `case` to handle the different types, such as in [this example](https://github.com/dropbox/SwiftyDropbox#response-handling-edge-cases), like this:
```
for entry in result.matches {
    switch entry.metadata {
    case .metadata(let entry_metadata):
        switch entry_metadata {
            case let fileMetadata as Files.FileMetadata:
                print("File metadata: \(fileMetadata)")
            case let folderMetadata as Files.FolderMetadata:
                print("Folder metadata: \(folderMetadata)")
            case let deletedMetadata as Files.DeletedMetadata:
                print("Deleted metadata: \(deletedMetadata)")
            default:
                print("other type")
          }
    default:
        print("other type")
    }
}
```

**Comment by JituAudify** [comment]
> You can use `switch` and `case` to handle the different types, such as in [this example](https://github.com/dropbox/SwiftyDropbox#response-handling-edge-cases), like this:
> 
> ```
> for entry in result.matches {
>     switch entry.metadata {
>     case .metadata(let entry_metadata):
>         switch entry_metadata {
>             case let fileMetadata as Files.FileMetadata:
>                 print("File metadata: \(fileMetadata)")
>             case let folderMetadata as Files.FolderMetadata:
>                 print("Folder metadata: \(folderMetadata)")
>             case let deletedMetadata as Files.DeletedMetadata:
>                 print("Deleted metadata: \(deletedMetadata)")
>             default:
>                 print("other type")
>           }
>     default:
>         print("other type")
>     }
> }
> ```

Thank you so much. It's working fine.
