### ISSUE TITLE
How I can make cancel the downloading?

### ISSUE THREAD

**Issue by JituAudify** [dropbox/SwiftyDropbox#327]
I have implemented the below code for downloading the audio files and its working fine but I want to make cancel the downloading

if let client = DropboxClientsManager.authorizedClient {
            
            client.files.download(path: filePath, overwrite: true, destination: destination)
                .response { response, error in
                    if let response = response {
                        //  print("RES :", response)
                    } else if let error = error {
                        print("ERR :",error)
                    }
                }
                .progress { progressData in
                    //print("PROGRESS :",progressData.fractionCompleted)
                }
        }      

Please provide any solution.

**Comment by greg-db** [comment]
Apologies there isn't better documentation on this, but if you keep a reference to any particular request, you can call `.cancel()` on it to cancel it, like this:
```
let request = client.files.download(...)
```
```
request.cancel()
```
