### ISSUE TITLE
The package product 'Alamofire' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0

### ISSUE THREAD

**Issue by stsandro** [dropbox/SwiftyDropbox#333]
I wanted to try out `SwiftyDropbox-8.0.0`, but when I do this via Swift Package Manager the following error occurs:

```
The package product 'Alamofire' requires minimum platform version 10.0 for the iOS platform, but this target supports 9.0
```

I think this is due to the missing platforms and versions declaration in the `Package.swift`. My guess is that the default is `iOS 9` and since `Alamofire` needs `iOS 10` you have to specify at least that. Here's what it should look like:

```swift
let package = Package(
    name: "SwiftyDropbox",
    platforms: [.iOS(.v10)],
    products: [
        .library(name: "SwiftyDropbox", targets:["SwiftyDropbox"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Alamofire/Alamofire.git", .upToNextMinor(from: "5.4.3")),
    ],
    targets: [
        .target(
            name: "SwiftyDropbox",
            dependencies: ["Alamofire"],
            path: "Source"
        )
    ]
)
```

**Comment by stsandro** [comment]
Oh, I see there is already a PR addressing this issue #332. This PR should resolve this issue.

**Comment by YufeiG** [comment]
Hi there, please try 8.0.1

**Comment by stsandro** [comment]
Yes, that works. Thanks 🙏
