### ISSUE TITLE
SwiftUI support

### ISSUE THREAD

**Issue by amoshsueh** [dropbox/SwiftyDropbox#334]
Is there a schedule to support SwiftUI? 

Thanks.

**Comment by greg-db** [comment]
No, there isn't a timeline for if or when Dropbox may test and officially support SwiftUI for SwiftyDropbox, but I'll pass this along as a feature request. I can't promise if/when that might be done though.

**Comment by andreasley** [comment]
Any news on this? It's not like SwiftUI is going away. :)

**Comment by greg-db** [comment]
@andreasley Thanks for the note! The team is working on this, but I can't promise a timeline for release right now. I'll follow up here once I have something to share.

**Comment by greg-db** [comment]
The team has updated SwiftyDropbox to support SwiftUI in the latest version of the SDK (v9.1.0). Let us know if you try that and run in to any issues. Thanks!
