### ISSUE TITLE
Support for multiple accounts with short lived tokens

### ISSUE THREAD

**Issue by adibendahan** [dropbox/SwiftyDropbox#338]
Hello,

In my app I currently support multiple user accounts on Dropbox, with more than one concurrent active user (more than one account can be used to upload/download a file at the same time). In order to do it I followed the instructions on:
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/SwiftyDropbox-and-support-for-multiple-accounts/td-p/143755

Now, when I am trying to update to the latest 8.1.0 release with short lived tokens, I encountered an issue:
I need to create a `DropboxClient` with `AccessTokenProvider` instead of `accessToken` if I want it to support token refresh, but this is not possible because the API to create `AccessTokenProvider` is internal.

On the other hand, I could use `DropboxClientsManager` to create a token refreshing client but it is a singleton that supports only one concurrent active user (it has a single `authorizedClient` member).

Am I missing something? Can this be done in a different way?

Thanks,
Adi.

**Comment by greg-db** [comment]
Thanks for writing this up! I believe you have this correct; we'd need to update the SDK to let you have multiple automatically refreshing clients simultaneously like this.

Currently, you can set up multiple accounts and use any particular one by switching using `reauthorizeClient` as [covered here](https://github.com/dropbox/SwiftyDropbox#multiple-dropbox-user-case), but it looks like the SDK doesn't offer a way to access multiple such clients simultaneously, or manually initialize an automatically refreshing client. 

We'll look into this and I'll follow up here once I have an update.

**Comment by YufeiG** [comment]
I added an init for creating the dropbox client, hope it works for you.
https://github.com/dropbox/SwiftyDropbox/pull/339

**Comment by adibendahan** [comment]
@YufeiG that's great news, thank you!
When can I expect it as a release?

**Comment by greg-db** [comment]
@adibendahan We can't guarantee a timeline right now, but I'll ask the team to do a release soon.

**Comment by shelefg** [comment]
Thanks for the updated version 👍 

By looking at the code it seems that with short-lived tokens, creating multiple DropboxClient instances for the same access token using the new init might lead to concurrent token refreshes. 
ShortLivedAccessTokenProvider synchronizes refreshes, but each client creates a new AccessTokenProvider instance. Is that correct?

Should I make sure I only create a single DropboxClient instance for each access token?

**Comment by greg-db** [comment]
> ShortLivedAccessTokenProvider synchronizes refreshes, but each client creates a new AccessTokenProvider instance. Is that correct?

Yes, that’s correct.

> Should I make sure I only create a single DropboxClient instance for each access token?

Yes, while it probably shouldn’t cause any issues, we recommend only creating a single instance for each access token.

**Comment by greg-db** [comment]
It sounds like the new functionality in v8.2.0 resolves this, so I'm closing this issue, but please let us know if you still have any issues. Thanks!
