### ISSUE TITLE
Uploading big files gives error

### ISSUE THREAD

**Issue by nikolasborrel** [dropbox/SwiftyDropbox#34]
Calling 

    client.files.upload(path: pathToDest, body: urlToLocalFile)

returns the following error object after having uploaded ~233 MB

    HTTPError = {
        0 = nil
        1 = ""
        2 = ""
    }

It seems (mostly) to be a problem with bigger files. Is it a known issue?

**Comment by nikolasborrel** [comment]
If I give a NSInputStream as input, I get the same error as described above, but also this error is returned now and then:

(SwiftyDropbox.CallError<SwiftyDropbox.Files.UploadError>?) error = BadInputError {
  BadInputError = {
    0 = "<!DOCTYPE html>\n<html>\n<head><title>Dropbox - 4xx</title>\n<link href=\"//www.dropbox.com/static/css/error.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<link rel=\"shortcut icon\" href=\"//www.dropbox.com/static/images/favicon.ico\"/>\n</head>\n<body>\n<div class=\"figure\">\n<img src=\"//www.dropbox.com/static/images/psychobox.png\" alt=\"Error: 4xx\"/>\n</div>\n<div id=\"errorbox\">\n<h1>Error (4xx)</h1>We can't find the page you're looking for. Check out our <a href=\"https://www.dropbox.com/help\">Help Center</a> and <a href=\"https://forums.dropbox.com\">forums</a> for help, or head back to <a href=\"https://www.dropbox.com/home\">home</a>.\n</div>\n\n<script type=\"text/javascript\" src=\"//www.dropbox.com/static/javascript/external/prototype.js\"></script>\n<script>\nmessage = {\"ru\": \"\\u003ch1\\u003e\\u041e\\u0448\\u0438\\u0431\\u043a\\u0430 (4xx)\\u003c/h1\\u003e\\u0417\\u0430\\u043f\\u0440\\u043e\\u0448\\u0435\\u043d\\u043d\\u0430\\u044f \\u0432\\u0430\\u043c\\u0438 \\u0441\\u0442\\u0440\\u0430\\u043d\\u0438\\u0446\\u0430 \\u043d\\u0435 \\u043d\\u0430\\u0439\\u0434\\u0435\\u043d\\"
    1 = "e2cf0c68fac1ba8465bcca4f9a6640f4"
  }
}

**Comment by rpearl** [comment]
Thanks for the report, we'll take a look.

**Comment by rpearl** [comment]
Hey @nikolasborrel, 

Looking into this, while we need to improve the error message, your issue is in usage--for large files, you need to upload the file in chunks. Please ask for support help in our [API Development Forum](https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development) and someone will be able to help you understand the call patterns.

**Comment by nikolasborrel** [comment]
Thanks, I managed to figure out how to upload the file in chunks. Though, it would be nice if your API could hide the complexity.
