### ISSUE TITLE
Tag 7.0.1 can't be built with Swift 5.0.x

### ISSUE THREAD

**Issue by msbit** [dropbox/SwiftyDropbox#341]
Tag 7.0.1 is marked as [buildable with Swift 5.0.x](https://github.com/dropbox/SwiftyDropbox/blob/7d5f3aec0977070627eb6d4ef1ce1be67734d226/Package.swift#L1) but there are a few features that were introduced in 5.1.x in use in the codebase, namely:

* `Self` can be used to refer to the type introduced by the current class, structure, or enumeration declaration
* enumeration case pattern can match an optional value
* implicit function return for functions whose body is a single expression

Not sure what the best path is for this tag, whether to:

* update `swift-tools-version` to `swift-tools-version:5.1`
* incorporate changes similar to the following:
  * https://github.com/msbit/SwiftyDropbox/commit/3dc7b92309430681cb52fc428c282263bf55af04
  * https://github.com/msbit/SwiftyDropbox/commit/61aa1b563e61f2f39ec5d47b12ea8a71c7fc4a5e
  * https://github.com/msbit/SwiftyDropbox/commit/03e8c45a15fde1465f10f785a4c213c2f35ac950

**Comment by greg-db** [comment]
Thanks for writing this up, and apologies for the inconvenience here. We have already updated `swift-tools-version` to `swift-tools-version:5.1`, so I recommend upgrading to the latest version of the SDK (currently 8.2.0).

**Comment by msbit** [comment]
Hey @greg-db, thanks for taking a look!

I didn't communicate properly what I was thinking; in my mind those changes I put forward would be applied on a newly created branch (`7.0.x` for example) that would then be tagged off with an updated version (for example `7.0.2`).

This is mainly to ensure that there is a tag of this library that is buildable by clients using Swift 5.0.x, as for various reasons (primarily those originally raised), none are.

**Comment by greg-db** [comment]
@msbit Thanks for following up. The team isn't currently maintaining branches for older versions like this, but I'll pass this along as a request to so. I can't promise if or when that might be done though.

**Comment by msbit** [comment]
All good @greg-db. Thanks again for taking a look.
