### ISSUE TITLE
Error when downloading empty file, crash the app

### ISSUE THREAD

**Issue by hexise** [dropbox/SwiftyDropbox#344]
I am using client.files.download(path: path) to open an empty file, which lead to app crash.

I found the code in DropboxTransportClient.swift, line 707, there is a hard conversion: response.data!, when response.data is nil, this will crash.

Can response.data! be replaced to **response.data ?? Data()**

I am new to swift but I think this is a bug in the library, could you review the code for this? Thanks.

**Comment by drewmccormack** [comment]
Yep, seeing this too. Pretty nasty, because takes down whole app.

**Comment by greg-db** [comment]
This is now fixed in v8.3.0.
