### ISSUE TITLE
Direct Auth(iOS) is not working, if the Dropbox app was installed

### ISSUE THREAD

**Issue by mammaiap** [dropbox/SwiftyDropbox#345]
1) if "dropbox" app was already installed, then it wont proceed to show the "Authentication screen"
2) if "dropbox" app was not installed, then there is no problem.(it shows the Authentication screen) 

->> i followed exact steps which you guys are described in the tutorials ...  (thats why it is working for "non Dropbox app installed" iOS devices. 

here is the code snippets related to authentication workflow 
in AppDelegate.m  (in objective c)
 
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{    
      [PhotoPickerEngine.sharedEngine setupSocialNetworks];
}

- (BOOL)application😞UIApplication *)app openURL😞NSURL *)url options😞NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{

NSString *urlString = [[[url absoluteString] componentsSeparatedByString:@":"] objectAtIndex:0];

if ([urlString isEqualToString:@"db-xxxxxxxxxx”])

{

[PhotoPickerEngine.sharedEngine handleRedirectURLWithUrl:url];   //dropbox to handle 

}

}

//swift code 

@objc public func setupSocialNetworks()

{              
DropboxClientsManager.setupWithAppKey(“APP_KEY”)             
}

 

@objc public func handleRedirectURL( url: URL)
{     
        DropboxClientsManager.handleRedirectURL(url, completion: { (authResult) in

            switch authResult {

            case .success(let token):

                print("Success! User is logged into Dropbox with token: \(token)")

                EventHub.post(DropboxLoginEvent())

                UserDefaults.standard.set(token.accessToken, forKey: Constants.keyAccessTokenDropbox)

            case .cancel:

                print("User canceld OAuth flow.")

            case .error(let error, let description):

                print("Error \(error): \(String(describing: description))")

            case .none:

                break

            }

        })

    }
 

  the version number of the Dropbox SDK    : 6.0.3

  the version number of the Dropbox iOS app : 258.2.2

  the version number of iOS : 15.0.1

can you please help me to fix this issue?

Thanks ,
Muthulingam

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/iOS-Problems-connecting-from-own-app-to-Dropbox-when-Dropbox-App/m-p/554844/highlight/true#M26295](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/iOS-Problems-connecting-from-own-app-to-Dropbox-when-Dropbox-App/m-p/554844/highlight/true#M26295) ]

I see you also [posted on an existing thread](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/iOS-Problems-connecting-from-own-app-to-Dropbox-when-Dropbox-App/m-p/554844/highlight/true#M26295) on the Dropbox forum regarding this, so I'll close this out and follow up with you there. For future reference, it's not necessary to share reports like this in multiple places.
