### ISSUE TITLE
not possible to access the thumbnail from getThumbnailBatch in swiftydropbox

### ISSUE THREAD

**Issue by mammaiap** [dropbox/SwiftyDropbox#349]
DropboxClientsManager.authorizedClient?.files.getThumbnailBatch(entries: subList).response(queue: DispatchQueue.global(qos: .default), completionHandler: { (dataResponse, error) in

                                                

                if((dataResponse) != nil)

                {

                    let results = dataResponse?.entries

                    

                    //print("getThumbnailBatch dataResponse:",results)

                    

                    results?.forEach { result in

                        

                        //let descstr = result.description

                        

                       

                        

                    }

                    

                    

                }

                

                

            })

 

here "result" is  GetThumbnailBatchResultEntry ... that is "ENUM" ..

 

can anyone help me, how to get the "

"thumbnail" and "metadata" from this ..

 

result.thumbnail and result.metadata throws the compilation error ...

 

so how i can access the "thumbnail and "metadata"?

**Comment by greg-db** [comment]
[The `GetThumbnailBatchResultEntry` type](http://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/GetThumbnailBatchResultEntry.html) is a union to cover `success`, `failure`, and `other` cases, so you'll need to use a `switch` to handle each case, like this:
```swift
switch result {
    case .success(let data):
        print(data.metadata)
        print(data.thumbnail)
    case .failure(let error):
        print(error)
    case .other:
        print("other result")
}
```

**Comment by mammaiap** [comment]
ok ...i will try it 

Thanks

**Comment by mammaiap** [comment]
Hi greg,
 it worked. thanks
