### ISSUE TITLE
Would like non-deprecated getting-started code

### ISSUE THREAD

**Issue by markd2** [dropbox/SwiftyDropbox#350]
Hi! Working through the "let's get started", and out of the gate have

```
 // Note: this is the DEPRECATED authorization flow that grants a long-lived token.
```

it'd be nice if the bootstrap docs had the most-blessed way of doing things, since a great majority of folks (I believe) who want to get-in and get-out (where dropbox integration is not the focal point of the app) will be wanting to use the bootstrap code and then move on. That would save a lot of developers a lot of time as the years go on.

**Comment by greg-db** [comment]
Thanks for the note. It sounds like you're referring to [this section of the readme](https://github.com/dropbox/SwiftyDropbox#ios-2). The current correct method is the `authorizeFromControllerV2` call shown just above the line you quoted. The old one is included for reference too, but I see that would be confusing so I'll ask the team to just remove that for clarity.

**Comment by julianlocke** [comment]
The latest version of SwiftyDropbox includes this change. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
