### ISSUE TITLE
UIWebview is depricated

### ISSUE THREAD

**Issue by Shalena** [dropbox/SwiftyDropbox#351]
Hi guys,
I uploaded build using your library and was rejected with the reason “Please, remove the UIWebview”
Can you replace it in your code please?
Thank you for support 
Olena Ostrozhynska

**Comment by greg-db** [comment]
Can you share more information about this issue? Specifically, what use of `UIWebview` are you referring to? [The SwiftyDropbox source code does not contain any reference to `UIWebview`](https://github.com/dropbox/SwiftyDropbox/search?q=UIWebview).

**Comment by Shalena** [comment]
Sure, here is my information:
I use Xcode 13.1
My podfile consists of the only pod at the current moment -   pod 'SwiftyDropbox'.
After pod install I got SwiftyDropbox (8.2.1) and Alamofire (5.4.4).
After that I check my build this way:
In command line:
cd ~/Library/Developer/Xcode/Archives/2022-01-14
I have my only archive MyProject 14.01.2022, 00.09.xcarchive
grep -R UIWebView *
My results:
Binary file Upload 14.01.2022, 00.09.xcarchive/dSYMs/SwiftyDropbox.framework.dSYM/Contents/Resources/DWARF/SwiftyDropbox matches
Binary file Upload 14.01.2022, 00.09.xcarchive/dSYMs/Alamofire.framework.dSYM/Contents/Resources/DWARF/Alamofire matches
My own code doesn't have reference to UIWebView

Uploading files to the Dropbox is the main feature of my project, so I can't remove SwiftyDropbox 
Thank you for quick response)

**Comment by greg-db** [comment]
Thanks for following up with the additional information. I'm still not sure what `UIWebview` reference this is though. I also [don't see any `UIWebview` reference in Alamofire either](https://github.com/Alamofire/Alamofire/search?q=UIWebview). 

In any case, no, SwiftyDropbox does not use `UIWebview`. If you're referring to the web browser used to process the OAuth app authorization flow (when the official Dropbox iOS app is not installed), [that's a `SFSafariViewController`, not a `UIWebview`](https://github.com/dropbox/SwiftyDropbox/blob/8d5600b3331a1777ef50633bdb7419d357523847/Source/SwiftyDropbox/Platform/SwiftyDropbox_iOS/OAuthMobile.swift#L438).

Did Apple provide any other information that you can share? I also can't say why your archive contains that string when our code doesn't; perhaps Apple can provide some guidance on that.

**Comment by julianlocke** [comment]
The latest version of SwiftyDropbox no longer includes Alamofire. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
