### ISSUE TITLE
Auth flow failed because of inconsistent state.

### ISSUE THREAD

**Issue by smattar2020** [dropbox/SwiftyDropbox#354]
When I do Dropbox Auth Flow with SwiftUI, dropbox raises error, Auth flow failed because of inconsistent state.

**Comment by greg-db** [comment]
Unfortunately, the Dropbox iOS Swift SDK does not officially support SwiftUI. I'll pass this along as a request for official support for that, but I can't promise if/when that would be done. (There's [a thread here](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/SwiftyDropbox-SwiftUI-iOS/m-p/500357) that may be helpful though.)

**Comment by smattar2020** [comment]
I tried the examples in the thread and they did not change the output. I am making a macOS app.

**Comment by greg-db** [comment]
Thanks for following up. I'm sorry to hear that didn't help. I'll follow up here if/when the team officially adds support for SwiftUI.

**Comment by smattar2020** [comment]
I don't think this is a problem with SwiftUI, as the URL Dropbox redirects to is: `db-<APP KEY>://2/token?code=<CODE>&state=<STATE>`, and not `db-<APP KEY>://2/token?access_token=<ACCESS TOKEN>`

**Comment by smattar2020** [comment]
What format of redirect URI does SwiftyDropbox expect?

**Comment by smattar2020** [comment]
Is there a way to manually parse the URL and get the Access Token?

**Comment by greg-db** [comment]
Thanks for following up and clarifying. I'm glad to hear you got this working.

For reference though, unless SwiftUI is somehow complicating this, you shouldn't have to parse the URLs yourself. As long as you implement the authorization flow as shown in [the documentation here](https://github.com/dropbox/SwiftyDropbox#configure-your-project), using `authorizeFromControllerV2` (which is preferred, or `authorizeFromController`, which is deprecated, but not both), the SDK should handle this all for you automatically.
