### ISSUE TITLE
Background Upload

### ISSUE THREAD

**Issue by Arshiii4425** [dropbox/SwiftyDropbox#356]
Is it possible to upload the large files when app goes in background?

**Comment by Arshiii4425** [comment]
Thanks @greg-db for quick response, is there any way we can use [NSURLSession](https://developer.apple.com/documentation/foundation/nsurlsession) and SwiftDropbox together to upload large file while app is in background. Thanks again.

**Comment by greg-db** [comment]
We've released a beta version of SwiftyDropbox with some significant updates, such as support for background sessions. You can find more information here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Beta-version-of-major-SwiftyDropbox-update-available/td-p/695441

**Comment by julianlocke** [comment]
The background session support mentioned above is now released in a stable version. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
