### ISSUE TITLE
ETA for Release of SwiftyDropbox v10

### ISSUE THREAD

**Issue by ChrisPearce** [dropbox/SwiftyDropbox#376]
Thanks for all the hard work on v10.

My own testing has not uncovered any problems.

I'm looking forward to the official release. Is there a rough ETA on when that is likely to be?

**Comment by inPhilly** [comment]
I'm excited for this API, but my issue is that I need it immediately. App validation was rejected with the current Carthage version of the current Objective-C API. (This is an old, large code base). What are my options until 10.0.0 is released, and the is this release expected?

**Comment by jcenturion18** [comment]
> I'm excited for this API, but my issue is that I need it immediately. App validation was rejected with the current Carthage version of the current Objective-C API. (This is an old, large code base). What are my options until 10.0.0 is released, and the is this release expected?

@inPhilly the ObjC SDK is not that different to implement from the 9.x version. We had been using the objc sdk (7.1) for a while without any problem on Apple

**Comment by greg-db** [comment]
@inPhilly As Julian mentioned, it should still be possible to use the versions before v10. I also [replied](https://github.com/dropbox/dropbox-sdk-obj-c/issues/374#issuecomment-1816883132) to your comment on the other issue you commented on, so please take a look at that and open a new issue if needed.

**Comment by inPhilly** [comment]
It was actually another sdk that was causing the validation to fail. I'm sorry for the confusion. Still, when do you expect this to be released? Dropbox is my last holdout for Carthage, I'm excited to see Carthage go.

**Comment by greg-db** [comment]
@inPhilly I don't have a timeline to share for the release of SwiftyDropbox v10, but reference [the current version of SwiftyDropbox supports Swift Package Manager and CocoaPods installation](https://github.com/dropbox/SwiftyDropbox#sdk-distribution) in addition to Carthage, and [the current version of the Dropbox Objective-C SDK supports CocoaPods](https://github.com/dropbox/dropbox-sdk-obj-c#sdk-distribution) in addition to Carthage, so you can switch off of Carthage currently if you wish.

**Comment by greg-db** [comment]
This is now available out of beta. More information can be found here in [this announcement](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816).
