### ISSUE TITLE
(10.0.0-beta1) MockDropboxTransportClient is not public, so it can't be used in it tests

### ISSUE THREAD

**Issue by erykmroczko** [dropbox/SwiftyDropbox#377]
Hi,

Is there a reason why MockDropboxTransportClient is not public? The same with eg. MockInput. We would love to test it, but we don't want to unlock the code just to write the "public" word :)

Is there a chance to fix it in next/future release of v10?

PS. V10 is awesome! we're waiting for the official release. 

Greetings,
Eryk

**Comment by greg-db** [comment]
Thanks for the feedback!

I'm bringing this up with the team to look into this and see if we can make `MockDropboxTransportClient` public.

**Comment by greg-db** [comment]
The team checked on this and clarified that these are only meant to be available when `SwiftyDropbox` is imported with the `@testable` attribute. We've updated [the information and example in the readme](https://github.com/dropbox/SwiftyDropbox/tree/branch_10.0.0-beta#mock-api-responses-in-tests). 

Please try that out and let us know if that doesn't work for you. Thanks!
