### ISSUE TITLE
Update for Alamofire 3.1

### ISSUE THREAD

**Issue by Sahilberi** [dropbox/SwiftyDropbox#38]
- `Alamofire (~> 3.0.0)` required by `SwiftyDropbox (2.0.2)`

It would be better if you remove the fix version from the pod 

i.e. in you pod file you can use `~>3.1` instead of `~>3.1.0` this will help us to keep updated with the bugs fixed by the Alamofire.

Just because of the older version of the Alamofire(3.0.0) we are not using this sdk right now.

Please update your sdk so that the other developers using latest version of Alamofire can use this sdk,
otherwise there is no use of this sdk

**Comment by InderKumarRathore** [comment]
:+1:  from my side as well,

If this is not including the latest Alamofire then it's a risk for us to use  buggy version of Alamofire

**Comment by joeljfischer** [comment]
I created a PR for this as #40

**Comment by wkiefer** [comment]
Thank you @joeljfischer! Merged at https://github.com/dropbox/SwiftyDropbox/commit/75aa2a747d9b5f7e22b22fb24ad090ad500973da

**Comment by InderKumarRathore** [comment]
Changes not submitted to cocoapod.
Please review the below Pull Request #41

**Comment by wkiefer** [comment]
I'm not a current owner of the podspec but will make sure this happens asap. Thanks!

**Comment by Sahilberi** [comment]
still changes not submitted to cocoapod.
it is showing :
  "dependencies": {
    "Alamofire": [
      "~> 3.0.0"
    ]
  }

**Comment by wkiefer** [comment]
Yep - should be updated tomorrow. Thanks!

**Comment by wkiefer** [comment]
Should be updated now - thanks!

**Comment by InderKumarRathore** [comment]
Thanks

**Comment by Sahilberi** [comment]
Thanks @wkiefer.
