### ISSUE TITLE
Assertion failure using fileSearch

### ISSUE THREAD

**Issue by aufflick** [dropbox/SwiftyDropbox#4]
Hi,

Been trying this out, but when I try to do a file search, I get this assertion while the sdk is parsing results. The assertion is originally raised by the stringValidator call in FileMetadata init()

`assertion failed: "2ec6g012cf0b7" must be at most 9 characters: file /.../Pods/SwiftyDropbox/Source/BabelValidators.swift, line 5`

NB: I changed some of the identifier's letters in case it's identifying somehow, but the length is as is.

**Comment by aufflick** [comment]
If I change the validator to max length 13 it seems to work fine, and that value seems to be the `rev` key in the metadata returned.

**Comment by rpearl** [comment]
Our code has changed quite a bit, and I definitely can't repro this now. Let me know if something of this sort comes up again?
