### ISSUE TITLE
v10 fails to detect app Bundle ID and stores authorization without it

### ISSUE THREAD

**Issue by andreasley** [dropbox/SwiftyDropbox#407]
When trying to upgrade my macOS app from using the SwiftyDropbox SDK v9 to v10, I've noticed that the authorization wasn't carried over on existing installations.

After checking the macOS keychain, I've noticed that the authorization for the v9-based app had the name `my.app.identifier.dropbox.authv2` while the one using v10 had just `.dropbox.authv2` (yes, starting with a dot).

v9 fetched the app bundle ID like this:
https://github.com/dropbox/SwiftyDropbox/blob/5bda01b02a87568801a5b2af07e3fdb075dce69c/Source/SwiftyDropbox/Shared/Handwritten/OAuth/OAuth.swift#L588

v10 uses a different approach and fails to create an instance of `Bundle`, thereby returning `nil`: https://github.com/dropbox/SwiftyDropbox/blob/6f247e4571dc672f571b5825df0cc4e417505dd8/Source/SwiftyDropbox/Shared/Handwritten/OAuth/SecureStorageAccess.swift#L127-L131

It seems that the path returned from the function `appBundlePath` is missing the leading slash.

A generic keychain item name also means that all apps using the v10 SDK will currently attempt to use the same keychain item.
Unfortunately, fixing this means that all existing installations of apps that are using v10 will have to re-authorize...

**Comment by julianlocke** [comment]
I appears that some versions of macOS successfully construct the Bundle even with the malformed path. What version of macOS are you seeing this behavior on?

**Comment by andreasley** [comment]
I'm using macOS Sonoma 14.3.1 (23D60), currently the most recent version.

When I'm debugging a build and breaking at the return of `appBundleId()`, I can successfully construct a bundle with the following code:

```swift
Bundle(path: "/" + bundlePath)
```

**Comment by julianlocke** [comment]
I wasn't able to repro this even on 23D60, there must be some other difference between our environments. Either way, the bundle path should include a leading slash. Newly released version 10.0.4 fixes this issue.
