### ISSUE TITLE
Incorrect Route Names in ReconnectionHelper

### ISSUE THREAD

**Issue by dsmurfin** [dropbox/SwiftyDropbox#426]
It appears that some of the route names are incorrect in ReconnectionHelpers.swift

https://github.com/dropbox/SwiftyDropbox/blob/70b78fcc3231ba6d0ed8529b7fa2c603c9d23e6e/Source/SwiftyDropbox/Shared/Generated/ReconnectionHelpers.swift#L129

I believe the above should be `upload_session/start` for example, instead of `uploadSessionStart`? See the returned routeName in the error below. If a background session uses a simple `upload` instead of a session this succeeds as the routeName `upload` matches the case in `ReconnectionHelpers.swift`.

> attemptReconnect returned requests [Swift.Result<SwiftyDropbox.DropboxBaseRequestBox, SwiftyDropbox.ReconnectionError>.failure(SwiftyDropbox.ReconnectionError(reconnectionErrorKind: SwiftyDropbox.ReconnectionErrorKind.missingReconnectionCase, taskDescription: Optional("10.0.7#?///?#{\"upload\":{\"_0\":{\"routeName\":\"upload_session\\/start\",\"originalSDKVersion\":\"10.0.7\",\"clientProvidedInfo\":\"\",\"routeNamespace\":\"files\"}}}")))]

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by dsmurfin** [comment]
Thanks @greg-db I'd honestly be surprised if this is the case as it means background upload sessions have always been broken for v10+, but equally this seems like the onky culprit from what I can see. If I modify the raw value of these cases to match what I'm expecting the route name to be no errors are thrown and it returns successfully.
