### ISSUE TITLE
Swift 2.0 not supported

### ISSUE THREAD

**Issue by dickverbunt** [dropbox/SwiftyDropbox#5]
It doesn't support the new syntax of Swift 2.0 yet. Will this be added in the near future?

I know it uses Alamofire and it's not fully Swift 2.0 yet but has a working `swift-2.0` branch.

**Comment by varenc** [comment]
hey @dickverbunt,

we hear you on this!  We're likely going to be dropping Alamofire support in the next update which will make it easier for us to make a swift-2.0 branch as well.

**Comment by dickverbunt** [comment]
@varenc Thanks for the update. Looking forward to it.

**Comment by l0veweap0n** [comment]
Please do point out this lack of support for Swift 2 in the docs & Tutorial on the Dropbox website(s).  Wasted a lot of time trying to fix syntax errors & resolve dependencies, after going through the install/tutorial before I found this thread.

**Comment by rpearl** [comment]
Hi all,

I have opened up swift 2 support, for now in a separate branch until swift 2 and Xcode 7 are out of beta. The swift-2.0 branch is [here](/dropbox/SwiftyDropbox/tree/swift-2.0).

This requires the latest Xcode 7 beta 6, available on [Apple's developer site](https://developer.apple.com/xcode/downloads/).

We currently still depend on Alamofire (2.0.0 branch from the swift-2.0 tree)--I wonder if anyone has any opinions as to whether we should work for a standalone library or whether continuing to depend on Alamofire is okay.

I'll leave this open until we merge to master.

**Comment by tkrajacic** [comment]
Libraries that don't have dependencies are always easier to manage. Alamofire is not that big a deal, since it is well tested and maintained, but if you can get rid of it it would definitely be better.

**Comment by rpearl** [comment]
Swift 2 is now merged to master!
