### ISSUE TITLE
Check if folder or file

### ISSUE THREAD

**Issue by combi83** [dropbox/SwiftyDropbox#51]
Hi, after calling client.files.listFolders(path: ""), I need to know if resulting files are files or folder. As properties I found only name, description, lowerPath and parentSharedFolderId. How can I do that?

Thank you

**Comment by varenc** [comment]
The type of the values in entries should either by FileMedata(https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FileMetadata.html) or FolderMetadata(https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FolderMetadata.html).

All of those are subclasses of Metadata.  The specific type will let you know if they're a file or folder.  Also for support questions and not SDK issues posting on our forum should get you a faster response. https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development?sort_by=recent_activity
