### ISSUE TITLE
Internal Server Error on file move

### ISSUE THREAD

**Issue by sidlatau** [dropbox/SwiftyDropbox#53]
Hello, 

When I upload picture to Dropbox and then rename it, I am getting such errors:
[request-id b1c84d48c139951ea50ad5bc8546b661] Internal Server Error 500: 
[request-id c53c18035fa0227a57503e53b40ce294] Internal Server Error 500:  
[request-id bf9ec42e85c20f9d8ffe9c932b09fd62] Internal Server Error 500: 

SwiftyDropbox 3.0.0 version used. Tested on simulator and on iPhone6. This problem appears frequently with one user, who has more than 100GB data in his Dropbox. With users with smaller amount of data upload and rename seems work fine. 

Can I do something in my app to prevent this problem?

**Comment by greg-db** [comment]
Sorry for the delay @sidlatau . Are you still seeing this errors?

**Comment by sidlatau** [comment]
No, I can not reproduce problem now. But no changes were done in my code. Do you know the source of these problems - maybe it can be solved in client code to avoid errors in the future?

**Comment by greg-db** [comment]
Thanks! It was a transient server-side issue, so not something that can be fixed in the client code. You can have your app retry these requests if/when issues like this occur though.

**Comment by joelcrawford** [comment]
is there a anyone to catch the error on the client side code?

**Comment by greg-db** [comment]
Yes, for example, here's a sample of using the `download` method and handling each error:

```
Dropbox.authorizedClient!.files.download(path: path, destination: destination).response { response, error in
    if let (metadata, url) = response {
        print("*** Download file ***")
        print("Downloaded file name: \(metadata.name)")
        print("Downloaded file url: \(url)")
    } else if let callError = error {
        switch callError as CallError {
            case .RouteError(let boxed, let requestId):
                print("RouteError[\(requestId)]:")
                switch boxed.unboxed as Files.DownloadError {
                case .Path(let fileLookupError):
                    print("PathError: ")
                    switch fileLookupError {
                    case .MalformedPath(let malformedPathError):
                        print("MalformedPath: \(malformedPathError)")
                    case .NotFile:
                        print("NotFile")
                    case .NotFolder:
                        print("NotFolder")
                    case .NotFound:
                        print("NotFound")
                    case .RestrictedContent:
                        print("RestrictedContent")
                    case .Other:
                        print("Other")
                    }
                case .Other:
                    print("Other")
            }
            case .BadInputError(let message, let requestId):
                print("BadInputError[\(requestId)]: \(message)")
            case .HTTPError(let code, let message, let requestId):
                print("HTTPError[\(requestId)]: \(code): \(message)")
            case .InternalServerError(let code, let message, let requestId):
                print("InternalServerError[\(requestId)]: \(code): \(message)")
            case .OSError(let err):
                print("OSError: \(err)")
            case .RateLimitError:
                print("RateLimitError")
            }
            
    }
}
```

**Comment by joelcrawford** [comment]
wow! thanks for the complete code...
