### ISSUE TITLE
Bad Input: Error

### ISSUE THREAD

**Issue by talkaboutdesign** [dropbox/SwiftyDropbox#56]
No matter what API I tried calling getting this error in Xcode. 
`
Bad Input: Error in call to API function "users/get_current_account": request body: could not decode input as JSON`

**Comment by greg-db** [comment]
This sounds like a bug that existed in version 2.0.3. What version of SwiftyDropbox do you currently have installed? If you're not already on the latest version, 3.0.0, please upgrade to that and try again. Let me know if that does or doesn't solve it.
