### ISSUE TITLE
[fatal error: unexpectedly found nil while unwrapping an Optional value] @ BabelSerializers.swift Line247

### ISSUE THREAD

**Issue by spahol** [dropbox/SwiftyDropbox#58]
I have file that create/modify at 29/Feb/2016 in my app folder.
When I try to listFolder, the fatal error happen !!!
I track code until see that file BabelSerializers.swift Line247 is generated this error !!!

As soon as you can fix this issue, please inform me. I can help to test it again.

PS. one more thing, this error is same in SwiftyDropbox version 2.0.2 and 3.0.0

**Comment by greg-db** [comment]
Can you share the relevant code snippet(s), as well as the full text of the error/output? Thanks in advance!

**Comment by redmason** [comment]
This can happen if listFolder (and other functions) are called without retaining the return value, because internally, weak _self gets released. One solution is to follow the example code by calling .response() on the return value.

Suggestion to SDK team: Add an assert with a warning message if _self is nil in the response handler.

**Comment by macteo** [comment]
I've replicated the issue with this very simple code:

```swift
if let client = Dropbox.authorizedClient {
    let files = client.files
    
    files.getThumbnail(path: "image.jpg", format: .Jpeg, size: .W640h480, destination: { (url, response) -> NSURL in
        let documentsPath = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0]
        let url = NSURL(  fileURLWithPath: "\(documentsPath)/image.jpg")
        return url
    })
}
```

Removing the `weak` keyword as suggested in pull request #79 solves the issue for me, but it probably causes a leak. Probably the whole `init` function should be refactored.
