### ISSUE TITLE
[!] No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by MariamNers** [dropbox/SwiftyDropbox#59]
Okay i am sorry if this is dumb question, but i am trying to install the SwiftyDropbox SDK, and i am following the steps outlined here :
**3) In your project directory, create a new file and call it "Podfile". Add the following text to the file
**
Now do i create a simple Podfile.txt in my app directory or what? Because when i do so and run pod install i get this error : [!] No `Podfile' found in the project directory. 

What am i doing wrong?
Thanks

**Comment by greg-db** [comment]
The file should just be named "Podfile" with no extension, and not "Podfile.txt". Hope this helps!

**Comment by MariamNers** [comment]
Thanks Greg, although now i am getting this error : 

[!] Invalid `Podfile` file: syntax error, unexpected $undefined, expecting '}'
{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf340
  ^
/Users/Desktop/Graphics/Podfile:2: syntax error, unexpected $undefined, expecting '}'
{\fonttbl\f0\fnil\fcharset0 Consolas;}
  ^
/Users//Desktop/Graphics/Podfile:2: syntax error, unexpected '}', expecting end-of-input. Updating CocoaPods might fix the issue.

Although i just updated my cocoapods. Do you know how to fix this?

**Comment by greg-db** [comment]
That error indicates there's an issue with the contents of your Podfile. It should just be:
```
platform :ios, '8.0'
use_frameworks!

pod 'SwiftyDropbox'
```
Based on your output, you seem to have some rich text in there instead, perhaps because you initially created it as a rich text file in a rich text editor. Replace the contents with the plain text above and try again.

**Comment by MariamNers** [comment]
got it, thanks :)
