### ISSUE TITLE
A regular path (not lowercased) for Metadata

### ISSUE THREAD

**Issue by andrew8712** [dropbox/SwiftyDropbox#60]
Are you guys planning to include `path` property to `Metadata` class? Or may be there is a way to get it?

**Comment by greg-db** [comment]
We have actually just added a `path_display` property to `Metadata` in the [HTTP API](https://www.dropbox.com/developers/documentation/http/documentation#files-get_metadata). That should get picked up and available in SwiftyDropbox in the next release.

**Comment by andrew8712** [comment]
When you're planning to release the next version?

**Comment by greg-db** [comment]
I don't have a specific timeline right now, but I don't expect it should be too long from now.

**Comment by scobbe** [comment]
Added in ab71ab5
