### ISSUE TITLE
Tutorial on how to download file from DB folder

### ISSUE THREAD

**Issue by MariamNers** [dropbox/SwiftyDropbox#61]
Is there a tutorial on your website on how to download a file from DB folder onto a desktop? Sorry if this is a silly question, i am just struggling a little on this journey. Thanks

**Comment by greg-db** [comment]
The SwiftyDropbox tutorial on the Dropbox developers site covers downloading files:

https://www.dropbox.com/developers/documentation/swift#tutorial

Hope this helps!

**Comment by prabhjot-singh-gogana** [comment]
Well, I created the reusable class 'DropBox-Helper' which provides a simple and effective way to download files using the iOS DBChooser. you just have to write one line for download the files. https://github.com/prabhjot-singh-gogana/DropBox-Helper. I hope this will help you.
