### ISSUE TITLE
How to locate the folder?

### ISSUE THREAD

**Issue by MariamNers** [dropbox/SwiftyDropbox#64]
I apologise if this is a silly or irrelevant question, i just couldn't find suitable answers online. Right now i download the file from drop box, and it saves in my simulator directory which is 

`/Users/Library/Developer/CoreSimulator/Devices/84437FF1-FFC4-4065-BEA6-42DF3153CD54/data/Containers/Data/Application/0958534F-ED94-4EE1-B189-04B918260AD3/Documents`

How do i locate that file in that folder from another class in my project? Is this possible to do? Thanks!

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/hc/en-us/community/posts/206077616-How-do-i-locate-the-file- ]
