### ISSUE TITLE
SwiftyDropbox JSON enum conflicts with SwiftyJSON

### ISSUE THREAD

**Issue by robbiet480** [dropbox/SwiftyDropbox#65]
Hi all,

When trying to `import `[`SwiftyJSON`](https://github.com/SwiftyJSON/SwiftyJSON) and `import SwiftyDropbox` in the same file I get this error: "'JSON' is ambiguous for type lookup in this context'".

It looks like the problem comes from SwiftyDropbox having [this](https://github.com/dropbox/SwiftyDropbox/blob/a79b6c21c0222d088904c474ba901cb833101db2/Source/BabelSerializers.swift#L5) public JSON enum.

I'm hoping that the SwiftyDropbox JSON could be renamed or an alternate solution proposed. 

See also: comments by @atomkirk on both #27 and #29.

Thanks!

**Comment by wkiefer** [comment]
When you have the same public export from two different modules, you have to namespace the type with the module to let the compiler know which one you want.

e.g. In your case you'd use
`let foo = SwiftyJSON.JSON()`

Let me know if that solves your issue - thanks!

**Comment by robbiet480** [comment]
D'oh, easy enough, just didn't know the right words to Google for. Thanks for the quick reply and assist @wkiefer!
