### ISSUE TITLE
Frequent Upload failures with no useful error code...

### ISSUE THREAD

**Issue by btanner** [dropbox/SwiftyDropbox#66]
We upload photos in batches of 30-50 from our job sites.  I have a simple loop based on the example code which uploads the files in a loop. Since behind the scenes your code (or alamofire) is spawning asynchronous calls to upload in parallel, I have a condition I check and sleep until the current file is done.

When the error comes back I get HTTP ERROR: without any status code.  My code keeps track of which files synced successfully and which fails. So, when uploading 50 photos, about 4-10 will work, then I sync again and do 4-10 more, repeating until all done.  I could internalize this retry I guess, but it seems weird to have some many failures so I wanted to investigate.  The files are 4-6 MB.

Here is a rough look at the code

```SWIFT
dropboxClient.files.upload(path: dropboxFilePath,mode:Files.WriteMode.Overwrite,body: NSData(contentsOfFile: devicePathToFile)!).response  { response, error in
						syncsCompleted++;
						
						if let _ = response {
							self.syncStatusByFilename[localFileName] = true;
							print("Completed upload of \(localFileName)");
						} else {
							print("Failed upload of \(localFileName)");
							debugPrint(error!)
						}
}
```

Any suggestions as to what might be happening or how to dig deeper?

**Comment by btanner** [comment]
Nevermind. I'm an idiot.  I was decrementing the "activeTransfers" counter when a sync succeeded or failed, but I was never incrementing it to begin with. So, my code as trying to upload all 50 files at once in parallel. Hopefully should be resolved now.

**Comment by btanner** [comment]
Apparently sleeping is not the right solution because that causes the rest of the code to break because its blocked.

Is there any official (or unofficial advice) on what pattern to use to throttle process uploads to 1-3 at a time?

**Comment by btanner** [comment]
I got it working with a custom serial queue (1 line of code), wrapping up all my code in a closure to be dispatched to the serial queue, a boolean to track completion, and then a sleep at the end of the new closure to block the start of the next file until done=true. 

Seems to work well enough.

**Comment by tjdhome** [comment]
I had exactly the same problem. In IOS, normally you would let NSURLSession handle the coordination of simultaneous transfers (by using a singleton and letting it handle the pipe to a single URL). I eventually stopped using SwiftyDropbox for most file transfers and rolled my own, using PromiseKit to make the coordination of a few dozen top-level operations easy-peasy. My recollection is that Alamofire is the culprit and SwiftyDropbox is a casualty- but I haven't updated since SwiftyDropbox 0.7 (if it aint broke...) so perhaps there is light at the end of that rather ugly tunnel. Best of luck.

**Comment by greg-db** [comment]
Glad to hear you got this sorted out, and thanks for the input t.j.! 

I don't believe we have any specific guidance on patterns like this. It's up to you if/how many uploads to kick off at once, and how to do so, but a common choice is to allow a maximum of 4 simultaneously.

For reference the current version of SwiftyDropbox, v3.0.0, has an Alamofire dependency of "~> 3.1". At version 0.7, the dependency was "~> 2.0.0-beta.3".
