### ISSUE TITLE
Background content download

### ISSUE THREAD

**Issue by andrew8712** [dropbox/SwiftyDropbox#71]
Hey guys, are you planning to implement this feature mentioned in [Apple docs](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html)?
I see `SwiftyDropbox` uses `Alamofire.Manager` with default `NSURLSessionConfiguration`. It'd be great to add another manager for background executions, which would have `NSURLSessionConfiguration.backgroundSessionConfigurationWithIdentifier(...)`

**Comment by greg-db** [comment]
I can't make any promises, but we'll consider this a feature request. Thanks!

**Comment by greg-db** [comment]
This was added in [version 3.1.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/3.1.0).
