### ISSUE TITLE
blank screen show when net disconnect in middle 

### ISSUE THREAD

**Issue by Sahilberi** [dropbox/SwiftyDropbox#73]
Hi,
    i'm trying integrate my app with dropbox and successfully integrated. but when user try to authenticate why there were no progress  indicator is shown.?  and in middle if user net is disconnect only blank page is shown with cancel toolbar. why there any message is not shown?

**Comment by greg-db** [comment]
HI @Sahilberi , to make sure where understand your questions, can you elaborate and share the steps to to reproduce the issue, as well as some screenshots showing it? Thanks in advance!

**Comment by Sahilberi** [comment]
when i authenticate the user using  below code, a viewcontroller is present and in middle if internet is disconnect nothing message is show to user.
 (Dropbox.authorizedClient == nil)  {
      Dropbox.authorizeFromController(self)
    }
![screen shot 2016-04-13 at 11 32 11 am](https://cloud.githubusercontent.com/assets/7422405/14484203/f5e50138-016b-11e6-8bfc-58824fb2dc75.png)

**Comment by greg-db** [comment]
Thanks, that's helpful!

**Comment by Sahilberi** [comment]
What should i do in  this case? what's the solution for this?

**Comment by greg-db** [comment]
This looks like something we'll have to improve in the SDK itself.

In the meantime, if you'd like, you can try testing for network connectivity before calling `authorizeFromController`.

**Comment by Sahilberi** [comment]
i am already checking network connectivity before calling authorizeFromController. but it takes too much time to show dropbox sign in  page. and in processing time if internet is gone how do i tell user what's the problem?

**Comment by greg-db** [comment]
Showing a loading indicator while the page is loading is one of the improvements we'll have to make in the SDK itself.

I don't know if there's a good way for you to handle the case where the Internet connection fails during the load from your side unfortunately.

**Comment by greg-db** [comment]
As of [version 3.1.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/3.1.0), SwiftyDropbox should will show an indicator when loading the page, as well as an error when it is unable to.

**Comment by Sahilberi** [comment]
Cool! Thanks.
