### ISSUE TITLE
 could not build objective-c module alamofire

### ISSUE THREAD

**Issue by kaushalPal86sq** [dropbox/SwiftyDropbox#74]
I'am trying to integrate SwiftyDropbox in my project. But it keeps on giving error " could not build objective-c module alamofire" The SwiftyDropbox version in use is "3.0.0". I'am using xcode 7.2 on  OS X El Capitan.

**Comment by greg-db** [comment]
Hi @kaushalPal86sq if you're using Xcode 7.2, this may be the same issue as this:

https://stackoverflow.com/questions/36261833/xcode-swift-dropbox-erors-in-alamofire-souce-codes/36271175#36271175

If not, please let me know the steps to reproduce the issue.

**Comment by kaushalPal86sq** [comment]
**@greg-db ** thanks a lot. it helped.
