### ISSUE TITLE
When request fails due to no internet access, a more useful error should be provided

### ISSUE THREAD

**Issue by sadlerjw** [dropbox/SwiftyDropbox#82]
Currently if the device is offline when a request is issued, the error is reported as `.HTTPError(nil, "", nil)`. Because the underlying `NSError` is not passed along, this makes it impossible to properly handle the situation.

If we look at `BabelRequest.handleResponseError` in this case, `response` is actually `nil`. I propose that when `response == nil`, the error returned is instead `.OSError(error)`.

**Comment by greg-db** [comment]
Thanks! I'll send this along to the team.

**Comment by sadlerjw** [comment]
If it will help, I'd be happy to submit a pull request. Thanks!

**Comment by scobbe** [comment]
Closed by: https://github.com/dropbox/SwiftyDropbox/commit/4c53c8ec4bc7b2cc1cf511863342e2d354c3b387
