### ISSUE TITLE
Error when uploading and iPhone is locked

### ISSUE THREAD

**Issue by John1843** [dropbox/SwiftyDropbox#83]
I am trying to upload a file with client.files.upload(path: pathAndFileNameDropbox, body: nsurl!).

In order to make it finish successfully when the iOS app is closed, I start a long-running background task:

[[UIApplication sharedApplication] beginBackgroundTaskWithExpirationHandler

However, when I lock the iPhone, the upload is not finished correctly. I get an NSError with the description given below.

What can I do?

> expression produced error: /var/folders/wl/_z5_bmvs5kq_ctqqpfqxk1mr0000gn/T/lldb/94056/expr3.swift:1:141: error: use of unresolved operator '>>>'
> $__lldb__DumpForDebugger(Swift.UnsafePointer<Swift.Optional<SwiftyDropbox.CallError<SwiftyDropbox.Files.UploadErrorSerializer.Type.ValueType>>>(bitPattern: 0x101e1ccd0).memory)
>                                                                                                                                             ^~~
> /var/folders/wl/_z5_bmvs5kq_ctqqpfqxk1mr0000gn/T/lldb/94056/expr3.swift:1:45: error: non-associative operator is adjacent to operator of same precedence
> $__lldb__DumpForDebugger(Swift.UnsafePointer<Swift.Optional<SwiftyDropbox.CallError<SwiftyDropbox.Files.UploadErrorSerializer.Type.ValueType>>>(bitPattern: 0x101e1ccd0).memory)
>                                             ^
> /var/folders/wl/_z5_bmvs5kq_ctqqpfqxk1mr0000gn/T/lldb/94056/expr3.swift:1:60: error: non-associative operator is adjacent to operator of same precedence
> $__lldb__DumpForDebugger(Swift.UnsafePointer<Swift.Optional<SwiftyDropbox.CallError<SwiftyDropbox.Files.UploadErrorSerializer.Type.ValueType>>>(bitPattern: 0x101e1ccd0).memory)

```
                                                       ^
```

**Comment by greg-db** [comment]
[Cross-linking for reference: https://stackoverflow.com/questions/37371139/error-when-uploading-using-swiftydropbox-and-iphone-is-locked ]

Can you share the rest of the relevant code? Thanks in advance!

**Comment by julianlocke** [comment]
The latest version of SwiftyDropbox supports background networking. Read more about it here: https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Major-SwiftyDropbox-update-available/td-p/737816
