### ISSUE TITLE
Please update the SwiftyDropbox.podspec to 3.1.0

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#84]
DropboxClient.swift has updated, but CocoaPods not yet.

Thanks.

**Comment by greg-db** [comment]
We have had some commits on the repo here, but we haven't done a release yet. We should be doing one relatively soon though.

**Comment by allea** [comment]
Any big changes to current background tasks? Working on a product which rely on this feature.

**Comment by greg-db** [comment]
You can find information on what's changing in the commit messages:
https://github.com/dropbox/SwiftyDropbox/commits/master
