### ISSUE TITLE
Can not access backgroundCompletionHandler

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#86]
To set the `BabelClient.backgroundManager.backgroundCompletionHandler`

`public var backgroundCompletionHandler: (() -> Void)?`

Get error:
`error: value of type 'DropboxClient' has no member 'backgroundManager'
        let a = self.dropboxClient.backgroundManager
`

**Comment by greg-db** [comment]
Are you using the latest release (v3.0.0) from CocoaPods? The `backgroundManager` was only added recently, and isn't yet in a released version.

**Comment by allea** [comment]
Using the 3.1.0 here; you can take it as a feature request :-)
