### ISSUE TITLE
getMetadata call on deleted file throws error rather than returning Files.DeletedMetadata object

### ISSUE THREAD

**Issue by bhhales** [dropbox/SwiftyDropbox#87]
When I use listFolders with includeDeleted set to true, my returned entries contain deleted files as desired.  However, when I iterate through the entries and do a getMetadata call on each file, this call fails on deleted files, returning the following error:

[request-id ccbeb40958350a20c28d39c4770710b0] API route error - {
    ".tag" = path;
    path =     {
        ".tag" = "not_found";
    };
}

I expected to be able to do a
**if let deletedFile = metadata as? Files.DeletedMetadata**
to detect if a file was deleted, similar to testing for Files.FileMetadata and Files.FolderMetadata, but never get to this code due to the error returned from the getMetadata call.

Is there a different or better way to test if a file has been deleted?

My code is a slightly modified version of the sample code, as I learn the SDK, so I don't think I'm doing anything that far off.

Full sample code:

func loadFiles()
{

    // verify valid client
    if let client = Dropbox.authorizedClient
    {
        print("success, client is \(client)")

        var fileList = [String]()

        // List contents of dropbox app folder
        client.files.listFolder( path: "",
                                 recursive: false,
                                 includeMediaInfo: false,
                                 includeDeleted: true).response { response, error in
            if let result = response
            {
                print("Folder contents:")
                for entry in result.entries
                {
                    print("Found file: \(entry.name)")

                    // add filename to list
                    fileList.append( entry.name)

                    // get file path
                    let destination : (NSURL, NSHTTPURLResponse) -> NSURL = { temporaryURL, response in
                        let fileManager = NSFileManager.defaultManager()
                        let directoryURL = fileManager.URLsForDirectory(.DocumentDirectory, inDomains: .UserDomainMask)[0]
                        let pathComponent = "\(entry.name)"
                        return directoryURL.URLByAppendingPathComponent(pathComponent)
                    } // end path closure
                    
                    // Get file (or folder) metadata
                    client.files.getMetadata(path: "/\(entry.name)").response { response, error in
                        print("*** Get file metadata ***")
                        if let metadata = response {
                            if let deletedFile = metadata as? Files.DeletedMetadata
                            {
                                print("\(deletedFile.name) is a deleted file")
                                // delete the old file
                            }
                            else if let file = metadata as? Files.FileMetadata {
                                print("This is a file with path: \(file.pathLower)")
                                print("File size: \(file.size)")
                                print("Uploaded on: \(file.clientModified)")
                                print("Dropbox modified on: \(file.serverModified)")
                            } else if let folder = metadata as? Files.FolderMetadata {
                                print("This is a folder with path: \(folder.pathLower)")
                            }
                        } else {
                            print("Metadata lookup error for file \(entry.name): \(error!)")
                        }
                    }

                    // download file
                    client.files.download(path: "/\(entry.name)", destination: destination).response { response, error in
                        if let (metadata, url) = response {
                            print("*** Download file ***")
                            //let data = NSData(contentsOfURL: url)
                            print("Downloaded file name: \(metadata.name)")
                            print("Downloaded file url: \(url)")
                            //print("Downloaded file data: \(data)")
                        }
                        else
                        {
                            print("Download error: \(error!)")
                        }
                    } // end download closure

                } // loop for all files in dropbox app folder

                // test if new file was downloaded
                    // upload stored last download time

            }
            else
            {
                print("List error: \(error!)")
            }
        } // end of listFilder closure

    } // end if authorized client
    else
    {
        print("invalid client")
    }

} // end of loadFiles()

**Comment by greg-db** [comment]
In order to get information on deleted items via getMetadata, the API requires an `includeDeleted` parameter for that call as well. That parameter is newer than the latest SwiftyDropbox SDK release though, so it's not currently available. It should be included in the next release though.

**Comment by greg-db** [comment]
SwiftyDropbox now supports the `includeDeleted` parameter on [`getMetadata`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes11getMetadataFT4pathSS16includeMediaInfoSb14includeDeletedSb31includeHasExplicitSharedMembersSb_GCS_10RpcRequestCCS_5Files18MetadataSerializerCS2_26GetMetadataErrorSerializer_) as of [version 3.1.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/3.1.0).

**Comment by bhhales** [comment]
Thanks!  Looking forward to experimenting with it. Barry HalesHales Consulting Services5401 Parkwood DriveRaleigh NC 27612(919) 782-5058bhhales@att.net
 

    On Tuesday, August 2, 2016 5:27 PM, Greg K <notifications@github.com> wrote:
 

 SwiftyDropbox now supports the includeDeleted parameter on getMetadata as of version 3.1.0.—
