### ISSUE TITLE
Build as a standalone framework

### ISSUE THREAD

**Issue by codeOfRobin** [dropbox/SwiftyDropbox#88]
Is there any way to build this project separately( I see no .xcodeproj file)? To fix bugs/contribute changes etc?

**Comment by allea** [comment]
It uses cocoapod, which will generate proper Xcode config when installed.

**Comment by greg-db** [comment]
@codeOfRobin Right now we only support installing it via CocoaPods, but do feel free to make changes that way and submit pull requests.
