### ISSUE TITLE
XCode 8 beta and Swift 3 support

### ISSUE THREAD

**Issue by thomasweller** [dropbox/SwiftyDropbox#90]
Hi,

are there any plans to upgrade this to the latest Swift version? If yes, when~ish?

Thanks for the great work,

Thomas

**Comment by greg-db** [comment]
This is something I expect we'll do, but I don't have a timeline to offer right now.

**Comment by akshaynhegde** [comment]
Any update?

**Comment by greg-db** [comment]
This is in the works, and we'll be testing it against the new Xcode 8 GM before releasing it. I don't have a timeline right now, but it shouldn't be too much longer.

**Comment by allea** [comment]
Will the 2.3 version also keeps for a while?

For a project relying on many pods, the syantex change will be a nightmare.



This is in the works, and we'll be testing it against the new Xcode 8 GM before releasing it. I don't have a timeline right now, but it shouldn't be too much longer.

-

**Comment by greg-db** [comment]
Yes, I believe we'll have separate branches for 2 and 3.

**Comment by cliftonlabrum** [comment]
Will the upcoming update to SwiftyDropbox pull in a newer version of Alamofire? I believe `Alamofire 3.5` is required to support `Swift 2.3`, and `Alamofire 4.0.x` is required to support `Swift 3.0`.

Secondarily, is there a way for me to change (before the update) which version of Alamofire that SwiftyDropbox adds so I can get my app to build?

**Comment by scobbe** [comment]
@cliftonlabrum: Yes, I'll get an update out ASAP that includes the new Alamofire version.

In the meantime, if you want to fetch a different version of Alamofire, I would recommend using Carthage to download the desired version from https://github.com/Alamofire/Alamofire as a framework file, then delete the Alamofire framework in your Pods project, and drag and drop the new Alamofire framework into the project.

**Comment by cliftonlabrum** [comment]
Can you give us a ballpark estimate on this? Please take this short quiz:

It will take ________ for a SwiftyDropbox release that supports Swift 2.3 + Alamofire 4.0.
**a.** Days
**b.** Weeks
**c.** Months
**d.** Years

Thanks 😀

**Comment by scobbe** [comment]
@cliftonlabrum: Haha I will really try to have a working version of this out by end of day tomorrow, along with a bunch of other updates. Thanks for your patience.

**Comment by magicboker** [comment]
I need the Xcode 8 support ASAP, too.
After upgrading to Xcode 8, i can not compile my app due to the Alamofire issue in SwiftyDropbox pod.

**Comment by cliftonlabrum** [comment]
Support for Xcode 8 and Swift 2.3 is now available: https://github.com/dropbox/SwiftyDropbox/releases/tag/3.2.0

**Comment by kallipigous** [comment]
I'm still getting the old version through cocoapods

**Comment by cliftonlabrum** [comment]
It looks like they just updated the pod. In Terminal, be sure to do:

`pod repo update`

...and then try `pod install` again. It just installed SwiftyDropbox 3.3.1 for me.

**Comment by cliftonlabrum** [comment]
Thank you @scobbe and @greg-db! 👍

**Comment by kristofvanlandschoot** [comment]
This is not yet the release with Swift 3 support, or is it?

**Comment by cliftonlabrum** [comment]
No, I think this is only Swift 2.3. But it at least makes it so you can use Xcode 8. 

Swift 3.0 requires Alamofire 4.x, but SwiftyDropbox 3.3.1 only includes Alamofire 3.5.

**Comment by scobbe** [comment]
This is 2.3 – 3 is coming in an hour or two! Thanks for your patience everyone

**Comment by kallipigous** [comment]
I cant get it to work at all. It installs 3.3.1 but xcode 8 still complains that alamo and swiftydropbox need to be updated (the server trust policy) and after it does so I get "ld: library not found for -lPods"
 If I update the pods I go through the whole circle again.  If I remove swiftydropbox all s fine.

**Comment by magicboker** [comment]
After updating the latest version, Xcode 8 still asked to convert and compile with a lot of errors. It still didn't compile in Xcode 8.

**Comment by magicboker** [comment]
Dropbox.authorizeFromController has changed the parameters:
`    public static func authorizeFromController(sharedApplication: UIApplication, controller: UIViewController, openURL: (NSURL -> Void), browserAuth: Bool = false)`
What should i put in the openURL parameter?
It used to be controller only.

**Comment by cliftonlabrum** [comment]
This is what I used and it works great:

`Dropbox.authorizeFromController(UIApplication.sharedApplication(), controller: self, openURL: {(url: NSURL) -> Void in UIApplication.sharedApplication().openURL(url)})`

**Comment by simplyAlkaline** [comment]
any updates on Swift 3 compatibility?

**Comment by greg-db** [comment]
We ran in to an issue or two, but it's on the way. Thanks for your patience!

**Comment by ykchau** [comment]
While installing SwiftDropbox 4.0 for xcode 8, I was encountered the following problem 

> - `Alamofire (~> 2.0.2)` required by `SwiftyDropbox (1.0)`

while using only 

> pod 'SwiftyDropbox'



So I change the podfile as below, it works for me, hope it can help someone who encountered the same problem.

platform :ios, '10.0'
use_frameworks!

target 'YOUR_PROJECT_NAME' do
    pod 'Alamofire', #'~> 4.0',
    :git => 'https://github.com/Alamofire/Alamofire.git',
    :tag => '4.0.0'
    pod 'SwiftyDropbox',
    :git => 'https://github.com/dropbox/SwiftyDropbox.git',
    :tag => '4.0.0'

end

**Comment by cliftonlabrum** [comment]
You probably just had an old version cached. 

I think you can just comment out `pod 'SwiftyDropbox'` in your `Podfile` then do `pod install`. This will remove the old pod. Then un-comment it so you have it back and do `pod install` again.

**Comment by andrew8712** [comment]
Any timeline for Swift 3?

**Comment by charlieMonroe** [comment]
@andrew8712 - look at the commits, it seems to be committed: https://github.com/dropbox/SwiftyDropbox/commit/5fbad95f6226adba5ac4470dd86db196df901cd1

**Comment by ajitbala** [comment]
i am getting the following errors after the latest 4.0.0 version. Any clue on whats wrong over here?. Is it some Config errors or SwiftyDropbox issue.
![screen shot 2016-09-16 at 8 57 18 pm](https://cloud.githubusercontent.com/assets/16803675/18591494/7b471e60-7c50-11e6-8a33-522f3b84e5c2.png)
 Pls Help.

**Comment by fernandoR96** [comment]
Hi, when I try to download folder information with this code:
`client.files.listFolder(path: "").response { response, error in
                print()
                print("*** List folder ***")
                if let result = response {
                    print("Folder contents:")
                    for entry in result.entries {
                        print(entry.name)
                    }
                } else {
                    print(error!)
                }
            }
` 
I obtain this error:
fatal error: Type error deserializing: file /Users/.../Pods/SwiftyDropbox/Source/Source/PlatformNeutral/StoneSerializers.swift, line 269
2016-09-16 fatal error: Type error deserializing: file /Users/.../Pods/SwiftyDropbox/Source/Source/PlatformNeutral/StoneSerializers.swift, line 269
(lldb) 
I need help please.

**Comment by simplyAlkaline** [comment]
I am also unable to recompile my Swift project, all worked fine pre Xcode 8 and Swift 3 and now I am getting tons of errors, thus I cannot deploy my app to the app store.

**Comment by scobbe** [comment]
@fernandoR96 @simplyAlkaline: Try re-pulling from CocoaPods to SwiftyDropbox 4.0.1. Things should work now. Let me know.

@ajitbala: Are you using CocoaPods? If you are, try re-pulling.

**Comment by simplyAlkaline** [comment]
I have now downgraded to Xcode 7 so I can deploy my app to the app store. sorry.

**Comment by greg-db** [comment]
@fernandoR96 Actually that might still be a bug in 4.0.1. We're looking into it.

@magicboker @cliftonlabrum the [README](https://github.com/dropbox/SwiftyDropbox) has been updated with the latest information on setting this up.

**Comment by greg-db** [comment]
@fernandoR96 This should be fixed now in 4.0.2

**Comment by greg-db** [comment]
Anyone else following this thread, Swift 3 support should now be fully working in SwiftyDropbox as of 4.0.2. Please grab the latest version and open an issue if you're still having any trouble. Thanks!
