### ISSUE TITLE
OAuth.swift is not App-Extension-Safe

### ISSUE THREAD

**Issue by allea** [dropbox/SwiftyDropbox#91]
when used in an app extension (for background sync), there's build warning; if turned on the "Require Only App-Extension-Safe API", the UIApplication.sharedAppliction(), openURL, canOpenURL will cause build error.

Better add a config API to hide the direct calling of the forbidden API (even if it's not used in the extension):

extension Dropbox {
    static var g_dropbox_app: (() -> UIApplication)?
    static var canOpenURLSel: Selector!
    static var openURLSel: Selector!

    public static func configApp(app: () -> UIApplication, canOpen: Selector, open: Selector) {
        g_dropbox_app = app
        canOpenURLSel = canOpen
        openURLSel = open
    }
}

and replace all the calling to UIApplication.sharedApplication, openURL, canOpenURL with this configured selectors

**Comment by greg-db** [comment]
Thanks! I can't make any promises, but we'll look into it.

**Comment by scobbe** [comment]
Should be fixed by ab71ab5
