### ISSUE TITLE
How can i download all folders names and pathLower under shared folder? & UI Freeze 

### ISSUE THREAD

**Issue by VDenis** [dropbox/SwiftyDropbox#92]
Hi!

How can i download all folders names and pathLower under shared folder?
I found that this method didn't work, it's return only a current folder:

```swift
let path = "path-to-shared-folder"
client.files.listFolder(path: path, recursive: true)
```
    

I use this code, but this freeze the UI from time to time
```swift
@IBOutlet weak var tableView: UITableView!

var folders: [Files.FolderMetadata] = []

func ShowFolders() {
	dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), {
		self.Recursion(self.searchPrefix)
	})
}

func Recursion(path: String) {
	if let client = Dropbox.authorizedClient {
		client.files.listFolder(path: path, recursive: false).response { response, error in
			if let result = response {

				for entry in result.entries {
					if let folder = entry as? Files.FolderMetadata {

						// Add new items
						self.folders.append(folder)
						print("This is a folder with path: \(folder.pathLower)")
						self.Recursion(folder.pathLower)
					}
					dispatch_async(dispatch_get_main_queue(), {
						// Reload data
						self.tableView.reloadData()
					})
				}
			} else {
	            print(error!)
			}
		}
	}
}
```

Thanks for the great library,

Denis

**Comment by greg-db** [comment]
Using `listFolder(path: path, recursive: true)` should certainly recursively list all items under the folder as well. Are you checking the `ListFolderResult.hasMore` value on the response though? If it's true, it means there are more entries to retrieve, and you need to call back to [`listFolderContinue`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes18listFolderContinueFS0_FT6cursorSS_GCS_15BabelRpcRequestCCS_5Files26ListFolderResultSerializerCS2_33ListFolderContinueErrorSerializer_) to get them.
