### ISSUE TITLE
App Transport Security (ATS) Settings

### ISSUE THREAD

**Issue by agiletortoise** [dropbox/SwiftyDropbox#93]
With Apple announcing that App Transport Security (ATS) exceptions will not be allowed by the end of the year, I'm wondering if there are recommended info.plist settings to ensure connections to the backend from the SDK will be allowed under ATS.

For details on the new rules, see WWDC session #706, What's New in Security (https://developer.apple.com/videos/play/wwdc2016/706/)

**Comment by greg-db** [comment]
The Dropbox API has required TLS for a long time now, so I don't believe there should be any issues here or extra work required on your part. That is, the defaults should be fine for use with the Dropbox API.

For reference, I just tried the `nscurl` test from [the `NSAppTransportSecurity` documentation](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html), and all of the Dropbox API domains PASSed with the default configuration.

Feel free to re-open and let me know if I missed anything or if you have any other questions!
