### ISSUE TITLE
Use of unresolved identifier 'Dropbox'

### ISSUE THREAD

**Issue by Dirk23** [dropbox/SwiftyDropbox#94]
Hi,

i started rewriting my App wich i created in ObjC, to Swift. I don't have that much time for Coding, so the project had no progress for months now. Today i found some minutes for fiddling around a bit. So i changed my Podfile, wich is lying in my projects Folder to the suggested Values on the Github Page of Swiftydropbox.

```platform :ios, '8.0'
use_frameworks!
pod 'SwiftyDropbox', '~> 3.0.0'```

After updating cocoa pods to 1.0.1 i ran "pod update" in my projects Folder to update to the newest Version of Swiftydropbox. The result of the update is:


```
user$ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
[!] The dependency `SwiftyDropbox (~> 3.0.0)` is not used in any concrete target.
```

And in my project Xcode warns me for:
`Use of unresolved identifier 'Dropbox'`

My Code imports Swiftydropbox:
`import SwiftyDropbox`

an the function that uses Dropbox is:

```
func dropboxCheckDatabaseFileRevision() ->String {
     var fileRev = ""
     if let client = Dropbox.authorizedClient {
         client.files.getMetadata(path: kDatabaseFileName).response { response, error in
             if let metadata = response {
                 if let file = metadata as? Files.FileMetadata {
                     fileRev = file.rev
                 } else {
                     print(error!)
                 }
             }
         }
     }
     return fileRev
 } 
```

I guess i am holding it wrong, because if this was a bug, i wouldn't be the only one with it, asking for help. What is my fault, why does it not compile?

Any help is appreciated.

Thank you in advance.

Dirk

**Comment by greg-db** [comment]
HI Dirk, it looks like the Podfile included in the instructions for SwiftyDropbox don't work with the latest version of Cocoapods. We'll get our instructions updated.

The Podfile should instead look like this:

```
platform :ios, '8.0' 
use_frameworks!

target "YOUR_PROJECT_NAME" do

    pod 'SwiftyDropbox'

end
```

Be sure to replace YOUR_PROJECT_NAME with your project's name.

**Comment by Dirk23** [comment]
Thank you very much,

i changed my Podfile to:
```platform :ios, '8.0'
use_frameworks!
target "brauhelfer" do
    pod 'SwiftyDropbox'
end```
Then i ran pod install, and there where no errors except some warnings:

```
dirk$ pod install
Analyzing dependencies
Downloading dependencies
Using Alamofire (3.4.1)
Using SwiftyDropbox (3.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] The `brauhelfer [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-brauhelfer/Pods-brauhelfer.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `brauhelfer [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-brauhelfer/Pods-brauhelfer.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

But still i still have the errors in Xcode:"Use of unresolved identifier "Dropbox"
![errors](https://cloud.githubusercontent.com/assets/4200682/16502564/592f1f0e-3f0f-11e6-8dec-06434637f9d1.png)
The frameworks are marked red in Xcode, does that mean anything?

Regards

Dirk

**Comment by greg-db** [comment]
Yes, I think that's not exactly how it's supposed to look. I believe the SwiftyDropbox and Alamofire .frameworks should only be in the "Pods" project. Perhaps something got installed incorrectly between the different versions of CocoaPods, your Podfile, etc. 

What version of Xcode are you using? Are you opening the .xcodeproj file instead of the .xcworkspace by any chance?

You may want to try removing the frameworks and `pod install`ing again.

**Comment by Dirk23** [comment]
I'm using Xcode 7.3 and yes, you are right, I opend the .xcodeproj file instead of the .xcworkspace. But unfortunately using the .xcworkspace didn't solve my problem. It still can't find Swiftydropbox, but now the Import doesn't seem to work.
I deleted all the red .framwork entry and reinstalled via pod install. But after that installation (and opening the .xcworkspace) I still have those re .framwork files in my Xcode and I still can't compile because now the Errormessage says: 

`No such module 'SwiftyDropbox'`

![swiftydropbox_modul_error](https://cloud.githubusercontent.com/assets/4200682/16513548/f4fea1ec-3f65-11e6-9e3d-3f6a34c23f16.png)

I guess I'm still holding it wrong ;)

Regards

Dirk

**Comment by Dirk23** [comment]
@greg-db could you please help?

**Comment by greg-db** [comment]
@Dirk23 Unfortunately I haven't been able to reproduce the state your project is in. I'm not a CocoaPods expert though, so I'm checking with some other members of the team to see if they have insight to offer on this issue.

**Comment by Dirk23** [comment]
I navigated to my project in Finder, deleted the Pod Folder, the Podfile.lock File and the .xcworkspace File. After that i ran pod install in my project Folder where the Podfile still exists. The installation says:
```
dirk$ pod install
Analyzing dependencies
Downloading dependencies
Installing Alamofire (3.4.1)
Installing SwiftyDropbox (3.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] The `brauhelfer [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-brauhelfer/Pods-brauhelfer.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `brauhelfer [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-brauhelfer/Pods-brauhelfer.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```
Then i open the .xcworkspace file and the errors are still there. Xcode doesn't know Dropbox, i can't Import Swiftydropbox, some .framework Files are still married red
![bildschirmfoto 2016-07-05 um 18 48 49](https://cloud.githubusercontent.com/assets/4200682/16592481/2d2635de-42e1-11e6-891d-c181a4f77eb3.png)

**Comment by Dirk23** [comment]
News!!! I almost did it ;)

Now Xcode knows SwiftyDropbox and it seems i can Import it. I deleted all Pod Stuff in my  Projectfolder and deleted the Podfile and Podfile.lock, made a new Podfile like the Tutorial says and installed Swiftydropbox via `pod install`

After that i opened the xcworksapce file and know i get a Autocompletion for the import.

But the convenience Class Dropbox is still marked red with:"Use of unresolved identifiers 'Dropbox' "
Even the Xcode Help knows the Class but i can't build my project!!

![bildschirmfoto 2016-07-07 um 18 09 09](https://cloud.githubusercontent.com/assets/4200682/16660294/fb32359e-446d-11e6-86c7-b17b73b64b9b.png)

What am i doing wrong here? I tried the same on an empty project and everything seems to ok, and the empty App Builds without any error!

Regards

Dirk

**Comment by scobbe** [comment]
@Dirk23: Apologies for the delay on our end. Are you still having trouble integrating SwiftyDropbox into your project?

**Comment by Dirk23** [comment]
Yes, still having the same issues!

**Comment by scobbe** [comment]
And I assume you have tried a totally clean build (empty caches) by running the following in Xcode:

Command + Option + Shift + K

**Comment by Dirk23** [comment]
I did bevore in deleted everything and it didn't do anything. But I didn't try that one after the last 'clean' install. Unfortunately it didn't help. The Warnung still complains about the import and says: "No such modul 'SwiftyDropbox'"

**Comment by scobbe** [comment]
Ah ok, I see. These sorts of issues are quite difficult to debug remotely. Would you be willing to send us a pared-down version of your project so we can debug the issue ourselves? Specifically, you could send us your project as a .zip file to api-support@dropbox.com. That way, we could get to the bottom of the issue. Let us know – thanks for your patience, Dirk.

**Comment by Dirk23** [comment]
Ok, no problem i can send you my project. I would be happy to continue developing on it. Do you need something else from me, or do i just send it zipped to your Adresse. Do you want to check it out of my Git Repo?

**Comment by scobbe** [comment]
Oh, if it's in a GitHub repo, that's great! Please just link me to the repo here and I will take a look. Thanks, Dirk!

**Comment by Dirk23** [comment]
Kind off :)
https://git.diehildebrands.de/ios/brauhelfer.git

**Comment by Dirk23** [comment]
@scobbe did you clone the repo?

**Comment by scobbe** [comment]
@Dirk23: Apologies for the delay again. I was able to get it working on your project with the latest version of SwiftyDropbox (v3.1.0). You can download the .zip here:

https://www.dropbox.com/s/jb7bv06qzmi3sjs/brauhelfer.zip?dl=1

Let me know if this resolves your issue!

**Comment by Dirk23** [comment]
@scobbe i am a bit confused of the version you checked out. It seems that you got an old version. Can you tell me what you did? Or shall i send you the up-to-date Version again to re-do it?

At least, what ever you did fixed the problem, but this was not the Version i used to work on. Looks more like the first commit or something.

**Comment by Dirk23** [comment]
@scobbe now i had a minute to look into what you did. You checked out the Objective-C Version, but i told to check out the Swift Branch!! the Objective-C Version had no problems with Dropbox!! 

Please try again on that version: https://cloud.diehildebrands.de/s/bmKAbIbj1VJE04r
Thank you!

**Comment by Dirk23** [comment]
@scobbe now i had a minute to look into what you did. You checked out the Objective-C Version, but i told to check out the Swift Branch!! the Objective-C Version had no problems with Dropbox!!

Please try again on that version: https://cloud.diehildebrands.de/s/bmKAbIbj1VJE04r
Thank you!

**Comment by scobbe** [comment]
@Dirk23: Oh, sorry, my bad. I will check out the Swift branch later today and see if I can identify the issue! Thanks for your patience.

**Comment by Dirk23** [comment]
@scobbe just Download the zip from here: https://cloud.diehildebrands.de/s/bmKAbIbj1VJE04r

**Comment by scobbe** [comment]
@Dirk23: I looked into your project a little bit. I noticed that if I delete the 'today' entity (in `braueifer` project's build targets), SwiftyDropbox can be successfully imported.

(note also the line `client.files.upload(path: kDatabaseFileName, body: database).response` should be `client.files.upload(path: kDatabaseFileName, input: database).response` 

`body` was changed to `input` in the latest release of SwiftyDropbox.

I'm not totally sure what the `today` entity does, but try debugging by deleting this entity and then re-adding it, if your project needs it. Let me know how it goes.

**Comment by Dirk23** [comment]
@scobbe Yes, thats it. I deleted the today view (haven't done any coding in there by now) and added it again. Now it works like a charm. 

Thank you

**Comment by cliftonlabrum** [comment]
I just installed SwiftyDropbox 4.0.6 via Cocoapods using Swift 3 in Xcode 8, and I'm having this same issue.

![image](https://cloud.githubusercontent.com/assets/2513753/18936920/947ba884-85a0-11e6-9ed0-f575802c57f0.png)

What exactly did @scobbe delete from the project build targets? I have `import SwiftyDropbox` at the top of my files where I use Dropbox.

**Comment by scobbe** [comment]
@cliftonlabrum: `Dropbox` was renamed to `DropboxClientsManager`.

If you get the chance, check out the updated [README](https://github.com/dropbox/SwiftyDropbox#table-of-contents) as it contains info about the most recent updates to the SDK, as well as a lot of other helpful info.

Let me know if this solves your issue!

**Comment by cliftonlabrum** [comment]
That was it. Thank you! :)

**Comment by scobbe** [comment]
No worries! Let us know if anything else comes up. Also note that there have been some other interface changes, such as how you [commence the auth flow](https://github.com/dropbox/SwiftyDropbox#begin-the-authorization-flow).
